# Generated by Django 5.2.17 on 2026-08-17 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'card_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('card_id', models.TextField()),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flashcard_reviews',
                'managed': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('ease_factor__gte', 1.3)), name='flashcard_review_minimum_ease')],
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('lesson_id', models.CharField(choices=[('words', 'Новые слова'), ('grammar', 'Грамматика'), ('review', 'Повторение'), ('quiz', 'Мини-тест')], max_length=16)),
                ('plan_date', models.DateField()),
                ('cards_total', models.PositiveIntegerField(default=0)),
                ('cards_known', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lesson_completions',
                'managed': False,
                'constraints': [models.UniqueConstraint(fields=('user_id', 'lesson_id', 'plan_date'), name='unique_daily_lesson_completion'), models.CheckConstraint(condition=models.Q(('cards_known__lte', models.F('cards_total'))), name='cards_known_not_above_total')],
            },
        ),
    ]
