# Generated by Django 5.2.17 on 2026-08-19 11:03

import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('polish', models.CharField(max_length=160)),
                ('translation', models.CharField(max_length=240)),
                ('example', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('plan_title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('minutes', models.PositiveSmallIntegerField(default=5)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('theory_title', models.CharField(blank=True, max_length=160)),
                ('theory_sections', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.lesson')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'position'), name='unique_question_position')],
            },
        ),
    ]
