# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.db import migrations, models


def seed_content_structure(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    Course = apps.get_model("learning", "Course")
    Topic = apps.get_model("learning", "Topic")
    Lesson = apps.get_model("learning", "Lesson")
    LessonFlashcard = apps.get_model("learning", "LessonFlashcard")

    course = Course.objects.create(
        id="a1-foundations",
        title="Польский с нуля",
        description="Базовые слова и конструкции уровня A1",
        level="A1",
    )
    topic = Topic.objects.create(
        id="first-steps",
        course=course,
        title="Первые шаги",
        description="Приветствия, простые ответы и основы грамматики",
        emoji="👋",
    )
    for lesson in Lesson.objects.all():
        lesson.kind = lesson.id if lesson.id in {"words", "grammar", "review", "quiz"} else "words"
        lesson.topic = topic
        lesson.save(update_fields=("kind", "topic"))
    for position, flashcard in enumerate(
        apps.get_model("learning", "Flashcard").objects.order_by("position", "id")
    ):
        LessonFlashcard.objects.create(
            lesson_id="words", flashcard=flashcard, position=position
        )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_seed_sqlite_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('words', 'Новые слова'), ('grammar', 'Грамматика'), ('review', 'Повторение'), ('quiz', 'Мини-тест')], default='words', max_length=16),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.course')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.topic'),
        ),
        migrations.CreateModel(
            name='LessonFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='learning.flashcard')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_links', to='learning.lesson')),
            ],
            options={
                'db_table': 'lesson_flashcards',
                'ordering': ('position', 'flashcard_id'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'flashcard'), name='unique_lesson_flashcard'), models.UniqueConstraint(fields=('lesson', 'position'), name='unique_lesson_flashcard_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_topic_position'),
        ),
        migrations.AlterField(
            model_name="lessoncompletion",
            name="lesson_id",
            field=models.CharField(max_length=80),
        ),
        migrations.RunPython(seed_content_structure, migrations.RunPython.noop),
    ]
