# Generated by Django 5.2.17 on 2026-08-25 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


READING_TEXTS = (
    {
        "id": "poranek-anny",
        "title": "Poranek Anny",
        "description": "Обычное утро Анны в Варшаве",
        "level": "A1",
        "minutes": 4,
        "emoji": "☀️",
        "paragraphs": [
            "Anna mieszka w Warszawie. Codziennie rano wstaje o siódmej i otwiera okno. Dzisiaj jest ciepło i świeci słońce.",
            "Anna robi kawę i przygotowuje śniadanie. Je chleb z serem i słucha radia. Potem bierze plecak i idzie do pracy.",
            "Po drodze spotyka sąsiada. Mówi: Dzień dobry! Sąsiad uśmiecha się i życzy jej miłego dnia.",
        ],
        "glossary": {
            "mieszka": "живёт", "codziennie": "каждый день", "rano": "утром",
            "wstaje": "встаёт", "otwiera": "открывает", "okno": "окно",
            "ciepło": "тепло", "świeci": "светит", "słońce": "солнце",
            "robi": "делает", "przygotowuje": "готовит", "śniadanie": "завтрак",
            "chleb": "хлеб", "serem": "сыром", "słucha": "слушает",
            "potem": "потом", "bierze": "берёт", "plecak": "рюкзак",
            "idzie": "идёт", "pracy": "работа", "drodze": "дорога",
            "spotyka": "встречает", "sąsiada": "соседа", "uśmiecha": "улыбается",
            "życzy": "желает", "miłego": "приятного", "dnia": "дня",
        },
        "position": 0,
    },
    {
        "id": "zakupy-na-targu",
        "title": "Zakupy na targu",
        "description": "Покупаем овощи на городском рынке",
        "level": "A1",
        "minutes": 5,
        "emoji": "🍎",
        "paragraphs": [
            "W sobotę Marek idzie na targ. Chce kupić świeże warzywa i owoce. Na targu jest dużo ludzi i kolorowych stoisk.",
            "Najpierw Marek kupuje pomidory, ogórki i ziemniaki. Pyta sprzedawcę: Ile kosztuje kilogram pomidorów? Cztery złote — odpowiada sprzedawca.",
            "Na końcu wybiera czerwone jabłka. Płaci dwanaście złotych i wraca do domu z pełną torbą.",
        ],
        "glossary": {
            "sobotę": "субботу", "targ": "рынок", "chce": "хочет", "kupić": "купить",
            "świeże": "свежие", "warzywa": "овощи", "owoce": "фрукты",
            "dużo": "много", "ludzi": "людей", "kolorowych": "цветных",
            "stoisk": "прилавков", "najpierw": "сначала", "kupuje": "покупает",
            "pomidory": "помидоры", "ogórki": "огурцы", "ziemniaki": "картофель",
            "pyta": "спрашивает", "sprzedawcę": "продавца", "kosztuje": "стоит",
            "kilogram": "килограмм", "cztery": "четыре", "złote": "злотых",
            "odpowiada": "отвечает", "końcu": "конце", "wybiera": "выбирает",
            "czerwone": "красные", "jabłka": "яблоки", "płaci": "платит",
            "dwanaście": "двенадцать", "wraca": "возвращается", "pełną": "полной", "torbą": "сумкой",
        },
        "position": 1,
    },
)


def seed_reading_texts(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    ReadingText = apps.get_model("learning", "ReadingText")
    topic = apps.get_model("learning", "Topic").objects.filter(id="first-steps").first()
    for data in READING_TEXTS:
        ReadingText.objects.create(topic=topic, **data)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_lesson_kind_topic_lesson_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('word', models.CharField(max_length=160)),
                ('translation', models.CharField(max_length=240)),
                ('context', models.TextField(blank=True)),
                ('source_text_id', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'personal_words',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=240)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('minutes', models.PositiveSmallIntegerField(default=5)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('paragraphs', models.JSONField(default=list)),
                ('glossary', models.JSONField(default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_texts', to='learning.topic')),
            ],
            options={
                'db_table': 'reading_texts',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RunPython(seed_reading_texts, migrations.RunPython.noop),
    ]
