# Generated by Django 5.2.17 on 2026-08-28 08:22

from django.db import migrations


SOURCE = {
    "origin": "original",
    "created_for": "PolskiFlow",
    "verified_at": "2026-08-28",
}

QUESTIONS = (
    (
        "Dokąd Kasia pojechała po pracy?",
        ["Do Krakowa", "Do Wrocławia", "Do parku"],
        1,
        "В первом абзаце прямо сказано: Kasia pojechała pociągiem do Wrocławia.",
    ),
    (
        "Co Kasia i jej koleżanka zrobiły w sobotę?",
        ["Zwiedziły muzeum", "Ugotowały obiad", "Pojechały na rowerach"],
        0,
        "В субботу подруги посетили музей и увидели рыночную площадь.",
    ),
    (
        "Dlaczego Kasia i jej koleżanka dużo spacerowały?",
        ["Bo zgubiły pociąg", "Bo było słonecznie", "Bo muzeum było zamknięte"],
        1,
        "Союз więc связывает причину и результат: было солнечно, поэтому они много гуляли.",
    ),
    (
        "Jak Paweł spędził część weekendu w domu?",
        ["Pracował i sprzątał", "Spał cały dzień", "Ugotował obiad i obejrzał filmy"],
        2,
        "Текст перечисляет два действия Павла дома: приготовил обед и посмотрел два фильма.",
    ),
    (
        "Jak Paweł czuł się w poniedziałek?",
        ["Miał dużo energii", "Był bardzo zmęczony", "Był chory"],
        0,
        "После отдыха Павел в понедельник чувствовал прилив энергии.",
    ),
)


def seed(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    Lesson = apps.get_model("learning", "Lesson")
    Question = apps.get_model("learning", "Question")
    ReadingText = apps.get_model("learning", "ReadingText")

    reading = ReadingText.objects.filter(id="weekend-kasi-i-pawla").first()
    if reading is None:
        return
    lesson, _ = Lesson.objects.update_or_create(
        id="weekend-reading-check",
        defaults={
            "topic_id": "past-weekend",
            "kind": "quiz",
            "title": "Czy rozumiesz tekst?",
            "plan_title": "Понимание текста",
            "subtitle": "5 вопросов · A2",
            "description": "Проверь детали рассказа Каси и Павла",
            "minutes": 5,
            "emoji": "📖",
            "position": 52,
            "is_active": True,
            "source_metadata": SOURCE,
        },
    )
    Question.objects.filter(lesson=lesson).delete()
    for position, (prompt, options, correct, explanation) in enumerate(QUESTIONS):
        Question.objects.create(
            lesson=lesson,
            prompt=prompt,
            options=options,
            correct=correct,
            explanation=explanation,
            position=position,
        )
    metadata = reading.source_metadata if isinstance(reading.source_metadata, dict) else {}
    reading.source_metadata = {
        **metadata,
        "comprehension_lesson_id": lesson.id,
    }
    reading.save(update_fields=("source_metadata",))


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_a2_past_weekend_content'),
    ]

    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
