from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}
CARDS=(("returns-paragon","paragon","чек","Czy ma pani paragon?"),("returns-zwrot","zwrot","возврат","Chcę zrobić zwrot tego produktu."),("returns-reklamacja","reklamacja","претензия; рекламация","Złożyłem reklamację w sklepie."),("returns-wymiana","wymiana","обмен","Proszę o wymianę na inny rozmiar."),("returns-wada","wada","дефект","Buty mają małą wadę."),("returns-rozmiar","rozmiar","размер","Ten rozmiar jest za mały."),("returns-przymierzyc","przymierzyć","примерить","Czy mogę przymierzyć tę kurtkę?"),("returns-kosztowac","kosztować","стоить","Ile kosztuje ten sweter?"),("returns-tanszy","tańszy","дешевле","Ten model jest tańszy od tamtego."),("returns-drozszy","droższy","дороже","Skórzana torba jest droższa."),("returns-lepszy","lepszy","лучше","Drugi materiał jest lepszy."),("returns-gorszy","gorszy","хуже","Ten zamek jest gorszy niż poprzedni."),("returns-oddac","oddać","вернуть","Mogę oddać produkt w ciągu czternastu dni."),("returns-uszkodzony","uszkodzony","повреждённый","Dostałam uszkodzony kubek."),("returns-potwierdzenie","potwierdzenie","подтверждение","Mam potwierdzenie płatności w telefonie."))
GRAMMAR=(("Ten sweter jest ___ niż tamten.",["tańszy","tani od","najtańszy niż"],0,"Сравнительная степень tani — tańszy; с niż: tańszy niż tamten."),("Ta kurtka jest ___ od poprzedniej.",["droższa","droga niż","najdroższy"],0,"Для женского рода: droższa od poprzedniej."),("Poproszę pół kilo ___.",["jabłka","jabłek","jabłkami"],1,"После единицы количества нужен родительный множественного: pół kilo jabłek."),("Это лучший размер.",["To jest lepszy rozmiar.","To jest najlepszy rozmiar.","To jest bardziej dobry rozmiar."],1,"Превосходная степень dobry — najlepszy."),("Potrzebuję dwóch ___.",["paragony","paragonów","paragonami"],1,"После dwóch употребляется родительный множественного: dwóch paragonów."))
QUIZ=(("Что означает reklamacja?",["примерочная","претензия на товар","скидка"],1,"Reklamacja — официальное обращение из-за дефекта товара."),("Ten model jest ___ od starego.",["lepszy","dobry niż","najlepiej"],0,"Сравнительная степень dobry — lepszy."),("Poproszę kilogram ___.",["pomidorów","pomidory","pomidorami"],0,"Количество требует родительного множественного: kilogram pomidorów."),("Как попросить обмен на другой размер?",["Proszę o wymianę na inny rozmiar.","Proszę kosztować paragon.","Oddam rozmiar wadą."],0,"Proszę o wymianę na inny rozmiar — вежливая просьба об обмене."),("Buty są za małe, chcę je ___.",["oddać","kosztować","przymierza paragon"],0,"Oddać — вернуть товар."),("Która torba jest ___?",["najtańsza","bardziej tania od","tani"],0,"Превосходная степень tani — najtańsza."),("Что подтверждает покупку?",["paragon lub potwierdzenie płatności","rozmiar i wada","przymierzalnia"],0,"Чек или подтверждение платежа доказывают покупку."),("Potrzebuję trzech ___.",["koszulki","koszulek","koszulkami"],1,"После trzech: родительный множественного — koszulek."))
CHECK=(("Dlaczego Natalia wróciła do sklepu?",["Kurtka miała uszkodzony zamek","Chciała kupić buty","Zgubiła telefon"],0,"У куртки оказался повреждён замок."),("Czego Natalia nie miała?",["Karty płatniczej","Papierowego paragonu","Kurtki"],1,"Бумажный чек она потеряла."),("Jak potwierdziła zakup?",["Pokazała płatność w aplikacji bankowej","Zadzwoniła do producenta","Przyniosła pudełko"],0,"Она показала банковское подтверждение оплаты."),("Co zaproponował sprzedawca?",["Tylko droższy produkt","Wymianę albo zwrot pieniędzy","Naprawę za miesiąc"],1,"Продавец предложил обмен или возврат денег."),("Co wybrała Natalia?",["Większy rozmiar", "Zwrot pieniędzy", "Tańszy, sprawny model"],2,"Она обменяла куртку на исправную более дешёвую модель."))
READING={"id":"reklamacja-natalii","title":"Reklamacja Natalii","description":"Возврат повреждённой куртки без бумажного чека","level":"A2","minutes":5,"emoji":"🛍️","position":16,"paragraphs":["Natalia kupiła zimową kurtkę podczas wyprzedaży. W domu zauważyła, że zamek jest uszkodzony. Następnego dnia wróciła do sklepu, ale nie mogła znaleźć papierowego paragonu. Miała za to potwierdzenie płatności w aplikacji bankowej.","Sprzedawca sprawdził datę i kwotę zakupu. Powiedział, że Natalia może złożyć reklamację i wybrać wymianę albo zwrot pieniędzy. Natalia przymierzyła drugi egzemplarz, lecz był za duży. Inny model pasował lepiej i był trochę tańszy.","Natalia wybrała tańszy model. Sprzedawca zwrócił jej różnicę ceny na kartę i wysłał nowe potwierdzenie e-mailem. Cała rozmowa trwała kilkanaście minut. Natalia była zadowolona, bo nie musiała wracać do sklepu jeszcze raz."],"glossary":{"wyprzedaży":{"lemma":"wyprzedaż","translation":"распродажа","part_of_speech":"существительное"},"zauważyła":{"lemma":"zauważyć","translation":"заметить","part_of_speech":"глагол"},"uszkodzony":{"lemma":"uszkodzony","translation":"повреждённый","part_of_speech":"прилагательное"},"kwotę":{"lemma":"kwota","translation":"сумма","part_of_speech":"существительное"},"złożyć":{"lemma":"złożyć","translation":"подать","part_of_speech":"глагол"},"wymianę":{"lemma":"wymiana","translation":"обмен","part_of_speech":"существительное"},"egzemplarz":{"lemma":"egzemplarz","translation":"экземпляр","part_of_speech":"существительное"},"pasował":{"lemma":"pasować","translation":"подходить","part_of_speech":"глагол"},"różnicę":{"lemma":"różnica","translation":"разница","part_of_speech":"существительное"},"zwrócił":{"lemma":"zwrócić","translation":"вернуть","part_of_speech":"глагол"}}}

def seed(apps,schema_editor):
    if schema_editor.connection.vendor!="sqlite": return
    Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Flashcard=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Question=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); ReadingText=apps.get_model("learning","ReadingText")
    topic,_=Topic.objects.update_or_create(id="shopping-returns",defaults={"course":Course.objects.get(id="a2-independence"),"title":"Покупки и возврат","description":"Сравниваем товары и решаем проблему с покупкой","emoji":"🛍️","position":4,"is_active":True})
    rows=(("returns-words","words","Zakupy i zwrot","Покупка и возврат","8 карточек · A2","Назови документы, дефект и желаемое решение",7,"🛍️"),("returns-grammar","grammar","Tańszy czy najlepszy?","Сравниваем товары","5 заданий · A2","Используй степени сравнения и формы количества",9,"✏️"),("returns-review","review","Składam reklamację","Обмен товара","7 карточек · A2","Повтори сравнения и фразы возврата",7,"🔄"),("returns-quiz","quiz","Quiz: zakupy i zwrot","Проверка темы","8 вопросов · A2","Проверь лексику и грамматику покупок",6,"🎯"),("returns-reading-check","quiz","Czy rozumiesz reklamację?","Понимание текста","5 вопросов · A2","Проверь детали возврата Наталии",5,"📖"))
    made={}
    for position,row in enumerate(rows,68):
        id_,kind,title,plan,subtitle,description,minutes,emoji=row; made[id_],_=Lesson.objects.update_or_create(id=id_,defaults={"topic":topic,"kind":kind,"title":title,"plan_title":plan,"subtitle":subtitle,"description":description,"minutes":minutes,"emoji":emoji,"position":position,"is_active":True,"source_metadata":SOURCE})
    g=made["returns-grammar"]; g.theory_title="Tańszy, droższy, najlepszy"; g.theory_sections=[["Сравнение","Частые формы: tani → tańszy, drogi → droższy, dobry → lepszy, zły → gorszy."],["С чем сравниваем","Используй niż + именительный или od + родительный: tańszy niż ten; tańszy od tego."],["Количество","После pół kilo, dwóch, trzech нужен родительный: jabłek, paragonów, koszulek."]]; g.save(update_fields=("theory_title","theory_sections"))
    cards=[]
    for position,(id_,polish,translation,example) in enumerate(CARDS,241): card,_=Flashcard.objects.update_or_create(id=id_,defaults={"polish":polish,"translation":translation,"example":example,"position":position,"is_active":True,"source_metadata":SOURCE}); cards.append(card)
    for lesson_id,chosen in (("returns-words",cards[:8]),("returns-review",cards[8:])):
        Link.objects.filter(lesson_id=lesson_id).delete()
        for position,card in enumerate(chosen): Link.objects.create(lesson_id=lesson_id,flashcard=card,position=position)
    for lesson_id,questions in (("returns-grammar",GRAMMAR),("returns-quiz",QUIZ),("returns-reading-check",CHECK)):
        Question.objects.filter(lesson_id=lesson_id).delete()
        for position,(prompt,options,correct,explanation) in enumerate(questions): Question.objects.create(lesson_id=lesson_id,prompt=prompt,options=options,correct=correct,explanation=explanation,position=position)
    ReadingText.objects.update_or_create(id=READING["id"],defaults={**{k:v for k,v in READING.items() if k!="id"},"topic":topic,"source_metadata":{**SOURCE,"comprehension_lesson_id":"returns-reading-check"},"is_active":True})

class Migration(migrations.Migration):
    dependencies=[("learning","0023_a2_work_content")]
    operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
