from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}
CARDS=(("med-objaw","objaw","симптом","Proszę dokładnie opisać objawy."),("med-kaszel","kaszel","кашель","Mam suchy kaszel od trzech dni."),("med-goraczka","gorączka","высокая температура","Wieczorem miałem wysoką gorączkę."),("med-bol-gardla","ból gardła","боль в горле","Ból gardła jest dziś silniejszy."),("med-recepta","recepta","рецепт","Lekarz wystawił receptę elektroniczną."),("med-dawkowanie","dawkowanie","дозировка","Dawkowanie jest napisane na opakowaniu."),("med-tabletka","tabletka","таблетка","Proszę brać jedną tabletkę rano."),("med-syrop","syrop","сироп","Ten syrop pomaga na kaszel."),("med-badanie","badanie","обследование","Lekarz skierował mnie na badanie krwi."),("med-uczulenie","uczulenie","аллергия","Czy ma pan uczulenie na antybiotyki?"),("med-skutek","skutek uboczny","побочный эффект","Senność może być skutkiem ubocznym."),("med-przyjmowac","przyjmować lek","принимать лекарство","Lek trzeba przyjmować po jedzeniu."),("med-pogorszyc","pogorszyć się","ухудшиться","Jeśli stan się pogorszy, proszę zadzwonić."),("med-poprawic","poprawić się","улучшиться","Po dwóch dniach powinno się poprawić."),("med-zwolnienie","zwolnienie lekarskie","больничный лист","Dostałam zwolnienie lekarskie na trzy dni."))
GRAMMAR=(("Przy gorączce ___ dużo pić.",["trzeba","wolno nie","powinienem jest"],0,"Безличное trzeba + инфинитив выражает общую необходимость."),("Pan ___ odpoczywać przez dwa dni.",["powinien","powinna","powinni"],0,"Форма powinien согласуется с pan в мужском роде."),("Kobieta w ciąży ___ skonsultować lek z lekarzem.",["powinna","powinien","powinno"],0,"Для женщины: powinna + инфинитив."),("Здесь нельзя курить.",["Tutaj trzeba palić.","Tutaj nie wolno palić.","Tutaj powinien palić."],1,"Запрет выражает безличное nie wolno + инфинитив."),("Lek ___ przyjmować po jedzeniu.",["należy","należą","należy się go"],0,"В инструкции нейтральная рекомендация: należy + инфинитив."))
QUIZ=(("Что означает dawkowanie?",["диагноз","дозировка","приёмная"],1,"Dawkowanie — количество и частота приёма лекарства."),("Przy bólu gardła ___ pić ciepłe napoje.",["warto","nie wolno zawsze","powinien są"],0,"Warto + инфинитив даёт мягкую рекомендацию."),("Dziecko ___ zostać w domu.",["powinno","powinien","powinna"],0,"Dziecko — средний род: powinno."),("Как сообщить об аллергии?",["Mam uczulenie na penicylinę.","Biorę receptę gorączką.","Objaw należy apteka."],0,"Mam uczulenie na… — стандартная фраза об аллергии."),("Antybiotyku nie wolno ___ bez konsultacji.",["odstawiać","odstawiał","odstawienie"],0,"После nie wolno нужен инфинитив: odstawiać."),("Если состояние ухудшится…",["Jeśli stan się pogorszy…","Kiedy recepta dawkowanie…","Gdy lek powinien był…"],0,"Pogorszyć się — ухудшиться; jeśli вводит реальное условие."),("Что может вызвать сонливость?",["skutek uboczny leku","zwolnienie lekarskie","badanie gardła"],0,"Сонливость может быть побочным эффектом лекарства."),("Lek ___ dwa razy dziennie.",["należy przyjmować","należy przyjmował","powinno przyjmują"],0,"Безличная инструкция: należy przyjmować."))
CHECK=(("Jak długo Adam miał objawy?",["Od jednego wieczoru","Od trzech dni","Od dwóch tygodni"],1,"Кашель и слабость продолжались три дня."),("Dlaczego lekarz nie przepisał od razu antybiotyku?",["Objawy wskazywały na infekcję wirusową","Adam nie miał dokumentów","Apteka była zamknięta"],0,"Врач счёл инфекцию вирусной, поэтому антибиотик не требовался."),("Co lekarz zalecił Adamowi?",["Dużo odpoczynku i picia","Intensywny trening","Pracę w nocy"],0,"Рекомендации: отдых, жидкость и средство от температуры."),("O co farmaceutka zapytała Adama?",["O uczulenia i inne leki","O miejsce pracy","O rozmiar ubrania"],0,"Фармацевт уточнила аллергию и другие лекарства."),("Kiedy Adam ma ponownie skontaktować się z lekarzem?",["Gdy stan się pogorszy lub gorączka nie minie","Po każdej tabletce","Dopiero za rok"],0,"Повторная консультация нужна при ухудшении или сохраняющейся температуре."))
READING={"id":"adam-u-lekarza-i-w-aptece","title":"Adam u lekarza i w aptece","description":"Консультация, рекомендации и безопасный приём лекарства","level":"A2","minutes":6,"emoji":"💊","position":17,"paragraphs":["Adam od trzech dni miał suchy kaszel, ból gardła i osłabienie. Wieczorem temperatura wzrosła do trzydziestu ośmiu stopni, dlatego rano umówił wizytę u lekarza. Podczas konsultacji dokładnie opisał objawy i powiedział, że nie ma uczulenia na leki.","Lekarz zbadał gardło i płuca. Wyjaśnił, że prawdopodobnie jest to infekcja wirusowa, więc antybiotyk nie jest potrzebny. Adam powinien odpoczywać, dużo pić i przyjmować lek przeciwgorączkowy tylko zgodnie z dawkowaniem. Dostał też zwolnienie lekarskie na trzy dni.","W aptece farmaceutka sprawdziła receptę i zapytała, czy Adam przyjmuje inne leki. Wyjaśniła, że tabletki należy brać po jedzeniu i nie wolno przekraczać zalecanej dawki. Jeśli stan Adama się pogorszy albo gorączka nie minie, powinien ponownie skontaktować się z lekarzem."],"glossary":{"osłabienie":{"lemma":"osłabienie","translation":"слабость","part_of_speech":"существительное"},"wzrosła":{"lemma":"wzrosnąć","translation":"повыситься","part_of_speech":"глагол"},"umówił":{"lemma":"umówić","translation":"назначить; договориться","part_of_speech":"глагол"},"zbadał":{"lemma":"zbadać","translation":"осмотреть","part_of_speech":"глагол"},"płuca":{"lemma":"płuco","translation":"лёгкие","part_of_speech":"существительное"},"wirusowa":{"lemma":"wirusowy","translation":"вирусный","part_of_speech":"прилагательное"},"przeciwgorączkowy":{"lemma":"przeciwgorączkowy","translation":"жаропонижающий","part_of_speech":"прилагательное"},"dawkowaniem":{"lemma":"dawkowanie","translation":"дозировка","part_of_speech":"существительное"},"przekraczać":{"lemma":"przekraczać","translation":"превышать","part_of_speech":"глагол"},"zalecanej":{"lemma":"zalecany","translation":"рекомендованный","part_of_speech":"прилагательное"},"pogorszy":{"lemma":"pogorszyć się","translation":"ухудшиться","part_of_speech":"глагол"}}}

def seed(apps,schema_editor):
    if schema_editor.connection.vendor!="sqlite": return
    Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Flashcard=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Question=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); ReadingText=apps.get_model("learning","ReadingText")
    topic,_=Topic.objects.update_or_create(id="doctor-pharmacy",defaults={"course":Course.objects.get(id="a2-independence"),"title":"Врач и аптека","description":"Описываем симптомы и понимаем рекомендации по лечению","emoji":"💊","position":5,"is_active":True})
    rows=(("med-words","words","U lekarza","Симптомы и консультация","8 карточек · A2","Опиши состояние и пойми основные вопросы",8,"🩺"),("med-grammar","grammar","Trzeba czy powinien?","Рекомендации и запреты","5 заданий · A2","Используй trzeba, należy, powinien и nie wolno",9,"✏️"),("med-review","review","W aptece","Безопасный приём лекарств","7 карточек · A2","Повтори дозировку и важные предупреждения",7,"🔄"),("med-quiz","quiz","Quiz: lekarz i apteka","Проверка темы","8 вопросов · A2","Проверь лексику и конструкции рекомендации",6,"🎯"),("med-reading-check","quiz","Czy rozumiesz zalecenia?","Понимание текста","5 вопросов · A2","Проверь детали консультации Адама",5,"📖"))
    made={}
    for position,row in enumerate(rows,73):
        id_,kind,title,plan,subtitle,description,minutes,emoji=row; made[id_],_=Lesson.objects.update_or_create(id=id_,defaults={"topic":topic,"kind":kind,"title":title,"plan_title":plan,"subtitle":subtitle,"description":description,"minutes":minutes,"emoji":emoji,"position":position,"is_active":True,"source_metadata":SOURCE})
    g=made["med-grammar"]; g.theory_title="Trzeba, należy, powinien, nie wolno"; g.theory_sections=[["Общая необходимость","Trzeba + инфинитив: trzeba odpoczywać."],["Рекомендация","Powinien/powinna/powinno согласуется с человеком; официальное należy остаётся безличным."],["Запрет","Nie wolno + инфинитив: nie wolno przekraczać dawki."]]; g.save(update_fields=("theory_title","theory_sections"))
    cards=[]
    for position,(id_,polish,translation,example) in enumerate(CARDS,256): card,_=Flashcard.objects.update_or_create(id=id_,defaults={"polish":polish,"translation":translation,"example":example,"position":position,"is_active":True,"source_metadata":SOURCE}); cards.append(card)
    for lesson_id,chosen in (("med-words",cards[:8]),("med-review",cards[8:])):
        Link.objects.filter(lesson_id=lesson_id).delete()
        for position,card in enumerate(chosen): Link.objects.create(lesson_id=lesson_id,flashcard=card,position=position)
    for lesson_id,questions in (("med-grammar",GRAMMAR),("med-quiz",QUIZ),("med-reading-check",CHECK)):
        Question.objects.filter(lesson_id=lesson_id).delete()
        for position,(prompt,options,correct,explanation) in enumerate(questions): Question.objects.create(lesson_id=lesson_id,prompt=prompt,options=options,correct=correct,explanation=explanation,position=position)
    ReadingText.objects.update_or_create(id=READING["id"],defaults={**{k:v for k,v in READING.items() if k!="id"},"topic":topic,"source_metadata":{**SOURCE,"comprehension_lesson_id":"med-reading-check"},"is_active":True})

class Migration(migrations.Migration):
    dependencies=[("learning","0024_a2_shopping_returns_content")]
    operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
