from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}
CARDS=(
("b1trip-przesiadka","przesiadka","пересадка","Na przesiadkę mamy tylko dwanaście minut."),("b1trip-opoznienie","opóźnienie","задержка","Pociąg ma czterdzieści minut opóźnienia."),("b1trip-polaczenie","połączenie","сообщение; рейс","Czy jest inne połączenie do Pragi?"),("b1trip-peron","peron","платформа","Pociąg odjedzie z trzeciego peronu."),("b1trip-odwolany","odwołany","отменённый","Nasz lot został odwołany z powodu burzy."),("b1trip-zglosic","zgłosić problem","сообщить о проблеме","Zgłosiliśmy problem pracownikowi informacji."),("b1trip-zastepczy","zastępczy","заменяющий","Przewoźnik zapewnił autobus zastępczy."),("b1trip-zwrot","zwrot kosztów","возврат расходов","Poprosiła o zwrot kosztów biletu."),("b1trip-dojechac","dojechać","доехать","Mimo opóźnienia dojechaliśmy przed północą."),("b1trip-wyjechac","wyjechać","уехать; выехать","Wyjechaliśmy z domu bardzo wcześnie."),("b1trip-przyjechac","przyjechać","приехать","Autobus przyjechał na czas."),("b1trip-przejechac","przejechać","проехать","W jeden dzień przejechaliśmy pięćset kilometrów."),("b1trip-ominac","ominąć","обойти; миновать","Kierowca ominął korek lokalną drogą."),("b1trip-utknac","utknąć","застрять","Utknęliśmy na lotnisku na kilka godzin."),("b1trip-wrazenie","niezapomniane wrażenie","незабываемое впечатление","Widok z pociągu zrobił na mnie niezapomniane wrażenie."),)
GRAMMAR=(("Musimy ___ do Krakowa przed osiemnastą.",["dojechać","wyjechać z","przejeżdżać od"],0,"Dojechać обозначает достижение пункта назначения."),("Pociąg ___ z Warszawy o 7:10 i ___ do Gdańska o 10:05.",["wyjeżdża; przyjeżdża","dojeżdża; wyjeżdża","przejeżdża; odjeżdża z"],0,"Wyjeżdża z называет исходную точку, przyjeżdża do — конечную."),("Wczoraj ___ przez Łódź, ale nie zatrzymywaliśmy się tam.",["przejechaliśmy","dojechaliśmy do","wyjechaliśmy z"],0,"Przejechać przez — проехать через место."),("Составьте: Из-за задержки мы не успели на пересадку.",["Z powodu opóźnienia nie zdążyliśmy na przesiadkę.","Dzięki opóźnieniu nie zdążamy do przesiadki.","Opóźnienie przez przesiadkę nie przyjechało."],0,"Z powodu вводит причину, zdążyć na требует винительного падежа."),("Gdy lot odwołano, pasażerowie ___ na lotnisku.",["utknęli","ominęli","dojechali"],0,"Utknąć означает оказаться без возможности продолжить путь."),("Составьте: Сотрудник предложил нам другой рейс.",["Pracownik zaproponował nam inne połączenie.","Pracownik zaproponował nas innym połączeniem.","Inne połączenie proponuje do pracownika."],0,"Zaproponować komu? требует дательного: nam; co? — винительного: połączenie."),)
QUIZ=(("Что означает przesiadka?",["пересадка","платформа","багаж"],0,"Przesiadka — смена транспорта по пути."),("Lot został ___ z powodu złej pogody.",["odwołany","przejechany","ominięty do"],0,"Odwołany lot не состоится."),("Как попросить возврат расходов?",["Proszę o zwrot kosztów.","Proszę przejechać koszt.","Zwrot jedzie do mnie."],0,"Prosić o zwrot kosztów — стандартная просьба о возмещении."),("Autobus zastępczy ___ pasażerów do następnej stacji.",["zawiózł","wyjechał pasażerów","utknął do"],0,"Zawieźć kogoś do места — доставить кого-либо."),("Który czasownik podkreśla osiągnięcie celu?",["dojechać","jechać","przejeżdżać"],0,"Приставка do- подчёркивает достижение конечной точки."),("Pociąg odjedzie z ___.",["peronu","połączenia","opóźnieniem do"],0,"Поезд отправляется с платформы: z peronu."),("Co robisz, gdy biletomat nie działa?",["Zgłaszam problem pracownikowi.","Odwołuję peron.","Przejeżdżam informację."],0,"Zgłosić problem — сообщить сотруднику о неисправности."),("Kierowca ___ zamkniętą drogę.",["ominął","utknął ją do","dojechał przez ją"],0,"Ominąć — выбрать путь в обход препятствия."),("Как связать проблему и решение?",["Z powodu opóźnienia spóźniliśmy się, dlatego wybraliśmy inny pociąg.","Dzięki problemowi, chociaż dlatego pociąg.","Opóźnienie albo rozwiązanie że."],0,"Z powodu вводит причину, dlatego — следствие и решение."),("Podróż zrobiła na mnie duże ___.",["wrażenie","połączenie","opóźnienie"],0,"Zrobić wrażenie — произвести впечатление."),)
CHECK=(("Dokąd jechali Marta i Paweł?",["Do Pragi","Do Wiednia","Do Gdańska"],0,"Они ехали поездом в Прагу."),("Gdzie pojawił się pierwszy problem?",["W Katowicach","W Krakowie","W Pradze"],0,"В Катовице объявили о большой задержке."),("Dlaczego mogli stracić połączenie?",["Mieli krótką przesiadkę","Zgubili paszporty","Kupili zły bilet"],0,"Из-за задержки они могли не успеть на короткую пересадку."),("Jak pomogła pracownica informacji?",["Znalazła inne połączenie przez Ostrawę","Oddała im samochód","Odwołała wszystkie pociągi"],0,"Сотрудница предложила альтернативный маршрут через Остраву."),("Co zrobili podczas dodatkowego czasu?",["Krótko zwiedzili centrum Ostrawy","Wrócili do Warszawy","Czekali cały dzień na peronie"],0,"Они использовали паузу для короткой прогулки."),("Jaki jest główny wniosek Marty?",["Problem w podróży może zmienić się w ciekawe doświadczenie","Nie warto pytać o inne połączenie","Każde opóźnienie kończy podróż"],0,"Марта оценила неожиданное изменение как полезный опыт."),)
READING={"id":"b1trip-nieplanowana-przesiadka","title":"Nieplanowana przesiadka","description":"Задержка, альтернативный маршрут и неожиданные впечатления","level":"B1","minutes":8,"emoji":"🚆","position":25,"paragraphs":["Marta i Paweł wyjechali rano z Warszawy do Pragi. Mieli przesiadkę w Katowicach, a cały plan wydawał się prosty. Jednak przed Katowicami pociąg zatrzymał się na trasie. Po kilkunastu minutach konduktor poinformował pasażerów o poważnym opóźnieniu.","Na przesiadkę mieli tylko dwadzieścia minut, więc istniało ryzyko, że nie zdążą na kolejne połączenie. Po przyjeździe szybko poszli do punktu informacji. Pracownica sprawdziła bilety i zaproponowała im inną trasę przez Ostrawę. Nowe połączenie odjeżdżało z sąsiedniego peronu.","Podróżni dojechali do Ostrawy bez problemu, lecz na pociąg do Pragi musieli czekać prawie dwie godziny. Zamiast siedzieć na dworcu, zostawili bagaż w przechowalni i poszli na krótki spacer po centrum. Obejrzeli rynek i zjedli obiad w małej restauracji.","Do Pragi przyjechali późnym wieczorem. Podróż trwała znacznie dłużej, niż planowali, ale Marta nie uważała jej za nieudaną. Stwierdziła, że dzięki spokojnej rozmowie i szybkiemu znalezieniu innego połączenia problem zmienił się w niezapomniane doświadczenie."],"glossary":{"wydawał":{"lemma":"wydawać się","translation":"казаться","part_of_speech":"глагол"},"trasie":{"lemma":"trasa","translation":"маршрут","part_of_speech":"существительное"},"konduktor":{"lemma":"konduktor","translation":"проводник; контролёр","part_of_speech":"существительное"},"poważnym":{"lemma":"poważny","translation":"серьёзный","part_of_speech":"прилагательное"},"ryzyko":{"lemma":"ryzyko","translation":"риск","part_of_speech":"существительное"},"zdążą":{"lemma":"zdążyć","translation":"успеть","part_of_speech":"глагол"},"sąsiedniego":{"lemma":"sąsiedni","translation":"соседний","part_of_speech":"прилагательное"},"przechowalni":{"lemma":"przechowalnia","translation":"камера хранения","part_of_speech":"существительное"},"znacznie":{"lemma":"znacznie","translation":"значительно","part_of_speech":"наречие"},"nieudaną":{"lemma":"nieudany","translation":"неудачный","part_of_speech":"прилагательное"},"stwierdziła":{"lemma":"stwierdzić","translation":"заключить; отметить","part_of_speech":"глагол"},"doświadczenie":{"lemma":"doświadczenie","translation":"опыт","part_of_speech":"существительное"}}}
def seed(apps,schema_editor):
    if schema_editor.connection.vendor!="sqlite": return
    Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Flashcard=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Question=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); ReadingText=apps.get_model("learning","ReadingText")
    topic,_=Topic.objects.update_or_create(id="b1-travel",defaults={"course":Course.objects.get(id="b1-independent"),"title":"Путешествия","description":"Решаем проблему в дороге и связно описываем впечатления","emoji":"🚆","position":1,"is_active":True})
    rows=(("b1trip-words","words","Gdy podróż nie idzie zgodnie z planem","Проблемы в пути","8 карточек · B1","Объясни задержку и попроси решение",9,"🚆"),("b1trip-grammar","grammar","Dokąd, skąd i którędy?","Глаголы движения","6 заданий · B1","Различай направление, достижение и маршрут",12,"✏️"),("b1trip-review","review","Mimo trudności","Маршрут и впечатления","7 карточек · B1","Расскажи, как изменился путь",8,"🔄"),("b1trip-quiz","quiz","Quiz: podróż","Проверка темы","10 вопросов · B1","Проверь лексику, управление и связность",9,"🎯"),("b1trip-reading-check","quiz","Czy rozumiesz podróż?","Понимание текста","6 вопросов · B1","Найди проблему, решение и вывод",7,"📖")); made={}
    for position,row in enumerate(rows,113): id_,kind,title,plan,subtitle,description,minutes,emoji=row; made[id_],_=Lesson.objects.update_or_create(id=id_,defaults={"topic":topic,"kind":kind,"title":title,"plan_title":plan,"subtitle":subtitle,"description":description,"minutes":minutes,"emoji":emoji,"position":position,"is_active":True,"source_metadata":SOURCE})
    grammar=made["b1trip-grammar"]; grammar.theory_title="Приставки движения и точка маршрута"; grammar.theory_sections=[["Начало и конец","Wyjechać z показывает отправление, przyjechać/dojechać do — прибытие и достижение цели."],["Путь","Przejechać przez называет место по пути, ominąć — движение в обход."],["Причина и решение","Z powodu вводит причину проблемы, dlatego связывает её с решением."]]; grammar.save(update_fields=("theory_title","theory_sections")); cards=[]
    for position,(id_,polish,translation,example) in enumerate(CARDS,377): card,_=Flashcard.objects.update_or_create(id=id_,defaults={"polish":polish,"translation":translation,"example":example,"position":position,"is_active":True,"source_metadata":SOURCE}); cards.append(card)
    for lesson_id,chosen in (("b1trip-words",cards[:8]),("b1trip-review",cards[8:])): Link.objects.filter(lesson_id=lesson_id).delete(); [Link.objects.create(lesson_id=lesson_id,flashcard=card,position=position) for position,card in enumerate(chosen)]
    for lesson_id,questions in (("b1trip-grammar",GRAMMAR),("b1trip-quiz",QUIZ),("b1trip-reading-check",CHECK)): Question.objects.filter(lesson_id=lesson_id).delete(); [Question.objects.create(lesson_id=lesson_id,prompt=q[0],options=q[1],correct=q[2],explanation=q[3],position=position) for position,q in enumerate(questions)]
    ReadingText.objects.update_or_create(id=READING["id"],defaults={**{k:v for k,v in READING.items() if k!="id"},"topic":topic,"source_metadata":{**SOURCE,"comprehension_lesson_id":"b1trip-reading-check"},"is_active":True})
class Migration(migrations.Migration):
    dependencies=[("learning","0032_b1_biography_experience_content")]; operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
