from django.db import migrations


SOURCE = {"origin": "original", "created_for": "PolskiFlow", "verified_at": "2026-08-30"}


TOPICS = (
    {
        "id": "b1-society", "title": "Общество", "description": "Обсуждаем знакомую общественную тему и аргументируем мнение", "emoji": "🤝", "position": 8,
        "prefix": "b1soc", "lesson_start": 148, "card_start": 482,
        "theory": ("Аргумент и уступка", [["Причина", "Ponieważ вводит причину, а więc — логическое следствие."], ["Уступка", "Chociaż показывает контраст между ожидаемым и реальным."], ["Позиция", "Начни с moim zdaniem, добавь причину и конкретный пример."]]),
        "cards": (
            ("społeczność", "сообщество", "Lokalna społeczność zorganizowała spotkanie."), ("mieszkaniec", "житель", "Każdy mieszkaniec mógł zabrać głos."), ("wolontariat", "волонтёрство", "Wolontariat pomaga poznać sąsiadów."), ("inicjatywa", "инициатива", "Poparliśmy inicjatywę młodzieży."), ("potrzeba", "потребность", "Projekt odpowiada na potrzeby mieszkańców."), ("dostępny", "доступный", "Transport powinien być dostępny dla wszystkich."), ("wspierać", "поддерживать", "Miasto wspiera lokalne organizacje."), ("uczestniczyć", "участвовать", "Warto uczestniczyć w konsultacjach."),
            ("odpowiedzialność", "ответственность", "Wspólna przestrzeń to nasza odpowiedzialność."), ("rozwiązanie", "решение", "Szukamy praktycznego rozwiązania."), ("korzyść", "польза", "Zmiana przyniesie korzyść całej dzielnicy."), ("wada", "недостаток", "Każde rozwiązanie ma także wady."), ("opinia", "мнение", "Szanuję twoją opinię."), ("przekonać", "убедить", "Ten przykład może przekonać niezdecydowanych."), ("dojść do porozumienia", "договориться", "Po dyskusji doszliśmy do porozumienia."),
        ),
        "grammar": (
            ("Popieram projekt, ___ ułatwi życie starszym mieszkańcom.", ["ponieważ", "chociaż", "więc"], 0, "Ponieważ вводит причину поддержки."), ("Pomysł jest kosztowny, ___ może przynieść długoterminowe korzyści.", ["chociaż", "ponieważ", "dlatego"], 0, "Chociaż выражает уступку."), ("Brakuje bezpiecznych przejść, ___ mieszkańcy proszą o zmiany.", ["więc", "mimo że", "ponieważ"], 0, "Więc вводит следствие."), ("Moim zdaniem warto działać, ___ mały krok też ma znaczenie.", ["ponieważ", "więc", "chociaż"], 0, "Здесь требуется обоснование позиции."), ("Составьте: Хотя мнения различаются, мы можем найти решение.", ["Chociaż opinie są różne, możemy znaleźć rozwiązanie.", "Ponieważ opinie różne, więc rozwiązanie.", "Opinie chociaż są, znaleźć rozwiązaniem."], 0, "Chociaż открывает придаточное уступки."), ("Составьте: Району нужен парк, поэтому я поддерживаю инициативу.", ["Dzielnica potrzebuje parku, więc popieram inicjatywę.", "Dzielnica potrzebuje park, ponieważ popieram inicjatywą.", "Chociaż park potrzebuje, popieram."], 0, "Więc логично соединяет проблему и позицию."),
        ),
        "quiz": (
            ("Что означает społeczność lokalna?", ["местное сообщество", "городской транспорт", "частное мнение"], 0, "Это люди, объединённые местом и общими делами."), ("Warto ___ w konsultacjach społecznych.", ["uczestniczyć", "przekonywać się", "wynikać"], 0, "Uczestniczyć w — участвовать в."), ("Projekt ma zalety, ___ wymaga dużego budżetu.", ["chociaż", "więc", "ponieważ"], 0, "Нужна уступка."), ("Brakuje zieleni, ___ proponujemy nowy park.", ["więc", "mimo że", "chociaż"], 0, "Предложение является следствием."), ("Как вежливо начать мнение?", ["Moim zdaniem…", "To oczywiste dla każdego…", "Nie masz racji."], 0, "Moim zdaniem нейтрально обозначает позицию."), ("Które połączenie jest naturalne?", ["dojść do porozumienia", "zrobić społeczność", "uczestniczyć opinię"], 0, "Устойчивое выражение — dojść do porozumienia."), ("Inicjatywa przyniesie ___ mieszkańcom.", ["korzyści", "wadywać", "odpowiedzialni"], 0, "Przynosić korzyści — приносить пользу."), ("Что усиливает аргумент?", ["конкретный пример", "повтор одного мнения", "нападение на собеседника"], 0, "Пример показывает практическое основание."), ("Szanuję twoją ___, ale widzę problem inaczej.", ["opinię", "potrzebą", "rozwiązaniem"], 0, "Szanuję kogo/co требует винительного падежа."), ("Które zdanie zawiera argument?", ["Popieram zmianę, ponieważ zwiększy bezpieczeństwo.", "Zmiana, zmiana, zmiana.", "Każdy musi się zgodzić."], 0, "Есть позиция и причина."),
        ),
        "reading": {
            "id": "b1soc-sasiedzki-ogrod", "title": "Ogród, który połączył sąsiadów", "description": "Как общественная инициатива привела к компромиссу", "emoji": "🤝", "minutes": 8,
            "paragraphs": ["Na osiedlu Mai stał pusty plac, którego od lat nikt nie wykorzystywał. Część mieszkańców chciała parkingu, ponieważ wieczorami brakowało miejsc. Inni proponowali ogród społeczny dostępny dla dzieci i seniorów.", "Rada dzielnicy zaprosiła mieszkańców na konsultacje. Chociaż opinie były bardzo różne, każdy mógł przedstawić potrzeby i wady obu pomysłów. Maja uczestniczyła w spotkaniu jako wolontariuszka i zapisywała najważniejsze argumenty.", "Po długiej rozmowie pojawiło się rozwiązanie: połowę placu przeznaczono na mały parking, a resztę na ogród. Miasto obiecało wspierać inicjatywę, więc społeczność przygotowała plan prac i podzieliła odpowiedzialność.", "Pierwszej wiosny sąsiedzi wspólnie posadzili rośliny. Projekt nie spełnił wszystkich oczekiwań, ale przyniósł wyraźne korzyści i pomógł ludziom dojść do porozumienia. Maja przekonała się, że kompromis wymaga słuchania, konkretnych przykładów i cierpliwości."],
            "glossary": {"osiedlu": ("osiedle", "жилой район", "существительное"), "plac": ("plac", "площадка", "существительное"), "wykorzystywał": ("wykorzystywać", "использовать", "глагол"), "brakowało": ("brakować", "не хватать", "глагол"), "dostępny": ("dostępny", "доступный", "прилагательное"), "konsultacje": ("konsultacja", "общественные обсуждения", "существительное"), "wady": ("wada", "недостаток", "существительное"), "wolontariuszka": ("wolontariuszka", "волонтёрка", "существительное"), "przeznaczono": ("przeznaczyć", "выделить", "глагол"), "resztę": ("reszta", "остаток", "существительное"), "podzieliła": ("podzielić", "разделить", "глагол"), "posadzili": ("posadzić", "посадить", "глагол"), "oczekiwań": ("oczekiwanie", "ожидание", "существительное"), "cierpliwości": ("cierpliwość", "терпение", "существительное")},
            "check": (("Co znajdowało się na osiedlu?", ["Niewykorzystany plac", "Nowa szkoła", "Duży dworzec"], 0, "На районе была пустующая площадка."), ("Jakie były dwie propozycje?", ["Parking i ogród społeczny", "Basen i kino", "Sklep i urząd"], 0, "Спор касался парковки и сада."), ("Jaką rolę miała Maja?", ["Zapisywała argumenty jako wolontariuszka", "Projektowała parking", "Prowadziła sklep"], 0, "Она фиксировала аргументы."), ("Na czym polegał kompromis?", ["Plac podzielono między parking i ogród", "Zrezygnowano z obu planów", "Zbudowano tylko parking"], 0, "Пространство разделили."), ("Co dał wspólny projekt?", ["Korzyści i lepsze porozumienie", "Więcej konfliktów", "Brak dostępu do placu"], 0, "Он объединил соседей."), ("Jaki jest wniosek?", ["Kompromis wymaga słuchania i konkretów", "Najgłośniejsza osoba zawsze wygrywa", "Konsultacje nie mają sensu"], 0, "Вывод прямо дан в конце.")),
        },
    },
    {
        "id": "b1-ecology", "title": "Природа и экология", "description": "Объясняем причины, последствия и реалистичные экологические решения", "emoji": "🌱", "position": 9,
        "prefix": "b1eco", "lesson_start": 153, "card_start": 497,
        "theory": ("Причина, следствие и решение", [["Причина", "Z powodu + родительный и ponieważ называют причину."], ["Следствие", "Dlatego, wskutek tego и prowadzić do показывают результат."], ["Решение", "Żeby + прошедшая форма выражает цель действия."]]),
        "cards": (("środowisko", "окружающая среда", "Dbamy o środowisko w naszej gminie."), ("zanieczyszczenie", "загрязнение", "Zanieczyszczenie powietrza spadło."), ("odpady", "отходы", "Segregujemy odpady w domu."), ("susza", "засуха", "Długa susza niszczy rośliny."), ("powódź", "наводнение", "Po ulewie groziła nam powódź."), ("gatunek", "вид", "Ten gatunek ptaka potrzebuje ochrony."), ("chronić", "защищать", "Musimy chronić lokalny las."), ("ograniczyć", "ограничить", "Chcemy ograniczyć zużycie plastiku."), ("zużycie", "потребление", "Zużycie wody latem rośnie."), ("odnawialny", "возобновляемый", "Energia odnawialna zmniejsza emisje."), ("emisja", "выброс", "Transport odpowiada za część emisji."), ("ponownie wykorzystać", "использовать повторно", "Słoik można ponownie wykorzystać."), ("oszczędzać", "экономить", "Oszczędzamy wodę i energię."), ("skutek", "последствие", "Skutki suszy odczuli rolnicy."), ("rozwiązanie", "решение", "Potrzebujemy trwałego rozwiązania.")),
        "grammar": (("Z powodu długiej suszy ___ poziom rzeki.", ["obniżył się", "ochronił", "wykorzystał"], 0, "Z powodu называет причину снижения."), ("Padało przez wiele godzin, ___ część ulic została zalana.", ["dlatego", "chociaż", "żeby"], 0, "Dlatego вводит следствие."), ("Nadmierne zużycie plastiku prowadzi ___ większej ilości odpadów.", ["do", "dla", "nad"], 0, "Prowadzić do требует родительного падежа."), ("Mieszkańcy zbierają deszczówkę, ___ oszczędzać wodę.", ["żeby", "ponieważ", "wskutek"], 0, "Żeby + инфинитив выражает цель при одном субъекте."), ("Составьте: Из-за загрязнения город ограничил движение автомобилей.", ["Z powodu zanieczyszczenia miasto ograniczyło ruch samochodów.", "Dlatego zanieczyszczenie ograniczył miastem ruch.", "Żeby zanieczyszczenia miasto ruch ogranicza."], 0, "Z powodu требует родительного падежа."), ("Составьте: Мы повторно используем вещи, чтобы уменьшить количество отходов.", ["Ponownie wykorzystujemy rzeczy, żeby ograniczyć ilość odpadów.", "Odpady prowadzą rzeczy ponownie wykorzystać.", "Ponieważ wykorzystać rzeczy, dlatego odpady."], 0, "Żeby корректно вводит цель.")),
        "quiz": (("Что означает odpady?", ["отходы", "осадки", "растения"], 0, "Odpady — ненужные материалы и мусор."), ("Długa ___ spowodowała brak wody.", ["susza", "emisja", "powódź"], 0, "Susza — длительный период без дождя."), ("Które źródło energii jest odnawialne?", ["wiatr", "węgiel", "benzyna"], 0, "Ветер восстанавливается естественным образом."), ("Zanieczyszczenie prowadzi ___ problemów zdrowotnych.", ["do", "na", "przy"], 0, "Управление prowadzić do."), ("Jak ograniczyć odpady?", ["Ponownie wykorzystywać rzeczy", "Kupować więcej opakowań", "Wyrzucać szkło do lasu"], 0, "Повторное использование уменьшает отходы."), ("Padało intensywnie, ___ rzeka wystąpiła z brzegów.", ["dlatego", "żeby", "chociaż"], 0, "Нужно следствие."), ("Что называет skutek?", ["последствие", "причину", "вид животного"], 0, "Skutek — результат причины."), ("Oszczędzamy wodę, ___ chronić jej zasoby.", ["żeby", "z powodu", "mimo"], 0, "Żeby вводит цель."), ("Выберите естественное сочетание.", ["ograniczyć emisję", "chronić zużyciem", "odnawiać suszę"], 0, "Ograniczyć emisję — сократить выбросы."), ("Które zdanie pokazuje przyczynę i skutek?", ["Z powodu suszy zużywamy mniej wody.", "Woda jest wodą.", "Las, ale miasto."], 0, "Конструкция ясно называет оба элемента.")),
        "reading": {"id": "b1eco-rzeka-wraca-do-miasta", "title": "Rzeka wraca do miasta", "description": "Как жители нашли решение экологической проблемы", "emoji": "🌱", "minutes": 9, "paragraphs": ["Przez wiele lat mała rzeka w mieście była ukryta w betonowym kanale. Z powodu zanieczyszczenia i braku roślin prawie nie żyły w niej ryby ani owady. Podczas intensywnych opadów woda szybko spływała do centrum i zwiększała ryzyko powodzi.", "Samorząd zaproponował przywrócenie naturalnych brzegów. Chociaż inwestycja była kosztowna, naukowcy wyjaśnili, że beton prowadzi do szybszego przepływu, natomiast rośliny zatrzymują część wody i tworzą miejsce dla różnych gatunków.", "Mieszkańcy poparli projekt, ale poprosili o ścieżkę i ławki. Żeby chronić najcenniejszy fragment, trasę poprowadzono dalej od gniazd ptaków. Wykorzystano też stare kamienie ponownie, dzięki czemu ograniczono ilość odpadów.", "Po dwóch latach jakość wody się poprawiła, a nad rzeką pojawiły się nowe gatunki. Park nie rozwiązał całego problemu zmian klimatu, jednak zmniejszył skutki upałów i ulew. Projekt pokazał, że trwałe rozwiązanie może łączyć ochronę środowiska z potrzebami ludzi."], "glossary": {"ukryta": ("ukryć", "скрытая", "причастие"), "kanale": ("kanał", "канал", "существительное"), "owady": ("owad", "насекомое", "существительное"), "opadów": ("opad", "осадки", "существительное"), "spływała": ("spływać", "стекать", "глагол"), "przywrócenie": ("przywrócenie", "восстановление", "существительное"), "brzegów": ("brzeg", "берег", "существительное"), "przepływu": ("przepływ", "течение", "существительное"), "zatrzymują": ("zatrzymywać", "удерживать", "глагол"), "najcenniejszy": ("cenny", "самый ценный", "прилагательное"), "gniazd": ("gniazdo", "гнездо", "существительное"), "ograniczono": ("ograniczyć", "ограничить", "глагол"), "upałów": ("upał", "жара", "существительное"), "ulew": ("ulewa", "ливень", "существительное")}, "check": (("Gdzie wcześniej płynęła rzeka?", ["W betonowym kanale", "Przez naturalny las", "Pod szkołą"], 0, "Река была заключена в бетонный канал."), ("Jaki problem pojawiał się podczas opadów?", ["Rosło ryzyko powodzi", "Brakowało energii", "Znikały drogi"], 0, "Вода быстро стекала в центр."), ("Dlaczego potrzebne były rośliny?", ["Zatrzymują wodę i wspierają gatunki", "Produkują beton", "Zwiększają emisję"], 0, "Они замедляют воду и создают среду."), ("Jak ochroniono ptaki?", ["Odsunięto ścieżkę od gniazd", "Usunięto wszystkie drzewa", "Zamknięto cały park"], 0, "Маршрут отвели от гнёзд."), ("Co ponownie wykorzystano?", ["Stare kamienie", "Plastikowe butelki", "Samochody"], 0, "В проекте повторно применили камни."), ("Jaki jest główny wniosek?", ["Rozwiązanie może łączyć naturę i potrzeby ludzi", "Jedna inwestycja kończy zmianę klimatu", "Beton zawsze chroni przed powodzią"], 0, "Финал подчёркивает баланс."))},
    },
    {
        "id": "b1-poland-regions", "title": "Польша и регионы", "description": "Представляем регион и сравниваем сведения из разных источников", "emoji": "🗺️", "position": 10,
        "prefix": "b1region", "lesson_start": 158, "card_start": 512,
        "theory": ("Связное сравнение источников", [["Сходство", "Zarówno… jak i… объединяет общие признаки."], ["Различие", "Natomiast, w przeciwieństwie do и podczas gdy показывают контраст."], ["Источник", "Według + родительный сообщает, откуда взяты сведения."]]),
        "cards": (("region", "регион", "Każdy region ma własne tradycje."), ("województwo", "воеводство", "Miasto leży w tym województwie."), ("krajobraz", "ландшафт", "Krajobraz zmienia się za przełęczą."), ("dziedzictwo", "наследие", "Muzeum chroni lokalne dziedzictwo."), ("gwara", "диалект", "Starsze osoby nadal mówią gwarą."), ("rzemiosło", "ремесло", "Region słynie z tradycyjnego rzemiosła."), ("szlak", "маршрут", "Szlak prowadzi przez trzy wsie."), ("przełęcz", "горный перевал", "Z przełęczy widać dolinę."), ("według", "согласно", "Według przewodnika trasa ma osiem kilometrów."), ("natomiast", "в то время как", "Centrum jest gwarne, natomiast okolica spokojna."), ("w przeciwieństwie do", "в отличие от", "W przeciwieństwie do lata zimą jest tu cicho."), ("zarówno", "как… так и", "Zarówno historia, jak i przyroda przyciągają gości."), ("wyróżniać się", "выделяться", "Miasteczko wyróżnia się drewnianą zabudową."), ("graniczyć", "граничить", "Region graniczy z Czechami."), ("zachować", "сохранить", "Mieszkańcy chcą zachować tradycję.")),
        "grammar": (("Według ___ ten szlak jest dostępny także zimą.", ["przewodnika", "przewodnik", "przewodnikiem"], 0, "Według требует родительного падежа."), ("Zarówno muzeum, ___ stary rynek opowiadają historię miasta.", ["jak i", "natomiast", "według"], 0, "Парная конструкция zarówno… jak i."), ("Północ regionu jest płaska, ___ południe ma górski krajobraz.", ["natomiast", "zarówno", "według"], 0, "Natomiast вводит контраст."), ("W przeciwieństwie ___ popularnego kurortu ta wieś jest spokojna.", ["do", "z", "od"], 0, "Устойчивое управление w przeciwieństwie do."), ("Составьте: Согласно музею ремесло сохранилось благодаря местным семьям.", ["Według muzeum rzemiosło zachowało się dzięki lokalnym rodzinom.", "Według muzeum rzemiosłem zachowali lokalne rodziny.", "Muzeum natomiast zachować rzemiosło rodzin."], 0, "Według + родительный и dzięki + дательный."), ("Составьте: Как природа, так и наследие выделяют этот регион.", ["Zarówno przyroda, jak i dziedzictwo wyróżniają ten region.", "Natomiast przyroda według dziedzictwa region.", "Zarówno przyrodę i dziedzictwem wyróżnia."], 0, "Оба подлежащих соединены zarówno… jak i.")),
        "quiz": (("Что такое województwo?", ["административный регион Польши", "горный маршрут", "народный костюм"], 0, "Это крупнейшая административная единица."), ("Region ___ z Czechami.", ["graniczy", "wyróżnia", "zachowuje się do"], 0, "Graniczyć z — граничить с."), ("Według ___ muzeum otwarto w 1920 roku.", ["kroniki", "kronika", "kroniką"], 0, "Według требует родительного."), ("Zarówno góry, ___ jeziora przyciągają turystów.", ["jak i", "natomiast", "podczas"], 0, "Правильная парная конструкция."), ("Что означает dziedzictwo?", ["наследие", "граница", "погода"], 0, "Это культурные и исторические ценности."), ("Centrum jest ruchliwe, ___ wsie są spokojne.", ["natomiast", "zarówno", "według"], 0, "Нужен контраст."), ("Które połączenie jest naturalne?", ["zachować tradycję", "graniczyć krajobraz", "wyróżniać gwarą do"], 0, "Zachować tradycję — сохранить традицию."), ("Как корректно сослаться на источник?", ["Według lokalnego archiwum…", "Każdy na pewno wie…", "Bez żadnych danych…"], 0, "Первый вариант прозрачно называет источник."), ("W przeciwieństwie ___ miasta wieś nie ma tramwajów.", ["do", "dla", "nad"], 0, "Фиксированное управление do."), ("Które zdanie porównuje dwa źródła?", ["Przewodnik podkreśla krajobraz, natomiast muzeum opisuje rzemiosło.", "Źródło jest źródłem.", "Region leży."], 0, "Первый вариант сопоставляет акценты.")),
        "reading": {"id": "b1region-dwa-spojrzenia-na-beskid", "title": "Dwa spojrzenia na Beskid Niski", "description": "Как сопоставить путеводитель и местный музей", "emoji": "🗺️", "minutes": 9, "paragraphs": ["Kasia planowała weekend w Beskidzie Niskim, regionie, który graniczy ze Słowacją. Według internetowego przewodnika jego największą zaletą są spokojne szlaki, łagodne przełęcze i krajobraz bez dużych kurortów. Autor polecał przede wszystkim długie wycieczki piesze.", "Kasia sprawdziła też stronę lokalnego muzeum. W przeciwieństwie do przewodnika muzeum mniej pisało o trasach, natomiast dokładnie przedstawiało dziedzictwo mieszkańców: drewnianą zabudowę, dawne rzemiosło oraz słowa zachowane w miejscowej gwarze.", "Na miejscu odwiedziła zarówno małą wystawę, jak i rodzinny warsztat. Rzemieślniczka wyjaśniła, że region wyróżnia się nie tylko krajobrazem. Ważne są również historie rodzin, które przez pokolenia zachowywały umiejętności i dzieliły się nimi z młodszymi.", "Oba źródła okazały się przydatne, chociaż każde miało inny cel. Przewodnik pomógł zaplanować szlak, podczas gdy muzeum pozwoliło lepiej zrozumieć ludzi i tradycje. Kasia uznała, że pełny obraz regionu powstaje dopiero wtedy, gdy porównuje się informacje z kilku perspektyw."], "glossary": {"graniczy": ("graniczyć", "граничит", "глагол"), "zaletą": ("zaleta", "преимущество", "существительное"), "łagodne": ("łagodny", "пологий", "прилагательное"), "kurortów": ("kurort", "курорт", "существительное"), "dawne": ("dawny", "старинный", "прилагательное"), "zabudowę": ("zabudowa", "застройка", "существительное"), "zachowane": ("zachować", "сохранённые", "причастие"), "gwarze": ("gwara", "диалект", "существительное"), "warsztat": ("warsztat", "мастерская", "существительное"), "rzemieślniczka": ("rzemieślniczka", "мастерица", "существительное"), "pokolenia": ("pokolenie", "поколение", "существительное"), "umiejętności": ("umiejętność", "умение", "существительное"), "perspektyw": ("perspektywa", "перспектива", "существительное"), "pełny": ("pełny", "полный", "прилагательное")}, "check": (("Gdzie planowała wyjazd Kasia?", ["W Beskid Niski", "Nad Bałtyk", "Do Warszawy"], 0, "Она выбрала Бескид Ниски."), ("Co podkreślał przewodnik?", ["Szlaki i krajobraz", "Wyłącznie przemysł", "Ceny mieszkań"], 0, "Путеводитель был ориентирован на маршруты."), ("Na czym skupiało się muzeum?", ["Na dziedzictwie i rzemiośle", "Na rozkładzie pociągów", "Na pogodzie"], 0, "Музей рассказывал о наследии."), ("Kogo spotkała Kasia?", ["Rzemieślniczkę", "Burmistrza Warszawy", "Pilota"], 0, "Она посетила семейную мастерскую."), ("Dlaczego oba źródła były przydatne?", ["Miały różne, uzupełniające się cele", "Powtarzały dokładnie to samo", "Nie zawierały informacji"], 0, "Источники дополняли друг друга."), ("Jaki jest wniosek?", ["Pełny obraz wymaga kilku perspektyw", "Wystarcza jeden nagłówek", "Tradycje nie mają znaczenia"], 0, "Вывод — сравнивать перспективы."))},
    },
    {
        "id": "b1-final-project", "title": "Проект B1", "description": "Интегрируем рассказ, письмо, чтение и аргументированное обсуждение", "emoji": "🏁", "position": 11,
        "prefix": "b1final", "lesson_start": 163, "card_start": 527,
        "theory": ("Связный проект B1", [["Структура", "Сначала обозначь цель, затем аргументы и пример, в конце — вывод."], ["Письмо", "Соблюдай обращение, абзацы, нейтральный регистр и заключительную формулу."], ["Самопроверка", "Проверь времена, связки, падежи и то, отвечает ли текст задаче."]]),
        "cards": (("cel", "цель", "Najpierw określ cel wypowiedzi."), ("odbiorca", "адресат", "Dostosuj styl do odbiorcy."), ("wstęp", "введение", "Krótki wstęp przedstawia temat."), ("argument", "аргумент", "Każdy argument poprzyj przykładem."), ("przykład", "пример", "Konkretny przykład wzmacnia opinię."), ("wniosek", "вывод", "Na końcu sformułuj wniosek."), ("akapit", "абзац", "Nowa myśl zaczyna nowy akapit."), ("spójny", "связный", "Tekst jest spójny i logiczny."), ("uzasadnić", "обосновать", "Uzasadnij swoją propozycję."), ("podsumować", "подвести итог", "Podsumuj najważniejsze informacje."), ("odnieść się do", "сослаться на", "Odnieś się do opinii rozmówcy."), ("zaproponować", "предложить", "Zaproponuj realistyczne rozwiązanie."), ("formalny", "официальный", "W urzędzie wybierz formalny styl."), ("poprawić", "исправить", "Przeczytaj tekst i popraw błędy."), ("kryterium", "критерий", "Każde kryterium jest jasno opisane.")),
        "grammar": (("Dobre wystąpienie zaczyna się od jasnego ___.", ["celu", "celem", "cel"], 0, "Od требует родительного падежа."), ("Najpierw przedstaw problem, ___ podaj argument i przykład.", ["następnie", "ponieważ", "chociaż"], 0, "Następnie организует последовательность."), ("W oficjalnym e-mailu napisz: ___.", ["Szanowni Państwo, zwracam się z prośbą…", "Hej, zróbcie to szybko!", "No więc mam sprawę."], 0, "Первый вариант соответствует официальному регистру."), ("Odniosę się ___ argumentu poprzedniej osoby.", ["do", "na", "z"], 0, "Odnieść się do требует родительного."), ("Составьте: В заключение я предлагаю решение, которое принесёт пользу жителям.", ["Podsumowując, proponuję rozwiązanie, które przyniesie korzyść mieszkańcom.", "Podsumowanie proponuje mieszkańcy korzyścią rozwiązanie.", "Chociaż rozwiązanie, więc mieszkańcom."], 0, "Podsumowując вводит вывод, a które связывает описание."), ("Составьте: Прежде чем отправить письмо, проверь структуру и исправь ошибки.", ["Zanim wyślesz wiadomość, sprawdź strukturę i popraw błędy.", "Zanim wysłać wiadomość, poprawił struktury błędy.", "Po wysłaniu zanim wiadomość sprawdza."], 0, "После zanim используются личные формы будущего/настоящего.")),
        "quiz": (("Что должно быть во введении?", ["тема и цель", "все детали сразу", "только прощание"], 0, "Введение ориентирует адресата."), ("Każdy argument warto poprzeć ___.", ["przykładem", "odbiorcy", "akapitu"], 0, "Poprzeć czym требует творительного."), ("Jak zakończyć formalny e-mail?", ["Z poważaniem", "Pa!", "Do zobaczyska"], 0, "Z poważaniem — нейтральная формальная формула."), ("Odnieść się ___ opinii rozmówcy.", ["do", "za", "przez"], 0, "Правильное управление do."), ("Co oznacza spójny tekst?", ["мысли логически связаны", "в нём нет абзацев", "он состоит из одного слова"], 0, "Связность — логическая связь частей."), ("Najpierw cel, ___ argumenty, na końcu wniosek.", ["następnie", "mimo że", "ponieważ"], 0, "Маркер последовательности."), ("Który element wzmacnia opinię?", ["konkretny przykład", "повтор без причины", "смена темы"], 0, "Пример поддерживает аргумент."), ("Какое действие относится к самопроверке?", ["poprawić błędy", "usunąć wniosek", "pominąć zadanie"], 0, "Нужно исправить ошибки."), ("Dostosuj styl do ___.", ["odbiorcy", "odbiorcą", "odbiorcę"], 0, "Do требует родительного."), ("Który wniosek jest dobry?", ["Podsumowując, rozwiązanie jest możliwe, jeśli podzielimy zadania.", "To wszystko, bo tak.", "Nie pamiętam tematu."], 0, "Первый вывод резюмирует и уточняет условие.")),
        "reading": {"id": "b1final-projekt-marty", "title": "Projekt Marty: miejsce dla młodych", "description": "Итоговый проект: от чтения источников до письма и обсуждения", "emoji": "🏁", "minutes": 10, "paragraphs": ["Marta przygotowywała projekt końcowy kursu. Wybrała temat miejsca spotkań dla młodych mieszkańców. Jej celem było nie tylko opisanie problemu, lecz także zaproponowanie rozwiązania, które można przedstawić radzie dzielnicy.", "Najpierw przeczytała dwa źródła: raport o potrzebach młodzieży i artykuł o podobnej inicjatywie w innym mieście. W osobnych akapitach podsumowała najważniejsze dane, porównała opinie i odniosła się do argumentu o kosztach.", "Następnie napisała formalny e-mail. We wstępie określiła cel, później uzasadniła propozycję konkretnymi przykładami, a w ostatnim akapicie poprosiła o spotkanie. Przed wysłaniem sprawdziła każde kryterium, poprawiła błędy i uprościła zbyt długie zdania.", "Podczas prezentacji jedna osoba nie zgodziła się z lokalizacją. Marta spokojnie odniosła się do tej opinii i zaproponowała wspólne porównanie dwóch miejsc. W podsumowaniu grupa przyjęła realistyczny plan. Projekt pokazał Marcie, że spójna wypowiedź łączy źródła, jasną strukturę i gotowość do rozmowy."], "glossary": {"końcowy": ("końcowy", "итоговый", "прилагательное"), "lecz": ("lecz", "но", "союз"), "radzie": ("rada", "совет", "существительное"), "raport": ("raport", "отчёт", "существительное"), "podsumowała": ("podsumować", "подвела итог", "глагол"), "odniosła się": ("odnieść się", "сослалась", "глагол"), "kosztach": ("koszt", "расходы", "существительное"), "określiła": ("określić", "определила", "глагол"), "uzasadniła": ("uzasadnić", "обосновала", "глагол"), "kryterium": ("kryterium", "критерий", "существительное"), "uprościła": ("uprościć", "упростила", "глагол"), "lokalizacją": ("lokalizacja", "местоположение", "существительное"), "przyjęła": ("przyjąć", "приняла", "глагол"), "gotowość": ("gotowość", "готовность", "существительное")}, "check": (("Jaki temat wybrała Marta?", ["Miejsce spotkań dla młodych", "Budowę lotniska", "Recenzję filmu"], 0, "Это тема итогового проекта."), ("Jakie źródła przeczytała?", ["Raport i artykuł o podobnej inicjatywie", "Tylko komentarze", "Powieść i wiersz"], 0, "Она использовала два разных источника."), ("Jak zbudowała e-mail?", ["Cel, argumenty z przykładami i prośba", "Jedno zdanie bez celu", "Same pytania"], 0, "Письмо имело ясную структуру."), ("Co zrobiła przed wysłaniem?", ["Sprawdziła kryteria i poprawiła błędy", "Usunęła wniosek", "Zmieniła temat"], 0, "Она провела самопроверку."), ("Jak zareagowała na sprzeciw?", ["Spokojnie odpowiedziała i zaproponowała porównanie", "Przerwała prezentację", "Zignorowała rozmówcę"], 0, "Она вступила в конструктивное обсуждение."), ("Co łączy spójna wypowiedź?", ["Źródła, strukturę i dialog", "Tylko trudne słowa", "Brak przykładów"], 0, "Это итоговый вывод текста."))},
    },
)


def seed(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    Course, Topic = apps.get_model("learning", "Course"), apps.get_model("learning", "Topic")
    Lesson, Flashcard = apps.get_model("learning", "Lesson"), apps.get_model("learning", "Flashcard")
    Link, Question = apps.get_model("learning", "LessonFlashcard"), apps.get_model("learning", "Question")
    ReadingText = apps.get_model("learning", "ReadingText")
    course = Course.objects.get(id="b1-independent")
    for spec in TOPICS:
        topic, _ = Topic.objects.update_or_create(id=spec["id"], defaults={"course": course, "title": spec["title"], "description": spec["description"], "emoji": spec["emoji"], "position": spec["position"], "is_active": True})
        p = spec["prefix"]
        rows = ((f"{p}-words", "words", "Słowa w kontekście", "Новая лексика", "8 карточек · B1", spec["description"], 9, spec["emoji"]), (f"{p}-grammar", "grammar", "Jak to wyrazić?", "Языковой фокус", "6 заданий · B1", spec["theory"][0], 12, "✏️"), (f"{p}-review", "review", "Powtórka aktywna", "Активное повторение", "7 карточек · B1", "Закрепи лексику темы", 8, "🔄"), (f"{p}-quiz", "quiz", f"Quiz: {spec['title']}", "Проверка темы", "10 вопросов · B1", "Проверь лексику и связность", 9, "🎯"), (f"{p}-reading-check", "quiz", "Czy rozumiesz tekst?", "Понимание текста", "6 вопросов · B1", "Найди детали и главный вывод", 7, "📖"))
        lessons = {}
        for position, row in enumerate(rows, spec["lesson_start"]):
            id_, kind, title, plan, subtitle, description, minutes, emoji = row
            lessons[id_], _ = Lesson.objects.update_or_create(id=id_, defaults={"topic": topic, "kind": kind, "title": title, "plan_title": plan, "subtitle": subtitle, "description": description, "minutes": minutes, "emoji": emoji, "position": position, "is_active": True, "source_metadata": SOURCE})
        grammar = lessons[f"{p}-grammar"]
        grammar.theory_title, grammar.theory_sections = spec["theory"]
        grammar.save(update_fields=("theory_title", "theory_sections"))
        cards = []
        for offset, (polish, translation, example) in enumerate(spec["cards"]):
            card, _ = Flashcard.objects.update_or_create(id=f"{p}-{offset + 1}", defaults={"polish": polish, "translation": translation, "example": example, "position": spec["card_start"] + offset, "is_active": True, "source_metadata": SOURCE})
            cards.append(card)
        for lesson_id, selected in ((f"{p}-words", cards[:8]), (f"{p}-review", cards[8:])):
            Link.objects.filter(lesson_id=lesson_id).delete()
            for position, card in enumerate(selected):
                Link.objects.create(lesson_id=lesson_id, flashcard=card, position=position)
        for lesson_id, questions in ((f"{p}-grammar", spec["grammar"]), (f"{p}-quiz", spec["quiz"]), (f"{p}-reading-check", spec["reading"]["check"])):
            Question.objects.filter(lesson_id=lesson_id).delete()
            for position, question in enumerate(questions):
                Question.objects.create(lesson_id=lesson_id, prompt=question[0], options=question[1], correct=question[2], explanation=question[3], position=position)
        reading = spec["reading"]
        glossary = {surface: {"lemma": entry[0], "translation": entry[1], "part_of_speech": entry[2]} for surface, entry in reading["glossary"].items()}
        ReadingText.objects.update_or_create(id=reading["id"], defaults={"topic": topic, "title": reading["title"], "description": reading["description"], "level": "B1", "minutes": reading["minutes"], "emoji": reading["emoji"], "position": 32 + spec["position"] - 8, "paragraphs": reading["paragraphs"], "glossary": glossary, "source_metadata": {**SOURCE, "comprehension_lesson_id": f"{p}-reading-check"}, "is_active": True})


class Migration(migrations.Migration):
    dependencies = [("learning", "0039_b1_culture_content")]
    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
