from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}

RAW=(
("c1-style-register","Стиль и регистр","Адаптируем речь к аудитории и ситуации","🎭",("rejestr","регистр"),("dobór słów","выбор слов"),("zwrot grzecznościowy","формула вежливости"),("potoczny","разговорный"),("neutralny","нейтральный"),("oficjalny","официальный"),("dostosować wypowiedź","адаптировать высказывание"),("zachować dystans","сохранять дистанцию"),("skrócić dystans","сократить дистанцию"),("brzmieć protekcjonalnie","звучать покровительственно"),("niestosowny","неуместный"),("adresat","адресат"),("kontekst sytuacyjny","ситуативный контекст"),("przeredagować","переформулировать"),("wyważyć ton","выверить тон"),["Redaktorka przygotowała trzy wersje tej samej wiadomości: do przyjaciela, zespołu i urzędu.","Wersja potoczna była krótka i bezpośrednia, lecz w urzędzie brzmiałaby niestosownie.","Tekst oficjalny zawierał zwrot grzecznościowy i precyzyjny cel, ale nie był chłodny.","Redaktorka zauważyła, że nadmierna uprzejmość może brzmieć protekcjonalnie.","Dobry rejestr nie polega na trudnych słowach, tylko na świadomym dopasowaniu tonu do adresata."],"Dlaczego powstały trzy wersje?","Aby dopasować ton do adresata"),
("c1-complex-argument","Сложная аргументация","Строим позицию с оговорками и контраргументом","⚖️",("zastrzeżenie","оговорка"),("przesłanka","предпосылка"),("tok rozumowania","ход рассуждения"),("kontrargument","контраргумент"),("obalić zarzut","опровергнуть возражение"),("przyznać rację","признать правоту"),("z dużym prawdopodobieństwem","с большой вероятностью"),("nie przesądza","не предрешает"),("o tyle, o ile","постольку, поскольку"),("tym niemniej","тем не менее"),("wynikać pośrednio","косвенно следовать"),("uprawniony wniosek","обоснованный вывод"),("nadużycie","злоупотребление"),("ważyć argumenty","взвешивать аргументы"),("niuansować stanowisko","нюансировать позицию"),["Rada debatowała nad ograniczeniem ruchu w centrum i analizowała kilka sprzecznych danych.","Zwolennicy wskazali poprawę jakości powietrza, przyznając zarazem, że dostawy mogą być trudniejsze.","Przeciwnicy przedstawili kontrargument dotyczący kosztów, lecz pojedynczy przykład nie przesądzał wyniku.","Ekspert zważył argumenty i oddzielił przesłanki od założeń, których raport nie potwierdzał.","Wniosek poparł pilotaż o tyle, o ile miasto równolegle zbada dostępność i skutki dla handlu."],"Jaki warunek zawierał wniosek?","Równoległe badanie skutków pilotażu"),
("c1-analytical-reading","Аналитическое чтение","Выявляем предпосылки, тон и стратегию автора","🔎",("założenie ukryte","скрытая предпосылка"),("rama interpretacyjna","интерпретационная рамка"),("dobór przykładów","подбор примеров"),("pominięcie","умолчание"),("wydźwięk","оттенок, звучание"),("ironiczny","ироничный"),("wartościujący","оценочный"),("pozornie neutralny","внешне нейтральный"),("sugerować","намекать"),("podważać","ставить под сомнение"),("strategia autora","стратегия автора"),("wiarygodność","достоверность"),("punkt widzenia","точка зрения"),("odczytać intencję","считать намерение"),("wniosek implicytny","имплицитный вывод"),["Studentka porównała dwa komentarze o tej samej zmianie w mieście.","Pierwszy tekst pozornie neutralnie wyliczał koszty, lecz pomijał korzyści i głosy mieszkańców.","Drugi używał ironicznych pytań, dlatego jego wydźwięk był wyraźnie wartościujący.","Studentka zbadała dobór przykładów, źródła i ramę interpretacyjną zamiast zgadywać poglądy autora.","Uznała, że analityczne czytanie oddziela treść jawną od wniosku sugerowanego przez strukturę tekstu."],"Co pominął pierwszy komentarz?","Korzyści i głosy mieszkańców"),
("c1-mediation","Медиация","Передаём сложную информацию неспециалисту","🧩",("sedno","суть"),("odbiorca niespecjalistyczny","неспециалист"),("przełożyć na prosty język","переложить простым языком"),("uniknąć uproszczenia","избежать упрощения"),("objaśnić pojęcie","объяснить понятие"),("zachować zastrzeżenie","сохранить оговорку"),("uporządkować informacje","структурировать информацию"),("podać analogię","привести аналогию"),("wyjaśnić zależność","объяснить зависимость"),("pominąć detal","опустить деталь"),("sprawdzić zrozumienie","проверить понимание"),("podsumować","подвести итог"),("pośredniczyć","посредничать"),("wiernie oddać sens","точно передать смысл"),("stopniować trudność","дозировать сложность"),["Analityczka miała wyjaśnić mieszkańcom raport o retencji wody, pełen terminów technicznych.","Najpierw wydobyła sedno: więcej zieleni spowalnia odpływ i zmniejsza ryzyko lokalnych podtopień.","Podała analogię do gąbki, ale zaznaczyła, że park nie zatrzyma każdej ulewy.","Pominęła wzory, zachowała natomiast liczby potrzebne do porównania wariantów i objaśniła ich zależność.","Na końcu poprosiła odbiorców o własne podsumowanie, aby sprawdzić zrozumienie bez infantylizowania rozmowy."],"Jakiej analogii użyła analityczka?","Porównała zieleń do gąbki"),)

def seed(apps,schema_editor):
 if schema_editor.connection.vendor!="sqlite": return
 Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Card=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Q=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); Reading=apps.get_model("learning","ReadingText"); course,_=Course.objects.update_or_create(id="c1-proficiency",defaults={"title":"C1 · Гибкость и точность","description":"Точная речь, аналитическое чтение и медиация","level":"C1","position":4,"is_active":True})
 for n,s in enumerate(RAW):
  tid,title,desc,emoji,*rest=s; terms=rest[:15]; paragraphs,prompt,answer=rest[15:]; prefix=f"c1{n+1}"; topic,_=Topic.objects.update_or_create(id=tid,defaults={"course":course,"title":title,"description":desc,"emoji":emoji,"position":n,"is_active":True}); rows=(("words","Słowa w kontekście",8),("grammar","Jak to wyrazić?",6),("review","Powtórka aktywna",7),("quiz",f"Quiz: {title}",10),("reading-check","Czy rozumiesz tekst?",6)); lessons={}
  for pos,(suffix,lt,count) in enumerate(rows,242+n*5): lessons[suffix],_=Lesson.objects.update_or_create(id=f"{prefix}-{suffix}",defaults={"topic":topic,"kind":"quiz" if suffix in ("quiz","reading-check") else suffix,"title":lt,"plan_title":lt,"subtitle":f"{count} заданий · C1","description":desc,"minutes":12,"emoji":emoji,"position":pos,"is_active":True,"theory_title":desc if suffix=="grammar" else "","theory_sections":[["Фокус темы",desc],["Практика","Выбирай формулировку с учётом смысла, адресата и контекста."]] if suffix=="grammar" else [],"source_metadata":SOURCE})
  cards=[]
  for i,(pl,tr) in enumerate(terms): cards.append(Card.objects.update_or_create(id=f"{prefix}-{i+1}",defaults={"polish":pl,"translation":tr,"example":f"W tej wypowiedzi ważne jest wyrażenie: {pl}.","position":722+n*15+i,"is_active":True,"source_metadata":SOURCE})[0])
  for suffix,subset in (("words",cards[:8]),("review",cards[8:])):
   Link.objects.filter(lesson=lessons[suffix]).delete()
   for i,c in enumerate(subset): Link.objects.create(lesson=lessons[suffix],flashcard=c,position=i)
  grammar=tuple((f"Wybierz wyrażenie pasujące do celu: {tr}.",[pl,terms[(i+1)%15][0],terms[(i+2)%15][0]],0,f"{pl} oznacza: {tr}.") for i,(pl,tr) in enumerate(terms[:6])); quiz=tuple((f"Co znaczy „{pl}”?",[tr,terms[(i+1)%15][1],terms[(i+2)%15][1]],0,f"„{pl}” — {tr}.") for i,(pl,tr) in enumerate(terms[:10])); check=((prompt,[answer,"Nie podano tego w tekście","Autor odrzucił wszystkie dane"],0,"Ответ прямо следует из текста."),)+tuple((f"Która teza najlepiej opisuje akapit {i+1}?",[p,paragraphs[(i+1)%5],paragraphs[(i+2)%5]],0,"Первый вариант точно передаёт содержание абзаца.") for i,p in enumerate(paragraphs[:5]))
  for suffix,questions in (("grammar",grammar),("quiz",quiz),("reading-check",check)):
   Q.objects.filter(lesson=lessons[suffix]).delete()
   for i,q in enumerate(questions): Q.objects.create(lesson=lessons[suffix],prompt=q[0],options=q[1],correct=q[2],explanation=q[3],position=i)
  glossary={pl:{"lemma":pl,"translation":tr,"part_of_speech":"wyrażenie"} for pl,tr in terms}; Reading.objects.update_or_create(id=f"{prefix}-tekst",defaults={"topic":topic,"title":title,"description":desc,"level":"C1","minutes":14,"emoji":emoji,"paragraphs":paragraphs,"glossary":glossary,"source_metadata":{**SOURCE,"comprehension_lesson_id":f"{prefix}-reading-check"},"position":47+n,"is_active":True})

class Migration(migrations.Migration):
 dependencies=[("learning","0051_a1_reading_comprehension")]
 operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
