from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}

RAW=(
("c1-academic-writing","Академическое письмо","Создаём связный аналитический текст и синтезируем источники","📝",("spójność wywodu","связность рассуждения"),("akapit problemowy","проблемный абзац"),("zdanie tematyczne","тематическое предложение"),("łącznik","средство связи"),("synteza źródeł","синтез источников"),("przywołać badanie","сослаться на исследование"),("zastrzec","оговорить"),("doprecyzować tezę","уточнить тезис"),("wywód","изложение"),("konkluzja","заключение"),("argument poboczny","второстепенный аргумент"),("hierarchia informacji","иерархия информации"),("unikać powtórzeń","избегать повторов"),("redagować","редактировать"),("odsyłacz","ссылка"),["Marta redagowała esej o pracy zdalnej, opierając się na trzech badaniach o różnych metodach.","W zdaniu tematycznym każdego akapitu nazywała problem, a następnie zestawiała zgodne i sprzeczne wyniki.","Nie streszczała źródeł osobno: budowała syntezę, wskazywała ograniczenia prób i doprecyzowała własną tezę.","Argument poboczny przeniosła do przypisu, ponieważ zakłócał spójność wywodu i hierarchię informacji.","Konkluzja nie powtarzała wstępu, lecz odpowiadała na pytanie i formułowała ostrożny dalszy wniosek."],"Dlaczego argument trafił do przypisu?","Zakłócał główny wywód"),
("c1-professional-expertise","Профессиональная экспертиза","Объясняем сложную тему и ведём точные переговоры","💼",("zakres odpowiedzialności","сфера ответственности"),("warunek brzegowy","граничное условие"),("ryzyko operacyjne","операционный риск"),("wykonalność","реализуемость"),("uzgodnić kryteria","согласовать критерии"),("przedstawić rekomendację","представить рекомендацию"),("zastrzec poufność","оговорить конфиденциальность"),("wariant awaryjny","резервный вариант"),("oszacować nakład","оценить трудозатраты"),("rozbieżność","расхождение"),("wynegocjować","согласовать на переговорах"),("doprowadzić do eskalacji","привести к эскалации"),("punkt decyzyjny","точка принятия решения"),("mierzalny rezultat","измеримый результат"),("odpowiedzialność końcowa","итоговая ответственность"),["Ekspertka przedstawiła zarządowi plan migracji systemu, zaczynając od warunków brzegowych i zakresu odpowiedzialności.","Zamiast obiecywać bezproblemowy termin oszacowała nakład oraz trzy ryzyka operacyjne wraz z prawdopodobieństwem.","Działy miały rozbieżne oczekiwania, więc uzgodniła mierzalne kryteria i wyraźny punkt decyzyjny.","Negocjacje dotyczyły nie celu, lecz kolejności etapów, poufności danych i wariantu awaryjnego.","Rekomendacja była stanowcza, ale wskazywała granice ekspertyzy oraz osobę ponoszącą odpowiedzialność końcową."],"Co uzgodniły działy?","Mierzalne kryteria i punkt decyzyjny"),
("c1-literary-language","Литературный язык","Анализируем голос, образность и синтаксическую вариативность","📚",("narrator niewiarygodny","ненадёжный рассказчик"),("perspektywa","перспектива"),("metafora","метафора"),("porównanie","сравнение"),("rytm zdania","ритм предложения"),("elipsa","эллипсис"),("niedopowiedzenie","недосказанность"),("ironia dramatyczna","драматическая ирония"),("stylizacja","стилизация"),("głos bohatera","голос героя"),("obrazowanie","образность"),("kontrast","контраст"),("wieloznaczność","многозначность"),("punkt kulminacyjny","кульминация"),("interpretacja","интерпретация"),["W opowiadaniu fikcyjnej autorki narrator opisuje pusty dworzec, lecz stopniowo ujawnia własny udział w wydarzeniach.","Krótkie zdania przyspieszają rytm przed przyjazdem pociągu, a rozbudowane metafory zatrzymują czas we wspomnieniach.","Powracający obraz zegara można odczytać jako znak winy, choć tekst nie przesądza jednej interpretacji.","Czytelnik wie więcej niż bohater, dlatego jego pewne deklaracje tworzą ironię dramatyczną i podważają wiarygodność głosu.","Punkt kulminacyjny pozostaje eliptyczny; niedopowiedzenie zmusza odbiorcę do połączenia perspektyw i oceny narratora."],"Co podważa wiarygodność narratora?","Rozbieżność między jego pewnością a wiedzą czytelnika"),
("c1-public-discussion","Общественная дискуссия","Модерируем сложный разговор и ищем область согласия","🏛️",("obszar zgody","область согласия"),("oś sporu","ось спора"),("interesariusz","заинтересованная сторона"),("legitymizować decyzję","легитимизировать решение"),("zrównoważyć interesy","сбалансировать интересы"),("oddać sprawiedliwość argumentowi","отдать должное аргументу"),("nazwać napięcie","обозначить напряжение"),("ramy debaty","рамки дискуссии"),("eskalować konflikt","обострять конфликт"),("wypracować kompromis","выработать компромисс"),("warunek konieczny","необходимое условие"),("stanowisko mniejszości","позиция меньшинства"),("podsumowanie robocze","рабочее резюме"),("procedura konsultacji","процедура консультаций"),("odroczyć decyzję","отложить решение"),["Mieszkańcy debatowali o przebudowie placu, a moderatorka najpierw nazwała interesariuszy i ramy rozmowy.","Oś sporu dotyczyła miejsc parkingowych, jednak obie strony uznawały bezpieczeństwo pieszych za obszar zgody.","Moderatorka oddała sprawiedliwość argumentowi mniejszości i zatrzymała wypowiedź, która eskalowała konflikt.","Podsumowanie robocze rozdzieliło fakty, wartości i kwestie wymagające danych, dzięki czemu napięcie stało się czytelne.","Decyzję odroczono do konsultacji, ale ustalono warunki konieczne pilotażu i sposób oceny kompromisu."],"Co było obszarem zgody?","Bezpieczeństwo pieszych"),)

def seed(apps,schema_editor):
 if schema_editor.connection.vendor!="sqlite": return
 Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Card=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Q=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); Reading=apps.get_model("learning","ReadingText"); course,_=Course.objects.update_or_create(id="c1-proficiency",defaults={"title":"C1 · Гибкость и точность","description":"Точная речь, аналитическое чтение и медиация","level":"C1","position":4,"is_active":True})
 for n,s in enumerate(RAW):
  tid,title,desc,emoji,*rest=s; terms=rest[:15]; paragraphs,prompt,answer=rest[15:]; prefix=f"c1{n+5}"; topic,_=Topic.objects.update_or_create(id=tid,defaults={"course":course,"title":title,"description":desc,"emoji":emoji,"position":n+4,"is_active":True}); rows=(("words","Słowa w kontekście",8),("grammar","Jak to wyrazić?",6),("review","Powtórka aktywna",7),("quiz",f"Quiz: {title}",10),("reading-check","Czy rozumiesz tekst?",6)); lessons={}
  for pos,(suffix,lt,count) in enumerate(rows,262+n*5): lessons[suffix],_=Lesson.objects.update_or_create(id=f"{prefix}-{suffix}",defaults={"topic":topic,"kind":"quiz" if suffix in ("quiz","reading-check") else suffix,"title":lt,"plan_title":lt,"subtitle":f"{count} заданий · C1","description":desc,"minutes":12,"emoji":emoji,"position":pos,"is_active":True,"theory_title":desc if suffix=="grammar" else "","theory_sections":[["Фокус темы",desc],["Практика","Выбирай формулировку с учётом смысла, адресата и контекста."]] if suffix=="grammar" else [],"source_metadata":SOURCE})
  cards=[]
  for i,(pl,tr) in enumerate(terms): cards.append(Card.objects.update_or_create(id=f"{prefix}-{i+1}",defaults={"polish":pl,"translation":tr,"example":f"W tej wypowiedzi ważne jest wyrażenie: {pl}.","position":782+n*15+i,"is_active":True,"source_metadata":SOURCE})[0])
  for suffix,subset in (("words",cards[:8]),("review",cards[8:])):
   Link.objects.filter(lesson=lessons[suffix]).delete()
   for i,c in enumerate(subset): Link.objects.create(lesson=lessons[suffix],flashcard=c,position=i)
  grammar=tuple((f"Wybierz wyrażenie pasujące do celu: {tr}.",[pl,terms[(i+1)%15][0],terms[(i+2)%15][0]],0,f"{pl} oznacza: {tr}.") for i,(pl,tr) in enumerate(terms[:6])); quiz=tuple((f"Co znaczy „{pl}”?",[tr,terms[(i+1)%15][1],terms[(i+2)%15][1]],0,f"„{pl}” — {tr}.") for i,(pl,tr) in enumerate(terms[:10])); check=((prompt,[answer,"Nie podano tego w tekście","Autor odrzucił wszystkie dane"],0,"Ответ прямо следует из текста."),)+tuple((f"Która teza najlepiej opisuje akapit {i+1}?",[p,paragraphs[(i+1)%5],paragraphs[(i+2)%5]],0,"Первый вариант точно передаёт содержание абзаца.") for i,p in enumerate(paragraphs[:5]))
  for suffix,questions in (("grammar",grammar),("quiz",quiz),("reading-check",check)):
   Q.objects.filter(lesson=lessons[suffix]).delete()
   for i,q in enumerate(questions): Q.objects.create(lesson=lessons[suffix],prompt=q[0],options=q[1],correct=q[2],explanation=q[3],position=i)
  glossary={pl:{"lemma":pl,"translation":tr,"part_of_speech":"wyrażenie"} for pl,tr in terms}; Reading.objects.update_or_create(id=f"{prefix}-tekst",defaults={"topic":topic,"title":title,"description":desc,"level":"C1","minutes":14,"emoji":emoji,"paragraphs":paragraphs,"glossary":glossary,"source_metadata":{**SOURCE,"comprehension_lesson_id":f"{prefix}-reading-check"},"position":51+n,"is_active":True})



class Migration(migrations.Migration):
 dependencies=[("learning","0052_c1_first_four_content")]
 operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
