from django.db import migrations

SOURCE={"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}
RAW=(
("c1-media-language","Язык медиа","Сравниваем жанры, редактируем и преобразуем материал","📰",("konwencja gatunkowa","жанровая конвенция"),("lead","лид"),("nagłówek wartościujący","оценочный заголовок"),("rama przekazu","рамка сообщения"),("depesza","информационное сообщение"),("felieton","фельетон"),("sprostowanie","опровержение, исправление"),("autoryzacja wypowiedzi","согласование высказывания"),("skrót myślowy","смысловое сокращение"),("selekcja informacji","отбор информации"),("przekształcić gatunek","преобразовать жанр"),("zachować sens","сохранить смысл"),("wyostrzyć tezę","заострить тезис"),("oddzielić komentarz","отделить комментарий"),("odpowiedzialność redakcyjna","редакционная ответственность"),["Redakcja otrzymała depeszę o nowym programie transportowym i przygotowała z niej trzy materiały.","Krótka wiadomość zaczynała się od neutralnego leadu, podczas gdy felieton wyostrzał tezę i oceniał decyzję władz.","Post w mediach społecznościowych wymagał skrótu, lecz redaktorka usunęła nagłówek, który sugerował skutek niepotwierdzony w danych.","W każdym gatunku zachowała liczby, źródło i zastrzeżenia; komentarz został wyraźnie oddzielony od informacji.","Ćwiczenie pokazało, że przekształcenie gatunku zmienia selekcję i ton, ale nie powinno zmieniać sensu faktów."],"Co redaktorka usunęła z posta?","Nagłówek sugerujący niepotwierdzony skutek"),
("c1-final-project","Проект C1","Интегрируем исследование, письмо, презентацию и медиацию","🏆",("zakres projektu","охват проекта"),("pytanie przewodnie","ведущий вопрос"),("triangulacja źródeł","триангуляция источников"),("kryterium oceny","критерий оценки"),("synteza ustaleń","синтез выводов"),("wersja dla odbiorcy","версия для аудитории"),("obrona projektu","защита проекта"),("odpowiedzieć na zarzut","ответить на возражение"),("uznać ograniczenie","признать ограничение"),("wniosek warunkowy","условный вывод"),("materiał pomocniczy","вспомогательный материал"),("próba generalna","генеральная репетиция"),("informacja zwrotna","обратная связь"),("samoocena","самооценка"),("dalszy kierunek","дальнейшее направление"),["Zespół kończący poziom C1 badał, jak miasto może jasno informować mieszkańców o falach upałów.","Uczestnicy porównali dane, komunikaty urzędu i wywiady, a rozbieżności opisali zamiast ukrywać je w jednej średniej.","Powstały trzy wersje materiału: raport analityczny, krótka informacja publiczna i prezentacja dla osób starszych.","Podczas obrony zespół odpowiedział na zarzut zbyt małej próby, uznał ograniczenie i sformułował wniosek warunkowy.","Samoocena wykazała, że projekt łączył precyzję, mediację i odpowiedzialność za odbiorcę, a dalszym kierunkiem stały się testy z użytkownikami."],"Jakie trzy wersje materiału powstały?","Raport, informacja publiczna i prezentacja"),)

def seed(apps,schema_editor):
 if schema_editor.connection.vendor!="sqlite": return
 Course,Topic=apps.get_model("learning","Course"),apps.get_model("learning","Topic"); Lesson,Card=apps.get_model("learning","Lesson"),apps.get_model("learning","Flashcard"); Link,Q=apps.get_model("learning","LessonFlashcard"),apps.get_model("learning","Question"); Reading=apps.get_model("learning","ReadingText"); course,_=Course.objects.update_or_create(id="c1-proficiency",defaults={"title":"C1 · Гибкость и точность","description":"Точная речь, аналитическое чтение и медиация","level":"C1","position":4,"is_active":True})
 for n,s in enumerate(RAW):
  tid,title,desc,emoji,*rest=s; terms=rest[:15]; paragraphs,prompt,answer=rest[15:]; prefix=f"c1{n+9}"; topic,_=Topic.objects.update_or_create(id=tid,defaults={"course":course,"title":title,"description":desc,"emoji":emoji,"position":n+8,"is_active":True}); rows=(("words","Słowa w kontekście",8),("grammar","Jak to wyrazić?",6),("review","Powtórka aktywna",7),("quiz",f"Quiz: {title}",10),("reading-check","Czy rozumiesz tekst?",6)); lessons={}
  for pos,(suffix,lt,count) in enumerate(rows,282+n*5): lessons[suffix],_=Lesson.objects.update_or_create(id=f"{prefix}-{suffix}",defaults={"topic":topic,"kind":"quiz" if suffix in ("quiz","reading-check") else suffix,"title":lt,"plan_title":lt,"subtitle":f"{count} заданий · C1","description":desc,"minutes":12,"emoji":emoji,"position":pos,"is_active":True,"theory_title":desc if suffix=="grammar" else "","theory_sections":[["Фокус темы",desc],["Практика","Выбирай формулировку с учётом смысла, адресата и контекста."]] if suffix=="grammar" else [],"source_metadata":SOURCE})
  cards=[]
  for i,(pl,tr) in enumerate(terms): cards.append(Card.objects.update_or_create(id=f"{prefix}-{i+1}",defaults={"polish":pl,"translation":tr,"example":f"W tej wypowiedzi ważne jest wyrażenie: {pl}.","position":842+n*15+i,"is_active":True,"source_metadata":SOURCE})[0])
  for suffix,subset in (("words",cards[:8]),("review",cards[8:])):
   Link.objects.filter(lesson=lessons[suffix]).delete()
   for i,c in enumerate(subset): Link.objects.create(lesson=lessons[suffix],flashcard=c,position=i)
  grammar=tuple((f"Wybierz wyrażenie pasujące do celu: {tr}.",[pl,terms[(i+1)%15][0],terms[(i+2)%15][0]],0,f"{pl} oznacza: {tr}.") for i,(pl,tr) in enumerate(terms[:6])); quiz=tuple((f"Co znaczy „{pl}”?",[tr,terms[(i+1)%15][1],terms[(i+2)%15][1]],0,f"„{pl}” — {tr}.") for i,(pl,tr) in enumerate(terms[:10])); check=((prompt,[answer,"Nie podano tego w tekście","Autor odrzucił wszystkie dane"],0,"Ответ прямо следует из текста."),)+tuple((f"Która teza najlepiej opisuje akapit {i+1}?",[p,paragraphs[(i+1)%5],paragraphs[(i+2)%5]],0,"Первый вариант точно передаёт содержание абзаца.") for i,p in enumerate(paragraphs[:5]))
  for suffix,questions in (("grammar",grammar),("quiz",quiz),("reading-check",check)):
   Q.objects.filter(lesson=lessons[suffix]).delete()
   for i,q in enumerate(questions): Q.objects.create(lesson=lessons[suffix],prompt=q[0],options=q[1],correct=q[2],explanation=q[3],position=i)
  glossary={pl:{"lemma":pl,"translation":tr,"part_of_speech":"wyrażenie"} for pl,tr in terms}; Reading.objects.update_or_create(id=f"{prefix}-tekst",defaults={"topic":topic,"title":title,"description":desc,"level":"C1","minutes":14,"emoji":emoji,"paragraphs":paragraphs,"glossary":glossary,"source_metadata":{**SOURCE,"comprehension_lesson_id":f"{prefix}-reading-check"},"position":55+n,"is_active":True})





class Migration(migrations.Migration):
 dependencies=[("learning","0054_profile_daily_goal")]
 operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
