import * as Speech from 'expo-speech';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { Session } from '@supabase/supabase-js';

import { checkListeningAnswer, loadListening, type ListeningAnswer, type ListeningExercise } from '../lib/api';
import type { Colors } from '../theme';

const speeds = [0.75, 1, 1.15] as const;

export function ListeningScreen({ session, colors, onClose }: { session: Session; colors: Colors; onClose: () => void }) {
  const [items, setItems] = useState<ListeningExercise[]>([]); const [exercise, setExercise] = useState<ListeningExercise | null>(null);
  const [speed, setSpeed] = useState<number>(1); const [speaking, setSpeaking] = useState(false);
  const [answers, setAnswers] = useState<Record<string, ListeningAnswer>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const rows = await loadListening(session.access_token); setItems(rows.filter((item) => item.delivery === 'device_tts')); } catch { setError('Не удалось загрузить аудирование.'); } finally { setLoading(false); } }, [session.access_token]);
  useEffect(() => { void load(); return () => { void Speech.stop(); }; }, [load]);

  function speak(text: string) { void Speech.stop().then(() => { setSpeaking(true); Speech.speak(text, { language: 'pl-PL', rate: speed, onDone: () => setSpeaking(false), onStopped: () => setSpeaking(false), onError: () => { setSpeaking(false); setError('Системный голос недоступен на этом устройстве.'); } }); }); }
  async function answer(questionId: string, selectedIndex: number) { if (!exercise || answers[questionId]) return; setLoading(true); setError(''); try { const result = await checkListeningAnswer(exercise.id, questionId, selectedIndex, session.access_token); setAnswers((current) => ({ ...current, [questionId]: result })); } catch { setError('Ответ не проверился. Попробуйте снова.'); } finally { setLoading(false); } }
  function choose(item: ListeningExercise) { void Speech.stop(); setExercise(item); setAnswers({}); setError(''); setSpeaking(false); }

  if (!exercise) return <ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={onClose}><Text style={[styles.back, { color: colors.primary }]}>‹ Сегодня</Text></Pressable><Text style={[styles.title, { color: colors.text }]}>Аудирование</Text><Text style={[styles.copy, { color: colors.muted }]}>Связные оригинальные записи через системный польский голос. Это не студийное аудио.</Text>{loading ? <ActivityIndicator color={colors.primary} /> : items.map((item) => <Pressable accessibilityRole="button" key={item.id} onPress={() => choose(item)} style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.itemTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.level, { color: colors.primary }]}>{item.level} · {item.questions.length} задания</Text></Pressable>)}{!loading && !items.length && !error && <Text style={{ color: colors.muted }}>Упражнения пока недоступны.</Text>}{!!error && <Text accessibilityRole="alert" style={{ color: colors.danger }}>{error}</Text>}</ScrollView>;

  return <ScrollView contentContainerStyle={styles.page}>
    <Pressable accessibilityRole="button" onPress={() => { void Speech.stop(); setExercise(null); }}><Text style={[styles.back, { color: colors.primary }]}>‹ Все упражнения</Text></Pressable><Text style={[styles.level, { color: colors.primary }]}>{exercise.level} · SYSTEMOWY GŁOS PL‑PL</Text><Text style={[styles.title, { color: colors.text }]}>{exercise.title}</Text>
    <View style={styles.controls}><Pressable accessibilityRole="button" onPress={() => speaking ? void Speech.stop() : speak(exercise.transcript)} style={[styles.play, { backgroundColor: colors.primary }]}><Text style={styles.playText}>{speaking ? '■ Стоп' : '▶ Весь текст'}</Text></Pressable>{speeds.map((rate) => <Pressable key={rate} accessibilityRole="button" accessibilityState={{ selected: speed === rate }} onPress={() => setSpeed(rate)} style={[styles.speed, { borderColor: speed === rate ? colors.primary : colors.border }]}><Text style={{ color: speed === rate ? colors.primary : colors.text, fontWeight: '800' }}>{rate}×</Text></Pressable>)}</View>
    <Text style={[styles.section, { color: colors.text }]}>Фрагменты</Text>{exercise.fragments.map((fragment, index) => <Pressable accessibilityRole="button" key={fragment.id} onPress={() => speak(fragment.transcript)} style={[styles.fragment, { borderColor: colors.border }]}><Text style={{ color: colors.primary, fontWeight: '900' }}>▶ {index + 1}</Text><Text style={{ color: colors.text, flex: 1 }}>{fragment.transcript}</Text></Pressable>)}
    <View style={[styles.transcript, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.section, { color: colors.text }]}>Транскрипт</Text><Text style={[styles.transcriptText, { color: colors.text }]}>{exercise.transcript}</Text></View>
    <Text style={[styles.section, { color: colors.text }]}>Проверка понимания</Text>{exercise.questions.map((question) => <View key={question.id} style={[styles.question, { borderColor: colors.border }]}><Text style={[styles.questionTitle, { color: colors.text }]}>{question.prompt}</Text>{question.options.map((option, index) => <Pressable key={option} accessibilityRole="button" disabled={!!answers[question.id] || loading} onPress={() => answer(question.id, index)} style={[styles.option, { borderColor: answers[question.id]?.correct_index === index ? colors.primary : colors.border }]}><Text style={{ color: colors.text }}>{option}</Text></Pressable>)}{answers[question.id] && <View accessibilityRole="alert"><Text style={{ color: answers[question.id].correct ? colors.primary : colors.danger, fontWeight: '900' }}>{answers[question.id].correct ? 'Верно' : 'Неверно'}</Text><Text style={{ color: colors.muted }}>{answers[question.id].explanation}</Text></View>}</View>)}
    {!!error && <Text accessibilityRole="alert" style={{ color: colors.danger }}>{error}</Text>}<Text style={[styles.note, { color: colors.muted }]}>Качество и доступность голоса зависят от устройства. На iPhone выключите беззвучный режим, если звука нет.</Text>
  </ScrollView>;
}

const styles = StyleSheet.create({
  page: { padding: 20, paddingBottom: 40, gap: 14 }, back: { fontSize: 15, fontWeight: '800', paddingVertical: 8 }, title: { fontSize: 30, lineHeight: 38, fontWeight: '900' }, copy: { fontSize: 15, lineHeight: 22 }, item: { borderWidth: 1, borderRadius: 18, padding: 17, gap: 5 }, itemTitle: { fontSize: 18, fontWeight: '800' }, level: { fontSize: 12, fontWeight: '900', letterSpacing: .4 }, controls: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, play: { minHeight: 46, borderRadius: 13, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' }, playText: { color: '#fff', fontWeight: '900' }, speed: { minHeight: 46, minWidth: 58, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, section: { fontSize: 20, fontWeight: '900', marginTop: 5 }, fragment: { flexDirection: 'row', borderWidth: 1, borderRadius: 14, padding: 14, gap: 12, alignItems: 'flex-start' }, transcript: { borderWidth: 1, borderRadius: 18, padding: 18, gap: 10 }, transcriptText: { fontSize: 17, lineHeight: 27 }, question: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 10 }, questionTitle: { fontSize: 17, fontWeight: '800', lineHeight: 24 }, option: { minHeight: 48, borderWidth: 1, borderRadius: 12, padding: 13, justifyContent: 'center' }, note: { fontSize: 12, lineHeight: 18 },
});
