import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { Session } from '@supabase/supabase-js';
import { loadBootstrap, loadLatestDraft, type BootstrapData } from '../lib/api';
import type { Colors } from '../theme';

export function TodayScreen({ session, colors, onOpenLesson, onResumeLesson, onOpenFeedback, onOpenReview, onOpenReading, onOpenListening, onOpenProfile, onOpenAchievements, onOpenHistory, onOpenDiagnostic, onOpenWriting, onOpenInteraction }: { session: Session; colors: Colors; onOpenLesson: (lessonId: string) => void; onResumeLesson: (launch: { lessonId: string; stepIndex: number; score: number }) => void; onOpenFeedback: () => void; onOpenReview: () => void; onOpenReading: () => void; onOpenListening: () => void; onOpenProfile: () => void; onOpenAchievements: () => void; onOpenHistory: () => void; onOpenDiagnostic: () => void; onOpenWriting: () => void; onOpenInteraction: () => void }) {
  const [data, setData] = useState<BootstrapData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const refresh = useCallback(async () => {
    setLoading(true); setError('');
    try { setData(await loadBootstrap(session.access_token)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить план.'); } finally { setLoading(false); }
  }, [session.access_token]);
  useEffect(() => { void refresh(); }, [refresh]);
  if (!data && loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /><Text style={{ color: colors.muted }}>Загружаем план…</Text></View>;
  return <ScrollView contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={loading} onRefresh={refresh} tintColor={colors.primary} />}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>МОБИЛЬНАЯ БЕТА</Text><Text style={[styles.title, { color: colors.text }]}>Сегодня</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Открыть профиль" onPress={onOpenProfile} style={[styles.profileButton, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.profileIcon}>👤</Text></Pressable></View>
    {!!error && <View style={[styles.alert, { borderColor: colors.danger }]}><Text accessibilityRole="alert" style={{ color: colors.danger }}>{error}</Text><Pressable onPress={refresh}><Text style={[styles.link, { color: colors.primary }]}>Повторить</Text></Pressable></View>}
    {data && <><Text style={[styles.greeting, { color: colors.text }]}>Привет, {data.profile.display_name}</Text><Text style={[styles.sub, { color: colors.muted }]}>Уровень {data.profile.level} · серия {data.progress.streak_days} дн.</Text>
      <View style={[styles.goal, { backgroundColor: colors.primary }]}><Text style={styles.goalLabel}>Цель на сегодня</Text><Text style={styles.goalValue}>{data.today.completed_count} / {data.today.task_count}</Text><View style={styles.track}><View style={[styles.fill, { width: `${data.today.progress_percent}%` }]} /></View></View>
      <Pressable accessibilityRole="button" accessibilityLabel="Открыть диагностику уровня" onPress={onOpenDiagnostic} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>🧭</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Определить стартовый уровень</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Самооценка и 8 коротких заданий без сохранения ответов</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenWriting} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>📝</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Письмо</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Задания B1–B2 и честная проверка структуры</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenInteraction} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>💬</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Общение и медиация</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Сценарии B1–B2 и самостоятельные ответы</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenReading} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>📖</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Читать по-польски</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Тексты по уровням, закладки и словарь</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenListening} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>🎧</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Аудирование</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Диалоги A1–B2, транскрипты и задания</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenAchievements} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>🏆</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>Достижения</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Прогресс по урокам, серии и словарю</Text></View></Pressable>
      <Pressable accessibilityRole="button" onPress={onOpenHistory} style={[styles.readingLink, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.emoji}>📈</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>История обучения</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Завершённые уроки и результаты</Text></View></Pressable>
      {data.today.resume && <Pressable accessibilityRole="button" onPress={async () => { setError(''); try { const draft = await loadLatestDraft(session.access_token); if (draft) onResumeLesson({ lessonId: draft.lesson_id, stepIndex: draft.step_index, score: draft.score }); } catch { setError('Не удалось загрузить сохранённую позицию.'); } }} style={[styles.resume, { backgroundColor: colors.surface, borderColor: colors.primary }]}><Text style={[styles.taskTitle, { color: colors.text }]}>Продолжить: {data.today.resume.title}</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>С шага {data.today.resume.step}</Text><Text style={[styles.meta, { color: colors.primary }]}>Вернуться к уроку →</Text></Pressable>}
      <Text style={[styles.sectionTitle, { color: colors.text }]}>План</Text>
      {data.today.tasks.map((task) => <Pressable accessibilityRole="button" onPress={() => task.plan_type === 'dictionary-review' ? onOpenReview() : onOpenLesson(task.id)} key={`${task.plan_type}:${task.id}`} style={({ pressed }) => [styles.task, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? .7 : 1 }]}><Text style={styles.emoji}>{task.emoji || '📘'}</Text><View style={styles.taskBody}><Text style={[styles.taskTitle, { color: colors.text }]}>{task.completed ? '✓ ' : ''}{task.title}</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>{task.reinforcement_reason || task.description}</Text><Text style={[styles.meta, { color: colors.primary }]}>{task.plan_type === 'dictionary-review' ? 'Повторить слова →' : `${task.minutes} мин. · Открыть`}</Text></View></Pressable>)}
      <Pressable accessibilityRole="button" onPress={onOpenFeedback} style={[styles.feedbackLink, { borderColor: colors.border }]}><Text style={[styles.taskTitle, { color: colors.text }]}>Помочь улучшить beta</Text><Text style={[styles.taskCopy, { color: colors.muted }]}>Сообщить о проблеме или предложить идею</Text></Pressable>
      <Text style={[styles.boundary, { color: colors.muted }]}>План, уроки, серверная проверка и синхронизация результата доступны. Авторизованный offline-кэш пока не включён.</Text></>}
  </ScrollView>;
}
const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 }, page: { padding: 20, paddingBottom: 40, gap: 12 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { fontSize: 12, fontWeight: '900', letterSpacing: 1 }, title: { fontSize: 36, fontWeight: '900' }, link: { fontWeight: '800', paddingVertical: 10 }, greeting: { fontSize: 22, fontWeight: '800', marginTop: 10 }, sub: { fontSize: 15 },
  goal: { borderRadius: 22, padding: 20, marginVertical: 8 }, goalLabel: { color: '#fff', fontWeight: '700' }, goalValue: { color: '#fff', fontSize: 34, fontWeight: '900', marginVertical: 4 }, track: { height: 7, backgroundColor: 'rgba(255,255,255,.35)', borderRadius: 10 }, fill: { height: 7, backgroundColor: '#fff', borderRadius: 10 }, sectionTitle: { fontSize: 20, fontWeight: '800', marginTop: 6 },
  task: { flexDirection: 'row', borderWidth: 1, borderRadius: 18, padding: 16, gap: 12 }, readingLink: { flexDirection: 'row', borderWidth: 1, borderRadius: 18, padding: 16, gap: 12 }, resume: { borderWidth: 2, borderRadius: 18, padding: 16, gap: 5 }, feedbackLink: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 4, marginTop: 8 }, emoji: { fontSize: 25 }, taskBody: { flex: 1, gap: 4 }, taskTitle: { fontSize: 17, fontWeight: '800' }, taskCopy: { fontSize: 14, lineHeight: 20 }, meta: { fontSize: 13, fontWeight: '800' }, alert: { borderWidth: 1, borderRadius: 14, padding: 14 }, boundary: { fontSize: 12, lineHeight: 18, marginTop: 8 },
  profileButton: { width: 48, height: 48, borderWidth: 1, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, profileIcon: { fontSize: 22 },
});
