-- Add database-backed learning content and finish progress-table hardening.

create table if not exists public.lessons (
  id text primary key,
  title text not null,
  plan_title text not null,
  subtitle text not null,
  description text not null,
  minutes smallint not null default 5 check (minutes > 0),
  emoji text not null default '',
  theory_title text not null default '',
  theory_sections jsonb not null default '[]'::jsonb,
  position smallint not null default 0 check (position >= 0),
  is_active boolean not null default true
);

create table if not exists public.flashcards (
  id text primary key,
  polish text not null,
  translation text not null,
  example text not null default '',
  position smallint not null default 0 check (position >= 0),
  is_active boolean not null default true
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  lesson_id text not null references public.lessons (id) on delete cascade,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct smallint not null check (correct >= 0),
  explanation text not null default '',
  position smallint not null default 0 check (position >= 0),
  is_active boolean not null default true,
  unique (lesson_id, position)
);

create table if not exists public.flashcard_reviews (
  user_id uuid not null references auth.users (id) on delete cascade,
  card_id text not null,
  ease_factor double precision not null default 2.5 check (ease_factor >= 1.3),
  interval_days integer not null default 0 check (interval_days >= 0),
  repetitions integer not null default 0 check (repetitions >= 0),
  next_review_date date not null default (timezone('utc', now()))::date,
  last_reviewed_at timestamptz,
  primary key (user_id, card_id)
);

alter table public.lessons enable row level security;
alter table public.flashcards enable row level security;
alter table public.questions enable row level security;
alter table public.flashcard_reviews enable row level security;

grant select on public.lessons, public.flashcards, public.questions to anon, authenticated;
grant select, insert, update, delete on public.flashcard_reviews to authenticated;
grant select, insert, update on public.lesson_completions to authenticated;
grant usage, select on sequence public.questions_id_seq to authenticated;

drop policy if exists "Active lessons are readable" on public.lessons;
create policy "Active lessons are readable" on public.lessons for select to anon, authenticated using (is_active);
drop policy if exists "Active flashcards are readable" on public.flashcards;
create policy "Active flashcards are readable" on public.flashcards for select to anon, authenticated using (is_active);
drop policy if exists "Active questions are readable" on public.questions;
create policy "Active questions are readable" on public.questions for select to anon, authenticated using (is_active);

drop policy if exists "Users can read own flashcard reviews" on public.flashcard_reviews;
create policy "Users can read own flashcard reviews" on public.flashcard_reviews for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can insert own flashcard reviews" on public.flashcard_reviews;
create policy "Users can insert own flashcard reviews" on public.flashcard_reviews for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users can update own flashcard reviews" on public.flashcard_reviews;
create policy "Users can update own flashcard reviews" on public.flashcard_reviews for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users can delete own flashcard reviews" on public.flashcard_reviews;
create policy "Users can delete own flashcard reviews" on public.flashcard_reviews for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can update own lesson completions" on public.lesson_completions;
create policy "Users can update own lesson completions" on public.lesson_completions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users can read own lesson completions" on public.lesson_completions;
create policy "Users can read own lesson completions" on public.lesson_completions for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can insert own lesson completions" on public.lesson_completions;
create policy "Users can insert own lesson completions" on public.lesson_completions for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

insert into public.lessons (id, title, plan_title, subtitle, description, minutes, emoji, theory_title, theory_sections, position)
values
  ('words', 'Słówka dnia', 'Новые слова', '5 слов · A1', 'Выучи 5 новых слов с примерами', 5, '📚', '', '[]', 0),
  ('grammar', 'Gramatyka', 'Грамматика', 'Род существительных', 'Короткий урок о роде существительных', 8, '✏️', 'Rodzajnik i ród rzeczownika', '[["Род существительных","В польском у каждого существительного есть род: мужской, женский или средний. От рода зависит форма прилагательных и местоимений."],["Примеры","dom (дом) — мужской · kawa (кофе) — женский · miasto (город) — средний."],["Неопределённость","В польском нет артиклей «a/an/the». «A cat» — просто kot, а «the cat» — ten kot."]]', 1),
  ('review', 'Powtórka', 'Повторение', '5 карточек', 'Повтори слова, которые уже знаешь', 6, '🔄', '', '[]', 2),
  ('quiz', 'Quiz', 'Мини-тест', '5 вопросов', 'Проверь себя: перевод слов', 4, '🎯', '', '[]', 3)
on conflict (id) do update set title = excluded.title, plan_title = excluded.plan_title, subtitle = excluded.subtitle, description = excluded.description, minutes = excluded.minutes, emoji = excluded.emoji, theory_title = excluded.theory_title, theory_sections = excluded.theory_sections, position = excluded.position;

insert into public.flashcards (id, polish, translation, example, position)
values ('czesc','cześć','привет','Cześć, jak się masz?',0), ('dziekuje','dziękuję','спасибо','Dziękuję bardzo!',1), ('prosze','proszę','пожалуйста','Proszę bardzo.',2), ('tak','tak','да','Tak, zgadzam się.',3), ('nie','nie','нет','Nie, dziękuję.',4)
on conflict (id) do update set polish = excluded.polish, translation = excluded.translation, example = excluded.example, position = excluded.position;

insert into public.questions (lesson_id, prompt, options, correct, explanation, position)
values
  ('grammar','Слово «kawa» (кофе) — это род…','["мужской","женский","средний"]',1,'Kawa оканчивается на -a и относится к женскому роду.',0),
  ('grammar','Слово «dom» (дом) — это род…','["мужской","женский","средний"]',0,'Dom — существительное мужского рода.',1),
  ('grammar','Слово «miasto» (город) — это род…','["мужской","женский","средний"]',2,'Miasto — существительное среднего рода.',2),
  ('quiz','Как переводится «cześć»?','["спасибо","привет","пожалуйста","до свидания"]',1,'Cześć — неформальное «привет».',0),
  ('quiz','Что значит «dziękuję»?','["нет","да","спасибо","извините"]',2,'Dziękuję = спасибо.',1),
  ('quiz','Выберите перевод «proszę»','["пожалуйста","утро","вечер","комната"]',0,'Proszę — «пожалуйста» или «прошу».',2),
  ('quiz','Как будет «да» по-польски?','["nie","tak","dom","kawa"]',1,'Tak = да.',3),
  ('quiz','Как будет «нет» по-польски?','["tak","cześć","nie","miasto"]',2,'Nie = нет.',4)
on conflict (lesson_id, position) do update set prompt = excluded.prompt, options = excluded.options, correct = excluded.correct, explanation = excluded.explanation;
