-- Organize learning content into courses and topics, and assign vocabulary to
-- concrete lessons. Browser roles receive read-only access to active content.

create table public.courses (
  id text primary key,
  title text not null,
  description text not null default '',
  level text not null default 'A1' check (level in ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
  position smallint not null default 0 check (position >= 0),
  is_active boolean not null default true
);

create table public.topics (
  id text primary key,
  course_id text not null references public.courses (id) on delete cascade,
  title text not null,
  description text not null default '',
  emoji text not null default '',
  position smallint not null default 0 check (position >= 0),
  is_active boolean not null default true,
  unique (course_id, position)
);

alter table public.lessons
  add column topic_id text references public.topics (id) on delete set null,
  add column kind text;

update public.lessons
set kind = case id
  when 'grammar' then 'grammar'
  when 'review' then 'review'
  when 'quiz' then 'quiz'
  else 'words'
end;

alter table public.lessons
  alter column kind set not null,
  add constraint lessons_kind_check
    check (kind in ('words', 'grammar', 'review', 'quiz'));

create table public.lesson_flashcards (
  id bigint generated by default as identity primary key,
  lesson_id text not null references public.lessons (id) on delete cascade,
  flashcard_id text not null references public.flashcards (id) on delete cascade,
  position smallint not null default 0 check (position >= 0),
  unique (lesson_id, flashcard_id),
  unique (lesson_id, position)
);

create index lessons_topic_id_idx on public.lessons (topic_id);
create index topics_course_id_idx on public.topics (course_id);
create index lesson_flashcards_flashcard_id_idx
  on public.lesson_flashcards (flashcard_id);

alter table public.lesson_completions
  drop constraint lesson_completions_lesson_id_check;

alter table public.courses enable row level security;
alter table public.topics enable row level security;
alter table public.lesson_flashcards enable row level security;

grant select on public.courses, public.topics, public.lesson_flashcards
  to anon, authenticated;

create policy "Active courses are readable"
  on public.courses for select to anon, authenticated
  using (is_active);

create policy "Active topics are readable"
  on public.topics for select to anon, authenticated
  using (
    is_active and exists (
      select 1 from public.courses
      where courses.id = topics.course_id and courses.is_active
    )
  );

create policy "Active lesson vocabulary is readable"
  on public.lesson_flashcards for select to anon, authenticated
  using (
    exists (
      select 1 from public.lessons
      where lessons.id = lesson_flashcards.lesson_id and lessons.is_active
    )
    and exists (
      select 1 from public.flashcards
      where flashcards.id = lesson_flashcards.flashcard_id
        and flashcards.is_active
    )
  );

insert into public.courses (id, title, description, level, position)
values (
  'a1-foundations',
  'Польский с нуля',
  'Базовые слова и конструкции уровня A1',
  'A1',
  0
);

insert into public.topics (
  id, course_id, title, description, emoji, position
)
values (
  'first-steps',
  'a1-foundations',
  'Первые шаги',
  'Приветствия, простые ответы и основы грамматики',
  '👋',
  0
);

update public.lessons set topic_id = 'first-steps'
where id in ('words', 'grammar', 'review', 'quiz');

insert into public.lesson_flashcards (lesson_id, flashcard_id, position)
select 'words', id, (row_number() over (order by position, id) - 1)::smallint
from public.flashcards;
