insert into public.topics(id,course_id,title,description,emoji,position,is_active) values
('poland-around-us','a2-independence','Польша вокруг нас','Рассказываем о польском месте, традиции и местном событии','🇵🇱',10,true)
on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('poland-words','poland-around-us','words','Miejsca w Polsce','Регионы и места','8 карточек · A2','Назови польские места и элементы городского пейзажа',8,'🇵🇱',98,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-grammar','poland-around-us','grammar','Opowiadamy po kolei','Связный рассказ','5 заданий · A2','Связывай события в ясной последовательности',9,'✏️',99,true,'Как выстроить события по порядку','[["Начало","Najpierw вводит первое действие: Najpierw spotkaliśmy się na rynku."],["Продолжение","Potem, następnie и później показывают следующие этапы рассказа."],["Связь и завершение","Kiedy связывает события во времени, а na końcu вводит последний этап."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-review','poland-around-us','review','Tradycja i wydarzenie','Традиции и события','7 карточек · A2','Повтори лексику путешествия и местной культуры',7,'🔄',100,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-quiz','poland-around-us','quiz','Quiz: Polska wokół nas','Проверка темы','8 вопросов · A2','Проверь лексику и маркеры последовательности',6,'🎯',101,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-reading-check','poland-around-us','quiz','Czy rozumiesz wycieczkę?','Понимание текста','5 вопросов · A2','Проверь детали поездки Майи в Торунь',5,'📖',102,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('poland-region','region','регион','Każdy region Polski ma własne tradycje.',331,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-stolica','stolica','столица','Warszawa jest stolicą Polski.',332,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-zabytek','zabytek','памятник истории; достопримечательность','Na rynku stoi znany zabytek.',333,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-rynek','rynek','главная площадь','Spotkamy się na rynku o południu.',334,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-muzeum','muzeum','музей','W muzeum poznaliśmy historię miasta.',335,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-krajobraz','krajobraz','пейзаж','Górski krajobraz zachwycił turystów.',336,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-wybrzeze','wybrzeże','побережье','Latem jedziemy nad polskie wybrzeże.',337,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-gory','góry','горы','Zimą wielu ludzi odpoczywa w górach.',338,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-tradycja','tradycja','традиция','Ta tradycja łączy całą rodzinę.',339,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-swietowac','świętować','праздновать','Mieszkańcy wspólnie świętują dzień miasta.',340,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-odbywac','odbywać się','проходить; состояться','Festiwal odbywa się w czerwcu.',341,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-zwiedzac','zwiedzać','осматривать достопримечательности','Rano zwiedzaliśmy stare miasto.',342,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-podroz','podróż','путешествие','Podróż pociągiem trwała trzy godziny.',343,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-mieszkaniec','mieszkaniec','житель','Mieszkaniec polecił nam lokalną kawiarnię.',344,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('poland-lokalny','lokalny','местный','Spróbowaliśmy lokalnego dania.',345,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('poland-words','poland-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('poland-words','poland-region',0),('poland-words','poland-stolica',1),('poland-words','poland-zabytek',2),('poland-words','poland-rynek',3),('poland-words','poland-muzeum',4),('poland-words','poland-krajobraz',5),('poland-words','poland-wybrzeze',6),('poland-words','poland-gory',7),
('poland-review','poland-tradycja',0),('poland-review','poland-swietowac',1),('poland-review','poland-odbywac',2),('poland-review','poland-zwiedzac',3),('poland-review','poland-podroz',4),('poland-review','poland-mieszkaniec',5),('poland-review','poland-lokalny',6);

delete from public.questions where lesson_id in ('poland-grammar','poland-quiz','poland-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('poland-grammar','Что лучше начинает связный рассказ о поездке?','["Najpierw pojechaliśmy do Gdańska.","Na końcu pojechaliśmy najpierw.","Potem przed początkiem Gdańsk."]',0,'Najpierw вводит первое событие рассказа.',0),
('poland-grammar','Najpierw zwiedziliśmy muzeum, ___ poszliśmy na rynek.','["potem","ponieważ","ale najpierw"]',0,'Potem показывает следующее действие в хронологической последовательности.',1),
('poland-grammar','___ kupiliśmy bilety, weszliśmy do muzeum.','["Kiedy","Na końcu","Dlatego"]',0,'Kiedy связывает действие или момент с последующим событием.',2),
('poland-grammar','Составьте: Сначала мы осмотрели замок, а затем пошли на рынок.','["Najpierw zwiedziliśmy zamek, a następnie poszliśmy na rynek.","Następnie najpierw zamek poszliśmy rynek.","Zwiedzaliśmy na końcu, ponieważ rynek."]',0,'Najpierw …, a następnie … ясно передаёт порядок двух действий.',3),
('poland-grammar','Как естественно завершить рассказ?','["Na końcu wróciliśmy pociągiem do domu.","Najpierw na końcu wracamy wczoraj.","Kiedy koniec, dlatego pociąg."]',0,'Na końcu вводит последнее событие и завершает последовательность.',4),
('poland-quiz','Что означает zabytek?','["исторический памятник","расписание","побережье"]',0,'Zabytek — исторически или культурно ценный объект.',0),
('poland-quiz','Gdzie leży Gdańsk?','["nad polskim wybrzeżem","w Tatrach","na południe od Krakowa"]',0,'Гданьск расположен на балтийском побережье Польши.',1),
('poland-quiz','Festiwal ___ w czerwcu.','["odbywa się","zwiedza","podróżuje się region"]',0,'О событии говорят: festiwal odbywa się — фестиваль проходит.',2),
('poland-quiz','Как сказать «местные жители»?','["lokalni mieszkańcy","stoliczne zabytki","górskie podróże"]',0,'Lokalni mieszkańcy — жители конкретного места.',3),
('poland-quiz','Najpierw byliśmy w muzeum, a ___ zjedliśmy obiad.','["później","zanim najpierw","dlatego że koniec"]',0,'Później продолжает хронологический рассказ.',4),
('poland-quiz','Что можно zwiedzać?','["stare miasto","tradycję wczoraj","podróż pociągiem jako czas"]',0,'Zwiedzać можно город, музей, замок и другие места.',5),
('poland-quiz','Выберите естественное описание Польши.','["Na północy jest morze, a na południu są góry.","Morze jest pod górami w stolicy.","Region świętuje pociągiem krajobraz."]',0,'Польское побережье находится на севере, а горные районы — на юге.',6),
('poland-quiz','Как завершить рассказ о празднике?','["Na końcu wszyscy obejrzeli koncert.","Najpierw koniec ogląda koncert.","Kiedy wszyscy, potem ponieważ."]',0,'Na końcu естественно вводит заключительное событие.',7),
('poland-reading-check','Dokąd pojechała grupa Mai?','["Do Torunia","Do Zakopanego","Do Gdańska"]',0,'Группа Майи отправилась на однодневную поездку в Торунь.',0),
('poland-reading-check','Co grupa zrobiła najpierw?','["Spotkała się z przewodniczką na rynku","Kupiła pierniki na dworcu","Wróciła do szkoły"]',0,'Первым событием была встреча с экскурсоводом на площади.',1),
('poland-reading-check','Czego uczniowie dowiedzieli się w muzeum?','["Jak dawniej przygotowywano pierniki","Jak buduje się statki","Jak chodzić po górach"]',0,'В музее они узнали о старом способе приготовления пряников.',2),
('poland-reading-check','Dlaczego na rynku było dużo ludzi?','["Odbywał się lokalny festiwal","Przyjechał pociąg","Muzeum było zamknięte"]',0,'На площади проходил местный фестиваль.',3),
('poland-reading-check','Co Maja zapamiętała z wyjazdu?','["Historię miasta i atmosferę festiwalu","Tylko czas podróży","Adres szkolnej biblioteki"]',0,'Майе запомнились история Торуни и атмосфера местного события.',4);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('poland-maja-odkrywa-torun','poland-around-us','Maja odkrywa Toruń','Однодневная поездка, история города и местный праздник','A2',6,'🇵🇱',
'["W sobotę Maja pojechała z grupą językową na jednodniową wycieczkę do Torunia. Najpierw spotkali się z przewodniczką na rynku. Pokazała im stare kamienice, ratusz i pomnik Mikołaja Kopernika. Opowiedziała też krótko o historii miasta.","Następnie grupa zwiedziła muzeum piernika. Uczniowie dowiedzieli się, jak dawniej przygotowywano ciasto, a potem sami zrobili małe pierniki. Kiedy wyszli z muzeum, na rynku było już dużo ludzi, ponieważ odbywał się tam lokalny festiwal.","Później Maja spróbowała regionalnego dania i rozmawiała z mieszkańcami. Na końcu wszyscy obejrzeli koncert i wrócili pociągiem do domu. Maja była zmęczona, ale z wyjazdu zapamiętała ciekawą historię Torunia i przyjazną atmosferę festiwalu."]',
'{"jednodniową":{"lemma":"jednodniowy","translation":"однодневный","part_of_speech":"прилагательное"},"przewodniczką":{"lemma":"przewodniczka","translation":"экскурсовод","part_of_speech":"существительное"},"kamienice":{"lemma":"kamienica","translation":"старинный городской дом","part_of_speech":"существительное"},"ratusz":{"lemma":"ratusz","translation":"ратуша","part_of_speech":"существительное"},"piernika":{"lemma":"piernik","translation":"пряник","part_of_speech":"существительное"},"dowiedzieli":{"lemma":"dowiedzieć się","translation":"узнать","part_of_speech":"глагол"},"dawniej":{"lemma":"dawniej","translation":"раньше; в прошлом","part_of_speech":"наречие"},"odbywał":{"lemma":"odbywać się","translation":"проходить","part_of_speech":"глагол"},"regionalnego":{"lemma":"regionalny","translation":"региональный","part_of_speech":"прилагательное"},"mieszkańcami":{"lemma":"mieszkaniec","translation":"житель","part_of_speech":"существительное"},"zmęczona":{"lemma":"zmęczony","translation":"уставший","part_of_speech":"прилагательное"},"atmosferę":{"lemma":"atmosfera","translation":"атмосфера","part_of_speech":"существительное"}}',
'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29","comprehension_lesson_id":"poland-reading-check"}',22,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
