-- Keep the final B2 editorial pass rerunnable and content-only.
update public.questions as q
set explanation = v.explanation
from (values
  ('b2discussion-grammar', 0, 'Formuła „jeśli dobrze rozumiem” neutralnie sprawdza trafność parafrazy i pozwala rozmówcy ją skorygować.'),
  ('b2discussion-grammar', 1, 'Konstrukcja „z jednej strony…, z drugiej strony…” porządkuje i równoważy dwa odmienne aspekty argumentu.'),
  ('b2discussion-grammar', 2, 'Czasownik „wrócić” łączy się z przyimkiem „do” i dopełniaczem, dlatego mówimy „do kwestii”.'),
  ('b2discussion-grammar', 3, 'Imiesłów „podsumowując” wprowadza zwięzły wniosek, a spójnik „lecz” zachowuje wskazane rozbieżności.'),
  ('b2discussion-grammar', 4, 'Po czasowniku „proponować” naturalnie występuje bezokolicznik, a formuła wstępna łagodzi sprawdzanie intencji.'),
  ('b2discussion-grammar', 5, 'Zwrot „zgadzać się co do” wymaga dopełniacza, natomiast „ale” wyraźnie zachowuje kontrast.'),
  ('b2discussion-quiz', 0, 'Zwrot „oddać głos” oznacza przekazać kolej wypowiedzi konkretnej osobie uczestniczącej w dyskusji.'),
  ('b2discussion-quiz', 1, 'Formuła „jeśli dobrze rozumiem” sprawdza cudzą intencję bez narzucania rozmówcy własnej interpretacji.'),
  ('b2discussion-quiz', 2, '„Punkt sporny” nazywa kwestię, w której uczestnicy nadal prezentują odmienne stanowiska.'),
  ('b2discussion-quiz', 3, 'Zwrot „wróćmy do pytania” uprzejmie kieruje rozmowę na wcześniejszy temat bez oceniania uczestnika.'),
  ('b2discussion-quiz', 4, 'Moderator parafrazuje wypowiedź, aby sprawdzić jej sens i uczynić stanowisko zrozumiałym dla wszystkich.'),
  ('b2discussion-quiz', 5, 'Para „z jednej strony…, z drugiej strony…” służy uporządkowanemu zestawieniu dwóch aspektów sprawy.'),
  ('b2discussion-quiz', 6, 'Rzetelne podsumowanie osobno wskazuje osiągnięte porozumienie oraz kwestie, które nadal pozostają sporne.'),
  ('b2discussion-quiz', 7, 'Zwrot „dojść do głosu” oznacza otrzymać realną możliwość przedstawienia swojej wypowiedzi podczas rozmowy.'),
  ('b2discussion-quiz', 8, 'Moderator przerywa wypowiedź ze względów proceduralnych, gdy narusza ona temat albo ustalony czas.'),
  ('b2discussion-quiz', 9, '„Osiągnąć porozumienie” znaczy wspólnie wypracować rozwiązanie możliwe do zaakceptowania przez uczestników.'),
  ('b2discussion-reading-check', 0, 'Celem spotkania było rozpoznanie potrzeb mieszkańców przed podjęciem decyzji, a nie natychmiastowe głosowanie.'),
  ('b2discussion-reading-check', 1, 'Moderatorka ujęła stanowiska jako potrzebę dostępności oraz pytanie o warunki bezpiecznej realizacji.'),
  ('b2discussion-reading-check', 2, 'Moderatorka przerwała wątek, ponieważ odszedł od ustalonego tematu godzin pracy biblioteki.'),
  ('b2discussion-reading-check', 3, 'Seniorka połączyła dostępność biblioteki z bezpiecznym powrotem, rozszerzając perspektywę całej dyskusji.'),
  ('b2discussion-reading-check', 4, 'Uczestnicy uzgodnili trzymiesięczny pilotaż obejmujący dwa wieczory w każdym tygodniu.'),
  ('b2discussion-reading-check', 5, 'W podsumowaniu jako nierozstrzygnięte wskazano źródło finansowania oraz dokładne godziny otwarcia.'),
  ('b2intercultural-grammar', 0, 'Formuła „mam wrażenie, że” przedstawia obserwację jako osobistą i ogranicza siłę uogólnienia.'),
  ('b2intercultural-grammar', 1, 'Stały zwrot „mieć na myśli” oznacza zamierzony sens wypowiedzi i wymaga formy „masz”.'),
  ('b2intercultural-grammar', 2, 'Ta formuła uznaje niezamierzony skutek słów, a następnie precyzyjnie wyjaśnia pierwotną intencję.'),
  ('b2intercultural-grammar', 3, 'Spójnik „zanim” wprowadza czynność wcześniejszą, więc najpierw pytamy, a dopiero potem interpretujemy.'),
  ('b2intercultural-grammar', 4, 'Konstrukcja „lepiej…, niż…” porównuje rozwiązania i wskazuje doprecyzowanie jako rozsądniejszy wybór.'),
  ('b2intercultural-grammar', 5, 'Pytanie „czy dobrze rozumiem, że…” neutralnie sprawdza interpretację przed sformułowaniem oceny.'),
  ('b2intercultural-quiz', 0, '„Norma komunikacyjna” to przyjęty w danym kontekście sposób prowadzenia rozmowy i wyrażania intencji.'),
  ('b2intercultural-quiz', 1, '„Nieporozumienie” oznacza sytuację, w której rozmówcy odmiennie rozumieją przekazaną wiadomość lub zachowanie.'),
  ('b2intercultural-quiz', 2, '„Intencja” nazywa zamiar mówiącego, który może różnić się od rzeczywistego efektu wypowiedzi.'),
  ('b2intercultural-quiz', 3, '„Interpretować” znaczy nadawać znaczenie wypowiedzi, zachowaniu albo sytuacji na podstawie dostępnych wskazówek.'),
  ('b2intercultural-quiz', 4, '„Uogólnienie” przypisuje cechę szerszej grupie, choć pojedyncza obserwacja nie musi jej potwierdzać.'),
  ('b2intercultural-quiz', 5, '„Stereotyp” jest uproszczonym przekonaniem o grupie, które pomija różnice między konkretnymi osobami.'),
  ('b2intercultural-quiz', 6, '„Bezpośredni” opisuje styl, w którym zamiar lub oczekiwanie zostaje wyrażone jasno i wprost.'),
  ('b2intercultural-quiz', 7, '„Pośredni” określa styl przekazywania sensu przez sugestię, kontekst albo łagodniejszą formułę.'),
  ('b2intercultural-quiz', 8, '„Doprecyzować” znaczy uzupełnić wypowiedź tak, aby jej znaczenie stało się dokładniejsze i jednoznaczne.'),
  ('b2intercultural-quiz', 9, 'Zwrot „odczytać ton” oznacza rozpoznać emocjonalny sposób, w jaki została sformułowana wiadomość.'),
  ('b2intercultural-reading-check', 0, 'Lenę uraziła interpretacja krótkiej wiadomości jako chłodnej oceny jej przygotowanej pracy.'),
  ('b2intercultural-reading-check', 1, 'Marek świadomie mówił o własnym doświadczeniu, unikając nieuprawnionego uogólnienia na całą grupę.'),
  ('b2intercultural-reading-check', 2, 'Szkolenie pokazało, że zachowanie zależy również od wieku, roli, branży oraz konkretnej sytuacji.'),
  ('b2intercultural-reading-check', 3, 'Zespół postanowił dodawać do pilnych krótkich wiadomości kontekst, termin oraz krótkie podziękowanie.'),
  ('b2intercultural-reading-check', 4, 'Zasada „najpierw pytamy, potem interpretujemy” nakazuje sprawdzić intencję przed ocenieniem zachowania.'),
  ('b2intercultural-reading-check', 5, 'Zespół dostosował wspólne normy komunikacji, lecz nie próbował usuwać indywidualnych różnic uczestników.')
) as v(lesson_id, position, explanation)
where q.lesson_id = v.lesson_id
  and q.position = v.position;
