-- Third original A2 topic. Existing public-content RLS and grants apply unchanged.
insert into public.topics(id,course_id,title,description,emoji,position,is_active) values
('housing-services','a2-independence','Жильё и услуги','Обсуждаем аренду и договариваемся о бытовом ремонте','🔧',2,true)
on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,theory_title,theory_sections,source_metadata,position,is_active) values
('housing-words','housing-services','words','Mieszkanie do wynajęcia','Аренда жилья','8 карточек · A2','Обсуди квартиру, договор и условия оплаты',7,'🏠','','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}',58,true),
('housing-grammar','housing-services','grammar','Nie ma ogrzewania','Проблема в квартире','5 заданий · A2','Используй родительный и творительный падежи',9,'✏️','Nie ma wody, problem z ogrzewaniem','[["Родительный после отрицания","После nie ma: nie ma prądu, ciepłej wody, ogrzewania."],["Глагольное управление","Szukać и potrzebować требуют родительного: szukam mieszkania, potrzebuję hydraulika."],["Творительный после z","Когда z означает «с»: problem z ogrzewaniem, rozmowa z właścicielem."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}',59,true),
('housing-review','housing-services','review','Zgłaszam usterkę','Ремонт и услуги','7 карточек · A2','Сообщи о проблеме и назначь время ремонта',7,'🔄','','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}',60,true),
('housing-quiz','housing-services','quiz','Quiz: mieszkanie','Проверка темы','8 вопросов · A2','Проверь лексику аренды и падежное управление',6,'🎯','','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}',61,true),
('housing-reading-check','housing-services','quiz','Czy rozumiesz zgłoszenie?','Понимание текста','5 вопросов · A2','Проверь детали обращения Лены',5,'📖','','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}',62,true)
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('housing-mieszkanie','mieszkanie','квартира','Szukamy mieszkania blisko centrum.',211,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-wynajmowac','wynajmować','снимать; сдавать','Chcemy wynajmować to mieszkanie przez rok.',212,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-czynsz','czynsz','арендная плата','Czynsz wynosi trzy tysiące złotych.',213,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-kaucja','kaucja','залог','Właściciel prosi o miesięczną kaucję.',214,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-umowa','umowa','договор','Przeczytam umowę przed podpisaniem.',215,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-wlasciciel','właściciel','владелец','Właściciel mieszkania mieszka za granicą.',216,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-ogrzewanie','ogrzewanie','отопление','Ogrzewanie nie działa od rana.',217,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-usterka','usterka','неисправность','Zgłosiłam usterkę administracji.',218,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-naprawa','naprawa','ремонт; починка','Naprawa potrwa około godziny.',219,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-hydraulik','hydraulik','сантехник','Hydraulik sprawdzi kran w kuchni.',220,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-prad','prąd','электричество','W łazience nie ma prądu.',221,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-woda','ciepła woda','горячая вода','Od wczoraj nie ma ciepłej wody.',222,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-zglaszac','zgłaszać','сообщать; заявлять','Proszę zgłaszać problemy telefonicznie.',223,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-administracja','administracja','управляющая компания','Administracja odpowie jutro rano.',224,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}'),
('housing-termin','termin','срок; назначенное время','Ustaliliśmy termin naprawy na wtorek.',225,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('housing-words','housing-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('housing-words','housing-mieszkanie',0),('housing-words','housing-wynajmowac',1),('housing-words','housing-czynsz',2),('housing-words','housing-kaucja',3),('housing-words','housing-umowa',4),('housing-words','housing-wlasciciel',5),('housing-words','housing-ogrzewanie',6),('housing-words','housing-usterka',7),
('housing-review','housing-naprawa',0),('housing-review','housing-hydraulik',1),('housing-review','housing-prad',2),('housing-review','housing-woda',3),('housing-review','housing-zglaszac',4),('housing-review','housing-administracja',5),('housing-review','housing-termin',6);

delete from public.questions where lesson_id in ('housing-grammar','housing-quiz','housing-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('housing-grammar','W mieszkaniu nie ma ___.','["ciepła woda","ciepłej wody","ciepłą wodą"]',1,'После nie ma употребляется родительный падеж: ciepłej wody.',0),
('housing-grammar','Szukamy małego ___.','["mieszkanie","mieszkaniem","mieszkania"]',2,'Глагол szukać требует родительного падежа: szukamy mieszkania.',1),
('housing-grammar','Mamy problem z ___.','["ogrzewaniem","ogrzewania","ogrzewanie"]',0,'После z в значении «с чем?» нужен творительный падеж: z ogrzewaniem.',2),
('housing-grammar','Разговариваю с владельцем.','["Rozmawiam z właścicielem.","Rozmawiam z właściciela.","Rozmawiam właściciel."]',0,'После z в значении совместности употребляется творительный: z właścicielem.',3),
('housing-grammar','Potrzebujemy ___.','["hydraulik","hydraulika","hydraulikiem"]',1,'Potrzebować требует родительного падежа: potrzebujemy hydraulika.',4),
('housing-quiz','Что означает kaucja?','["отопление","залог","счётчик"]',1,'Kaucja — залог, который обычно возвращают после окончания аренды.',0),
('housing-quiz','Nie ma ___.','["prądu","prądem","prąd"]',0,'Отрицательная конструкция nie ma требует родительного: prądu.',1),
('housing-quiz','Problem z ___.','["kran","kranu","kranem"]',2,'После z в конструкции problem z нужен творительный: kranem.',2),
('housing-quiz','Куда сообщить о неисправности?','["Zgłosić usterkę administracji.","Wynająć hydraulika umową.","Szukać czynsz z wodą."]',0,'Zgłosić usterkę administracji — сообщить управляющей компании о неисправности.',3),
('housing-quiz','Szukamy ___.','["nowego mieszkania","nowym mieszkaniem","nowe mieszkanie"]',0,'Szukać управляет родительным падежом: nowego mieszkania.',4),
('housing-quiz','Rozmawiam z ___.','["hydraulika","hydraulikiem","hydraulik"]',1,'Лицо после z ставится в творительном падеже: z hydraulikiem.',5),
('housing-quiz','Что обычно подписывают при аренде?','["usterkę","umowę","ogrzewanie"]',1,'При аренде стороны подписывают umowę — договор.',6),
('housing-quiz','Ustaliliśmy ___ naprawy.','["termin","czynszem","kaucji nie ma"]',0,'Ustalić termin naprawy — назначить время ремонта.',7),
('housing-reading-check','Jaki problem zauważyła Lena?','["Nie działało ogrzewanie","Zgubiła umowę","Nie miała kluczy"]',0,'Утром Лена заметила, что отопление не работает.',0),
('housing-reading-check','Do kogo Lena najpierw zadzwoniła?','["Do koleżanki","Do właściciela","Do hydraulika"]',1,'Сначала она позвонила владельцу квартиры.',1),
('housing-reading-check','Dlaczego właściciel poprosił o wiadomość?','["Potrzebował opisu usterki","Chciał podnieść czynsz","Szukał nowego mieszkania"]',0,'Ему нужны были описание проблемы и фотография счётчика.',2),
('housing-reading-check','Kiedy fachowiec ma przyjść?','["W poniedziałek rano","We wtorek między 16 a 18","W niedzielę wieczorem"]',1,'Администрация назначила визит на вторник с 16 до 18.',3),
('housing-reading-check','Co Lena zrobi, jeśli naprawa się opóźni?','["Wyprowadzi się natychmiast","Podpisze nową umowę","Ponownie skontaktuje się z administracją"]',2,'Если специалист не придёт вовремя, она снова свяжется с администрацией.',4);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('usterka-w-mieszkaniu','housing-services','Usterka w mieszkaniu','Лена договаривается о ремонте отопления','A2',5,'🔧','["Lena wynajmuje małe mieszkanie w Poznaniu. W poniedziałek rano zauważyła, że ogrzewanie nie działa, a w sypialni jest bardzo zimno. Najpierw zadzwoniła do właściciela. Powiedziała, że od wieczora nie ma ciepłych kaloryferów i potrzebuje szybkiej pomocy.","Właściciel poprosił Lenę o krótką wiadomość z opisem usterki i zdjęciem licznika. Potem zgłosił problem administracji. Po godzinie administracja odpowiedziała, że fachowiec może przyjść we wtorek między szesnastą a osiemnastą. Lena potwierdziła termin i zapytała, czy naprawa będzie płatna.","Zgodnie z umową właściciel zapłaci za naprawę ogrzewania. Lena będzie rozmawiać z fachowcem i pokaże mu kaloryfer w sypialni. Jeśli fachowiec się spóźni, ponownie skontaktuje się z administracją. Lena ma nadzieję, że wieczorem mieszkanie znów będzie ciepłe."]','{"wynajmuje":{"lemma":"wynajmować","translation":"снимать","part_of_speech":"глагол"},"zauważyła":{"lemma":"zauważyć","translation":"заметить","part_of_speech":"глагол"},"ogrzewanie":{"lemma":"ogrzewanie","translation":"отопление","part_of_speech":"существительное"},"kaloryferów":{"lemma":"kaloryfer","translation":"радиатор","part_of_speech":"существительное"},"usterki":{"lemma":"usterka","translation":"неисправность","part_of_speech":"существительное"},"licznika":{"lemma":"licznik","translation":"счётчик","part_of_speech":"существительное"},"fachowiec":{"lemma":"fachowiec","translation":"специалист","part_of_speech":"существительное"},"potwierdziła":{"lemma":"potwierdzić","translation":"подтвердить","part_of_speech":"глагол"},"płatna":{"lemma":"płatny","translation":"платный","part_of_speech":"прилагательное"},"zgodnie":{"lemma":"zgodnie z","translation":"согласно","part_of_speech":"выражение"},"spóźni":{"lemma":"spóźnić się","translation":"опоздать","part_of_speech":"глагол"},"ponownie":{"lemma":"ponownie","translation":"повторно","part_of_speech":"наречие"}}','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-28","comprehension_lesson_id":"housing-reading-check"}',14,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
