insert into public.topics(id,course_id,title,description,emoji,position,is_active) values ('b1-culture','b1-independent','Культура','Рассказываем о книге, фильме и событии и обосновываем оценку','🎭',7,true) on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('b1culture-words','b1-culture','words','Książka, film i scena','Произведение и событие','8 карточек · B1','Назови элементы книги, фильма и культурного события',9,'🎭',143,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-grammar','b1-culture','grammar','Dzieło, które porusza','Оценка и описание','6 заданий · B1','Соединяй оценочную лексику с относительными местоимениями',12,'✏️',144,true,'Оценочная лексика и относительные местоимения','[["Оценка","Poruszający, przekonujący и wielowątkowy называют конкретное качество; оценку лучше подкреплять примером."],["Który","Местоимение который согласуется с существительным в роде и числе, но падеж зависит от его роли в придаточном."],["Формы","Który/która — подлежащее, którego/której — принадлежность или дополнение, w którym/w której — место."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-review','b1-culture','review','Moja opinia','Аргументированная оценка','7 карточек · B1','Опиши впечатление и объясни свою оценку',8,'🔄',145,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-quiz','b1-culture','quiz','Quiz: kultura','Проверка темы','10 вопросов · B1','Проверь лексику и формы относительных местоимений',9,'🎯',146,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-reading-check','b1-culture','quiz','Książka czy ekranizacja?','Понимание текста','6 вопросов · B1','Сравни произведения и найди вывод героини',7,'📖',147,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('b1culture-powiesc','powieść','роман','Ta powieść opowiada o przyjaźni w trudnych czasach.',467,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-ekranizacja','ekranizacja','экранизация','Ekranizacja różni się od książkowego oryginału.',468,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-fabula','fabuła','сюжет','Fabuła rozwija się powoli, ale logicznie.',469,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-bohater','bohater','герой; персонаж','Główny bohater podejmuje trudną decyzję.',470,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-przedstawienie','przedstawienie','спектакль','Przedstawienie trwało prawie dwie godziny.',471,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-wystawa','wystawa','выставка','Wystawa pokazuje fotografie współczesnego miasta.',472,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-recenzja','recenzja','рецензия','Po seansie przeczytałam krótką recenzję.',473,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-tworca','twórca','создатель; автор','Twórca filmu rozmawiał z publicznością.',474,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-poruszajacy','poruszający','трогательный','Najbardziej poruszająca była ostatnia scena.',475,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-przekonujacy','przekonujący','убедительный','Aktor stworzył przekonującą postać.',476,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-wielowatkowy','wielowątkowy','многосюжетный','Wielowątkowa opowieść wymaga uwagi.',477,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-scenografia','scenografia','сценография','Prosta scenografia dobrze budowała nastrój.',478,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-publicznosc','publiczność','публика','Publiczność długo rozmawiała po spotkaniu.',479,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-wywierac-wrazenie','wywierać wrażenie','производить впечатление','Muzyka wywiera mocne wrażenie.',480,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1culture-skłaniac','skłaniać do refleksji','побуждать к размышлению','Zakończenie skłania do refleksji nad odpowiedzialnością.',481,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('b1culture-words','b1culture-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values ('b1culture-words','b1culture-powiesc',0),('b1culture-words','b1culture-ekranizacja',1),('b1culture-words','b1culture-fabula',2),('b1culture-words','b1culture-bohater',3),('b1culture-words','b1culture-przedstawienie',4),('b1culture-words','b1culture-wystawa',5),('b1culture-words','b1culture-recenzja',6),('b1culture-words','b1culture-tworca',7),('b1culture-review','b1culture-poruszajacy',0),('b1culture-review','b1culture-przekonujacy',1),('b1culture-review','b1culture-wielowatkowy',2),('b1culture-review','b1culture-scenografia',3),('b1culture-review','b1culture-publicznosc',4),('b1culture-review','b1culture-wywierac-wrazenie',5),('b1culture-review','b1culture-skłaniac',6);

delete from public.questions where lesson_id in ('b1culture-grammar','b1culture-quiz','b1culture-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('b1culture-grammar','To film, ___ bohater wraca po latach do rodzinnego miasta.','["w którym","którego","któremu"]',0,'После w filmie относительное местоимение принимает форму w którym.',0),
('b1culture-grammar','Poznałam reżyserkę, ___ film zdobył nagrodę.','["której","którą","któremu"]',0,'Форма której выражает принадлежность: фильм этой режиссёрки.',1),
('b1culture-grammar','Aktor, ___ publiczność nagrodziła brawami, zagrał bardzo naturalnie.','["którego","który","któremu"]',0,'Глагол nagrodzić требует винительного падежа; для лица мужского рода — którego.',2),
('b1culture-grammar','Książka była ___: długo myślałem o decyzji bohatera.','["poruszająca","poruszona","poruszająco"]',0,'Poruszająca согласуется с существительным książka и оценивает произведение.',3),
('b1culture-grammar','Составьте: Это выставка, которая побуждает публику к размышлению.','["To wystawa, która skłania publiczność do refleksji.","To wystawa, której skłania publicznością refleksję.","To wystawa, który publiczność skłania do refleksją."]',0,'Która согласуется с wystawa; skłaniać kogoś do czegoś требует винительного и родительного падежей.',4),
('b1culture-grammar','Составьте: Мне понравился фильм, в котором музыка создавала тревожное настроение.','["Spodobał mi się film, w którym muzyka budowała niepokojący nastrój.","Podobałem film, którego muzyka budowała niepokojącego nastrój.","Spodobał mnie się film, który muzyką budował nastrój."]',0,'Безличное spodobał mi się требует дательного; место действия выражено w którym.',5),
('b1culture-quiz','Что означает ekranizacja?','["фильм по мотивам литературного произведения","театральная декорация","критическая статья"]',0,'Ekranizacja переносит литературное произведение на экран.',0),
('b1culture-quiz','Które słowo opisuje wydarzenia utworu?','["fabuła","publiczność","scenografia"]',0,'Fabuła — последовательность событий произведения.',1),
('b1culture-quiz','To autorka, ___ powieść właśnie przeczytałem.','["której","którą","która"]',0,'Której выражает принадлежность: роман этой авторки.',2),
('b1culture-quiz','Spektakl, ___ widzieliśmy wczoraj, był bardzo poruszający.','["który","którego","któremu"]',0,'Неодушевлённое существительное мужского рода в винительном имеет форму który.',3),
('b1culture-quiz','Jak pozytywnie ocenić grę aktora?','["Stworzył przekonującą i naturalną postać.","Fabuła siedziała na widowni.","Recenzja zagrała bohatera."]',0,'Первый вариант естественно оценивает актёрскую работу.',4),
('b1culture-quiz','Prosta ___ pomogła zbudować nastrój przedstawienia.','["scenografia","publiczność","powieść"]',0,'Scenografia — визуальное оформление сцены.',5),
('b1culture-quiz','Выберите естественное сочетание.','["skłaniać do refleksji","wywierać publicznością","oglądać wrażeniem"]',0,'Skłaniać do refleksji — побуждать к размышлению.',6),
('b1culture-quiz','Film był wielowątkowy, czyli ___.','["rozwijał kilka powiązanych historii","trwał tylko minutę","nie miał bohaterów"]',0,'Wielowątkowy значит состоящий из нескольких сюжетных линий.',7),
('b1culture-quiz','Muzeum, ___ odbywa się wystawa, mieści się w centrum.','["w którym","którego","któremu"]',0,'Место выражается конструкцией w którym.',8),
('b1culture-quiz','Która opinia jest uzasadniona?','["Film wywarł na mnie wrażenie, ponieważ obraz i muzyka tworzyły spójną całość.","Film był dobry, bo tak.","Każda ekranizacja jest lepsza od książki."]',0,'Первый вариант содержит конкретную оценку и её обоснование.',9),
('b1culture-reading-check','Dlaczego Ola wybrała się na wydarzenie?','["Chciała porównać książkę z ekranizacją","Musiała napisać szkolny egzamin","Szukała nowego mieszkania"]',0,'Она прочитала роман и хотела увидеть его экранизацию.',0),
('b1culture-reading-check','Co pokazano przed filmem?','["Wystawę szkiców i zdjęć ze scenografii","Koncert muzyki ludowej","Kurs fotografii"]',0,'Перед сеансом можно было увидеть материалы о создании сценографии.',1),
('b1culture-reading-check','Co Ola oceniła pozytywnie?','["Przekonującą grę głównej aktorki","Brak związku z książką","Puste spotkanie bez twórców"]',0,'Ей особенно понравилась убедительная игра актрисы.',2),
('b1culture-reading-check','Czym film różnił się od powieści?','["Łączył kilka postaci i skracał wątki","Dodawał wszystkie szczegóły książki","Nie miał muzyki ani obrazu"]',0,'Экранизация объединила персонажей и сократила некоторые линии.',3),
('b1culture-reading-check','Co wydarzyło się po seansie?','["Publiczność rozmawiała z reżyserką","Kino zostało natychmiast zamknięte","Ola oddała książkę autorowi"]',0,'После фильма состоялась встреча с режиссёркой.',4),
('b1culture-reading-check','Jaki wniosek wyciągnęła Ola?','["Książka i film mogą inaczej opowiadać tę samą historię","Ekranizacja zawsze powinna kopiować każde zdanie","Recenzje są ważniejsze niż własna opinia"]',0,'Главный вывод касается разных средств литературы и кино.',5);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('b1culture-wieczor-z-ksiazka-i-filmem','b1-culture','Wieczór z książką i filmem','Как сравнить роман, экранизацию и культурное событие','B1',9,'🎭','["Ola niedawno przeczytała powieść o rodzeństwie, które po latach wraca do rodzinnego domu. Kiedy lokalne kino zapowiedziało pokaz ekranizacji i spotkanie z reżyserką, od razu kupiła bilet. Chciała sprawdzić, czy film zachował spokojny nastrój i wielowątkową fabułę książki.","Przed seansem publiczność mogła obejrzeć małą wystawę szkiców kostiumów oraz zdjęć miejsc, w których powstawał film. Olę zainteresowała zwłaszcza prosta scenografia domu. Dzięki światłu i starym przedmiotom wywierała mocne wrażenie, chociaż nie kopiowała dokładnie opisów z powieści.","Film skracał niektóre wątki i łączył kilka drugoplanowych postaci. Mimo to główna aktorka, której grę Ola uznała za przekonującą, dobrze pokazała zmianę bohaterki. Szczególnie poruszająca była scena bez dialogu, w której muzyka i obraz zastąpiły długi książkowy opis.","Po seansie reżyserka odpowiadała na pytania publiczności. Wyjaśniła, że ekranizacja nie musi powtarzać każdego zdania, lecz powinna zachować najważniejszy konflikt i emocje. Spotkanie skłoniło Olę do refleksji: książka i film opowiadają tę samą historię innymi środkami, dlatego warto oceniać każde dzieło osobno."]','{"rodzeństwie":{"lemma":"rodzeństwo","translation":"братья и сёстры","part_of_speech":"существительное"},"zapowiedziało":{"lemma":"zapowiedzieć","translation":"объявить","part_of_speech":"глагол"},"zachował":{"lemma":"zachować","translation":"сохранить","part_of_speech":"глагол"},"seansem":{"lemma":"seans","translation":"сеанс","part_of_speech":"существительное"},"szkiców":{"lemma":"szkic","translation":"эскиз","part_of_speech":"существительное"},"kostiumów":{"lemma":"kostium","translation":"костюм","part_of_speech":"существительное"},"powstawał":{"lemma":"powstawać","translation":"создаваться","part_of_speech":"глагол"},"zwłaszcza":{"lemma":"zwłaszcza","translation":"особенно","part_of_speech":"наречие"},"wywierała":{"lemma":"wywierać","translation":"производить","part_of_speech":"глагол"},"drugoplanowych":{"lemma":"drugoplanowy","translation":"второстепенный","part_of_speech":"прилагательное"},"uznała":{"lemma":"uznać","translation":"счесть","part_of_speech":"глагол"},"zastąpiły":{"lemma":"zastąpić","translation":"заменить","part_of_speech":"глагол"},"powtarzać":{"lemma":"powtarzać","translation":"повторять","part_of_speech":"глагол"},"konflikt":{"lemma":"konflikt","translation":"конфликт","part_of_speech":"существительное"},"środkami":{"lemma":"środek","translation":"средство","part_of_speech":"существительное"},"dzieło":{"lemma":"dzieło","translation":"произведение","part_of_speech":"существительное"}}','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"b1culture-reading-check"}',31,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
