-- First original B1 vertical block. Existing RLS and grants remain unchanged.
insert into public.courses(id,title,description,level,position,is_active) values ('b1-independent','Независимое общение','Связная речь, опыт и мнение в знакомых ситуациях','B1',2,true) on conflict(id) do update set title=excluded.title,description=excluded.description,level=excluded.level,position=excluded.position,is_active=excluded.is_active;
insert into public.topics(id,course_id,title,description,emoji,position,is_active) values ('b1-biography','b1-independent','Биография и опыт','Связно рассказываем о прошлом, этапах и важных решениях','🧭',0,true) on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('bio-words','b1-biography','words','Etapy życia','Биография','8 карточек · B1','Назови этапы, решения и достижения',9,'🧭',108,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-grammar','b1-biography','grammar','Proces czy rezultat?','Вид в рассказе','6 заданий · B1','Различай фон, повторение и завершённый результат',12,'✏️',109,true,'Как вид глагола строит рассказ о прошлом','[["Фон и процесс","Несовершенный вид описывает длительность, повторение и фон: pracowała, jeździł."],["Результат","Совершенный вид выделяет завершённый этап: ukończyła, podjął, osiągnęli."],["Связная история","Najpierw, następnie, z czasem и w końcu помогают показать развитие событий."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-review','b1-biography','review','Co mnie ukształtowało?','Опыт и перемены','7 карточек · B1','Свяжи опыт с его последствиями',8,'🔄',110,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-quiz','b1-biography','quiz','Quiz: biografia','Проверка темы','10 вопросов · B1','Проверь лексику и связность рассказа',9,'🎯',111,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-reading-check','b1-biography','quiz','Czy rozumiesz drogę Joanny?','Понимание текста','6 вопросов · B1','Найди этапы, причины и главный вывод',7,'📖',112,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('bio-dorastac','dorastać','расти; взрослеть','Dorastałam w małym mieście na południu Polski.',362,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-ukonczyc','ukończyć studia','окончить вуз','Po pięciu latach ukończył studia techniczne.',363,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-zdobyc','zdobyć doświadczenie','приобрести опыт','Pierwszą pracę podjęła, żeby zdobyć doświadczenie.',364,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-podjac','podjąć decyzję','принять решение','Wtedy podjąłem ważną decyzję o przeprowadzce.',365,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-przeprowadzic','przeprowadzić się','переехать','W 2018 roku przeprowadziliśmy się do Poznania.',366,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-rozpoczac','rozpocząć karierę','начать карьеру','Karierę rozpoczęła jako asystentka.',367,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-osiagnac','osiągnąć cel','достичь цели','Po kilku latach osiągnął swój zawodowy cel.',368,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-wydarzenie','ważne wydarzenie','важное событие','To wydarzenie całkowicie zmieniło jej plany.',369,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-poczatkowo','początkowo','поначалу','Początkowo nie znałem w mieście nikogo.',370,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-z-czasem','z czasem','со временем','Z czasem poczuła się pewniej w nowej roli.',371,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-okazac','okazać się','оказаться','Nowe zajęcie okazało się bardzo ciekawe.',372,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-wplynac','wpłynąć na','повлиять на','Ta rozmowa wpłynęła na moją decyzję.',373,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-wspominac','wspominać','вспоминать','Często wspominam pierwszy dzień pracy.',374,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-doswiadczenie','życiowe doświadczenie','жизненный опыт','Podróż była dla niej ważnym doświadczeniem.',375,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('bio-przelom','punkt zwrotny','поворотный момент','Zmiana zawodu stała się punktem zwrotnym.',376,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('bio-words','bio-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('bio-words','bio-dorastac',0),('bio-words','bio-ukonczyc',1),('bio-words','bio-zdobyc',2),('bio-words','bio-podjac',3),('bio-words','bio-przeprowadzic',4),('bio-words','bio-rozpoczac',5),('bio-words','bio-osiagnac',6),('bio-words','bio-wydarzenie',7),
('bio-review','bio-poczatkowo',0),('bio-review','bio-z-czasem',1),('bio-review','bio-okazac',2),('bio-review','bio-wplynac',3),('bio-review','bio-wspominac',4),('bio-review','bio-doswiadczenie',5),('bio-review','bio-przelom',6);

delete from public.questions where lesson_id in ('bio-grammar','bio-quiz','bio-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('bio-grammar','Przez trzy lata Marta ___ w banku, a potem zmieniła zawód.','["pracowała","przepracowała","będzie pracować"]',0,'Несовершенный вид pracowała описывает длительный фон прошлого.',0),
('bio-grammar','W 2020 roku Marta ___ kurs i dostała certyfikat.','["kończyła","ukończyła","kończy"]',1,'Ukończyła подчёркивает завершённый результат.',1),
('bio-grammar','Kiedy ___ studia, przeprowadził się do Gdańska.','["kończył","ukończył","ukończy"]',1,'Одно завершённое событие предшествует другому: ukończył.',2),
('bio-grammar','Составьте: Сначала она работала в школе, а потом открыла фирму.','["Najpierw pracowała w szkole, a potem założyła firmę.","Najpierw założyła szkołę, bo pracowała firmę.","Pracuje najpierw, potem firma otwierała."]',0,'Najpierw и potem выстраивают хронологию; założyła передаёт достигнутый результат.',3),
('bio-grammar','Co roku Jan ___ za granicę, ale w zeszłym roku ___ w Polsce.','["jeździł; został","pojechał; zostawał","jeździ; zostanie"]',0,'Jeździł описывает повторение, został — единичный завершённый выбор.',4),
('bio-grammar','Составьте: Этот опыт сильно повлиял на мою жизнь.','["To doświadczenie bardzo wpłynęło na moje życie.","To doświadczenie wpływało moje życie bardzo.","Moje życie wpłynęło do doświadczenia."]',0,'Wpłynąć требует na + винительный падеж: na moje życie.',5),
('bio-quiz','Что означает dorastać?','["взрослеть","переезжать","увольняться"]',0,'Dorastać — постепенно становиться взрослым.',0),
('bio-quiz','Po studiach Anna ___ karierę w mediach.','["rozpoczęła","dorastała","wspominała się"]',0,'Rozpocząć karierę — начать профессиональный путь.',1),
('bio-quiz','Как сказать «поворотный момент»?','["punkt zwrotny","ważny kierunek","czas doświadczenia"]',0,'Punkt zwrotny меняет дальнейшее развитие событий.',2),
('bio-quiz','Pracował nad projektem rok i wreszcie ___ cel.','["osiągnął","osiągał się","dorósł na"]',0,'Osiągnął обозначает полученный результат.',3),
('bio-quiz','Która forma opisuje powtarzające się podróże?','["jeździłem","pojechałem","pojadę raz"]',0,'Jeździłem передаёт повторявшееся действие.',4),
('bio-quiz','Ta książka ___ na wybór jej zawodu.','["wpłynęła","przeprowadziła","ukończyła"]',0,'Wpłynąć na — оказать влияние на что-либо.',5),
('bio-quiz','___ było trudno, lecz z czasem wszystko się zmieniło.','["Początkowo","Na końcu wczoraj","Osiągnięcie"]',0,'Początkowo вводит начальный этап истории.',6),
('bio-quiz','Nowa praca ___ ciekawsza, niż oczekiwał.','["okazała się","podjęła się na","zdobyła się"]',0,'Okazać się сообщает, каким что-либо оказалось.',7),
('bio-quiz','Что лучше связывает биографический рассказ?','["najpierw, następnie, z czasem, w końcu","bo, albo, czy, lecz że","wczoraj, jutro, teraz, nigdy"]',0,'Хронологические маркеры делают рассказ связным.',8),
('bio-quiz','Как сказать о завершённом образовании?','["Ukończyłem studia w 2019 roku.","Kończyłem studia i nie wiadomo kiedy.","Studia ukończyć w roku."]',0,'Ukończyłem ясно обозначает завершённый этап.',9),
('bio-reading-check','Gdzie dorastała Joanna?','["W Białymstoku","W Krakowie","Za granicą"]',0,'Йоанна выросла в Белостоке.',0),
('bio-reading-check','Co studiowała?','["Architekturę","Medycynę","Dziennikarstwo"]',0,'Она изучала архитектуру в Варшаве.',1),
('bio-reading-check','Dlaczego pierwsza praca była ważna?','["Zdobyła praktyczne doświadczenie","Od razu została dyrektorką","Mogła wrócić do szkoły"]',0,'Первая работа дала ей практический опыт.',2),
('bio-reading-check','Co było punktem zwrotnym?','["Projekt biblioteki w małym mieście","Wyjazd na wakacje","Zmiana mieszkania w dzieciństwie"]',0,'Работа над библиотекой изменила её профессиональные цели.',3),
('bio-reading-check','Jak zmieniły się jej plany?','["Postanowiła projektować miejsca publiczne","Zrezygnowała z architektury","Chciała pracować wyłącznie sama"]',0,'Она решила заниматься общественными пространствами.',4),
('bio-reading-check','Jaki wniosek wyciąga Joanna?','["Doświadczenia pomagają lepiej rozumieć własne cele","Każdy plan musi pozostać bez zmian","Pierwsza praca zawsze jest najważniejsza"]',0,'В финале она связывает опыт с пониманием собственных целей.',5);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('bio-droga-joanny','b1-biography','Droga Joanny do własnego celu','Биография, профессиональный выбор и поворотный момент','B1',8,'🧭',
'["Joanna dorastała w Białymstoku. Już jako dziecko lubiła rysować domy i obserwować, jak zmienia się jej miasto. Po maturze przeprowadziła się do Warszawy, gdzie rozpoczęła studia architektoniczne. Początkowo trudno było jej przyzwyczaić się do szybkiego życia w stolicy, ale z czasem poznała przyjaciół i poczuła się pewniej.","Po ukończeniu studiów Joanna podjęła pracę w niewielkim biurze projektowym. Przez dwa lata przygotowywała rysunki i pomagała bardziej doświadczonym architektom. Nie prowadziła jeszcze własnych projektów, jednak zdobyła praktyczne doświadczenie i nauczyła się rozmawiać z klientami.","Punktem zwrotnym okazał się projekt biblioteki w małym mieście. Joanna odpowiadała za spotkania z mieszkańcami. Zrozumiała wtedy, że dobrze zaprojektowane miejsce może wpłynąć na codzienne życie wielu osób. Po zakończeniu projektu podjęła decyzję, że chce zajmować się przede wszystkim przestrzeniami publicznymi.","Dziś Joanna pracuje w większym zespole i prowadzi własne projekty. Często wspomina pierwsze lata kariery, bo dzięki nim lepiej rozumie swoje cele. Uważa, że nawet trudne doświadczenie może z czasem stać się ważnym etapem rozwoju."]',
'{"dorastała":{"lemma":"dorastać","translation":"взрослеть","part_of_speech":"глагол"},"maturze":{"lemma":"matura","translation":"выпускной экзамен","part_of_speech":"существительное"},"przyzwyczaić":{"lemma":"przyzwyczaić się","translation":"привыкнуть","part_of_speech":"глагол"},"ukończeniu":{"lemma":"ukończenie","translation":"окончание","part_of_speech":"существительное"},"niewielkim":{"lemma":"niewielki","translation":"небольшой","part_of_speech":"прилагательное"},"zdobyła":{"lemma":"zdobyć","translation":"приобрести","part_of_speech":"глагол"},"punktem":{"lemma":"punkt zwrotny","translation":"поворотный момент","part_of_speech":"словосочетание"},"mieszkańcami":{"lemma":"mieszkaniec","translation":"житель","part_of_speech":"существительное"},"wpłynąć":{"lemma":"wpłynąć na","translation":"повлиять на","part_of_speech":"глагол"},"przestrzeniami":{"lemma":"przestrzeń","translation":"пространство","part_of_speech":"существительное"},"prowadzi":{"lemma":"prowadzić","translation":"вести; руководить","part_of_speech":"глагол"},"rozwoju":{"lemma":"rozwój","translation":"развитие","part_of_speech":"существительное"}}',
'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29","comprehension_lesson_id":"bio-reading-check"}',24,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
