-- Add comprehension checks to all active A1 readings. Content-only; no schema, grants, or RLS changes.

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-poranek-check','introductions','quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',228,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='poranek-anny' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-poranek-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-poranek-check','Co Anna je na śniadanie?','["Chleb z serem","Zupę","Ryż"]',0,'Она ест хлеб с сыром.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-poranek-check','Dokąd potem idzie?','["Do pracy","Do szkoły","Na targ"]',0,'После завтрака она идёт на работу.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-poranek-check','Kogo spotyka po drodze?','["Sąsiada","Lekarza","Nauczyciela"]',0,'По дороге она встречает соседа.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-poranek-check"}'::jsonb where id='poranek-anny';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-kurs-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',229,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='pierwszy-dzien-na-kursie' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-kurs-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-kurs-check','Gdzie jest Anna?','["Na kursie polskiego","W banku","W sklepie"]',0,'Это первый день на курсе.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-kurs-check','Skąd pochodzi Anna?','["Z Ukrainy","Z Polski","Z Niemiec"]',0,'Анна из Украины.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-kurs-check','Jak ma na imię nowy kolega?','["Marek","Paweł","Thomas"]',0,'Нового коллегу зовут Марек.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-kurs-check"}'::jsonb where id='pierwszy-dzien-na-kursie';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-targ-check','introductions','quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',230,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='zakupy-na-targu' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-targ-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-targ-check','Kiedy Marek idzie na targ?','["W sobotę","W poniedziałek","W nocy"]',0,'Он идёт на рынок в субботу.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-targ-check','Ile kosztuje kilogram pomidorów?','["Cztery złote","Dwanaście złotych","Dwa złote"]',0,'Продавец называет четыре злотых.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-targ-check','Jakie jabłka wybiera?','["Czerwone","Zielone","Żółte"]',0,'Он выбирает красные яблоки.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-targ-check"}'::jsonb where id='zakupy-na-targu';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-grupa-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',231,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='rozmowa-w-miedzynarodowej-grupie' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-grupa-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-grupa-check','Gdzie mieszka Oksana?','["W Krakowie","W Berlinie","W Warszawie"]',0,'Оксана живёт в Кракове.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-grupa-check','Jaki jest język ojczysty Thomasa?','["Niemiecki","Polski","Ukraiński"]',0,'Томас из Германии.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-grupa-check','Czego uczą się razem?','["Języka polskiego","Matematyki","Historii"]',0,'Группа вместе учит польский.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-grupa-check"}'::jsonb where id='rozmowa-w-miedzynarodowej-grupie';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-rodzina-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',232,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='niedziela-u-babci' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-rodzina-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-rodzina-check','Kogo odwiedza Maja?','["Babcię i dziadka","Koleżankę","Lekarza"]',0,'Мая навещает бабушку и дедушку.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-rodzina-check','Kim jest mama Mai?','["Nauczycielką","Lekarką","Sprzedawczynią"]',0,'Её мама работает учительницей.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-rodzina-check','Czym interesuje się Kuba?','["Sportem","Gotowaniem","Muzyką"]',0,'Куба интересуется спортом.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-rodzina-check"}'::jsonb where id='niedziela-u-babci';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-dzien-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',233,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='zwykly-dzien-oli' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-dzien-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-dzien-check','O której Ola wstaje?','["O siódmej","O szóstej","O dziewiątej"]',0,'Она встаёт в семь.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-dzien-check','Jak wraca z pracy?','["Autobusem","Pociągiem","Rowerem"]',0,'Она возвращается автобусом.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-dzien-check','O której kładzie się spać?','["O jedenastej","O ósmej","O północy"]',0,'Она ложится в одиннадцать.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-dzien-check"}'::jsonb where id='zwykly-dzien-oli';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-mieszkanie-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',234,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='nowe-mieszkanie-marty' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-mieszkanie-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-mieszkanie-check','Na którym piętrze mieszka Marta?','["Na drugim","Na pierwszym","Na trzecim"]',0,'Квартира на втором этаже.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-mieszkanie-check','Co stoi w salonie?','["Sofa, stół i krzesła","Łóżko i szafa","Biurko i komputer"]',0,'Эти предметы находятся в гостиной.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-mieszkanie-check','Co jest naprzeciwko sypialni?','["Łazienka","Kuchnia","Balkon"]',0,'Напротив спальни ванная.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-mieszkanie-check"}'::jsonb where id='nowe-mieszkanie-marty';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-zakupy-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',235,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='zakupy-oli' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-zakupy-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-zakupy-check','Co Ola chce przygotować?','["Śniadanie","Obiad dla gości","Kolację w restauracji"]',0,'Она покупает продукты на завтрак.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-zakupy-check','Jak płaci?','["Kartą","Gotówką","Telefonem"]',0,'Оля платит картой.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-zakupy-check','Ile jabłek wybiera?','["Cztery","Dwa","Sześć"]',0,'Она берёт четыре яблока.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-zakupy-check"}'::jsonb where id='zakupy-oli';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-muzeum-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',236,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='droga-do-muzeum' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-muzeum-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-muzeum-check','Skąd wychodzi Anna?','["Z dworca","Z muzeum","Z banku"]',0,'Она выходит с вокзала.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-muzeum-check','Gdzie skręca na drugim skrzyżowaniu?','["W lewo","W prawo","Nie skręca"]',0,'Инструкция велит повернуть налево.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-muzeum-check','Co jest naprzeciwko muzeum?','["Kawiarnia","Dworzec","Apteka"]',0,'Напротив музея кафе.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-muzeum-check"}'::jsonb where id='droga-do-muzeum';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-spotkanie-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',237,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='spotkanie-w-piatek' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-spotkanie-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-spotkanie-check','Dlaczego czwartek nie pasuje Pawłowi?','["Ma kurs polskiego","Pracuje w nocy","Jedzie do lekarza"]',0,'В четверг у него курс.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-spotkanie-check','O której się spotykają?','["O szóstej","O piątej","O siódmej"]',0,'Они договорились на шесть.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-spotkanie-check','Gdzie się spotykają?','["W kawiarni obok parku","Na dworcu","W biurze"]',0,'Место — кафе возле парка.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-spotkanie-check"}'::jsonb where id='spotkanie-w-piatek';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-praca-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',238,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='pierwszy-dzien-w-pracy' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-praca-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-praca-check','Gdzie pracuje Kasia?','["W małej firmie","W szkole","W aptece"]',0,'У Каси новая работа в небольшой фирме.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-praca-check','Co pisze pierwszego dnia?','["Pierwszą wiadomość","Długą książkę","Receptę"]',0,'Её первая задача — сообщение.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-praca-check','Jak często uczy się polskiego?','["Dwa razy w tygodniu","Codziennie","Raz w miesiącu"]',0,'Она учится дважды в неделю.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-praca-check"}'::jsonb where id='pierwszy-dzien-w-pracy';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-sobota-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',239,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='wolna-sobota-marka' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-sobota-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-sobota-check','Co Marek robi rano?','["Czyta książkę","Idzie do pracy","Gra w piłkę"]',0,'Утром он читает.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-sobota-check','Dlaczego przyjaciele idą do kawiarni?','["Pada deszcz","Jest bardzo gorąco","Park jest zamknięty"]',0,'Из-за дождя они меняют план.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-sobota-check','Jaki film wybierają?','["Krótką komedię","Horror","Film historyczny"]',0,'Они выбирают короткую комедию.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-sobota-check"}'::jsonb where id='wolna-sobota-marka';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-lekarz-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',240,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='ola-u-lekarza' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-lekarz-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-lekarz-check','Jaką temperaturę ma Ola?','["Trzydzieści osiem stopni","Trzydzieści sześć","Czterdzieści"]',0,'У неё 38 градусов.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-lekarz-check','Dlaczego nie idzie do pracy?','["Źle się czuje","Ma urlop","Jedzie na kurs"]',0,'Она заболела.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-lekarz-check','Dokąd idzie po wizycie?','["Do apteki","Do banku","Do muzeum"]',0,'После врача она идёт в аптеку.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-lekarz-check"}'::jsonb where id='ola-u-lekarza';

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) select 'a1read-final-check',topic_id,'quiz','Czy rozumiesz tekst?','Понимание текста','3 вопроса · A1','Проверь понимание прочитанного текста',5,'📖',241,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}' from public.reading_texts where id='samodzielny-dzien-leny' on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;
delete from public.questions where lesson_id='a1read-final-check';
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-final-check','Na kiedy Lena umawia lekarza?','["Na czwartek o dziewiątej","Na piątek o szóstej","Na sobotę rano"]',0,'Визит назначен на четверг в девять.',0);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-final-check','Co kupuje w sklepie?','["Chleb, mleko i jabłka","Lekarstwo i kawę","Ser i pomidory"]',0,'Это её покупки.',1);
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values ('a1read-final-check','O czym rozmawia z koleżanką?','["O rodzinie, pracy i weekendzie","Tylko o pogodzie","O egzaminie z matematyki"]',0,'Они обсуждают семью, работу и выходные.',2);
update public.reading_texts set source_metadata=coalesce(source_metadata,'{}'::jsonb) || '{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"a1read-final-check"}'::jsonb where id='samodzielny-dzien-leny';
