insert into public.topics(id,course_id,title,description,emoji,position,is_active) values
('b1-media-internet','b1-independent','Медиа и интернет','Проверяем публикации и связно передаём их главную мысль','📰',6,true)
on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('b1media-words','b1-media-internet','words','Co naprawdę napisano?','Публикация и источник','8 карточек · B1','Назови части публикации и оцени источник',9,'📰',138,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-grammar','b1-media-internet','grammar','Jak przekazać wiadomość?','Структура пересказа','6 заданий · B1','Используй глаголы речи и маркеры последовательности',12,'✏️',139,true,'Глаголы речи и ясный пересказ','[["Кто сообщает","Twierdzić и podkreślać передают позицию автора, relacjonować — ход события, a zaprzeczać — отрицание сообщения."],["Вывод из источника","Конструкция z tekstu wynika, że показывает, что вывод основан на публикации, а не является личным фактом."],["Структура","Назови тему и главную мысль, затем используй najpierw, następnie, na końcu для существенных деталей."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-review','b1-media-internet','review','Sprawdzam i streszczam','Проверка информации','7 карточек · B1','Сравни источники и сформулируй главную мысль',8,'🔄',140,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-quiz','b1-media-internet','quiz','Quiz: media i internet','Проверка темы','10 вопросов · B1','Проверь лексику и структуру пересказа',9,'🎯',141,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-reading-check','b1-media-internet','quiz','Czy wiadomość była prawdziwa?','Понимание текста','6 вопросов · B1','Отдели заголовок от подтверждённой главной мысли',7,'📖',142,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('b1media-publikacja','publikacja','публикация','Publikacja opisuje wyniki miejskiego badania.',452,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-naglowek','nagłówek','заголовок','Nagłówek powinien odpowiadać treści artykułu.',453,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-zrodlo','źródło informacji','источник информации','Zawsze sprawdzam źródło informacji.',454,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-wiarygodny','wiarygodny','достоверный','Wiarygodny autor podaje konkretne dane.',455,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-udostepnic','udostępnić','поделиться; опубликовать','Nie udostępniaj wiadomości bez sprawdzenia.',456,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-komentarz','komentarz','комментарий','Komentarz nie zawsze opisuje fakt.',457,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-relacjonowac','relacjonować','освещать; рассказывать','Reporter relacjonował wydarzenie na żywo.',458,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-twierdzic','twierdzić','утверждать','Autor twierdzi, że projekt zakończył się sukcesem.',459,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-podkreslac','podkreślać','подчёркивать','Ekspert podkreśla znaczenie kontekstu.',460,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-zaprzeczyc','zaprzeczyć','опровергнуть; отрицать','Organizator zaprzeczył tej informacji.',461,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-wynikac','wynikać z','следовать из','Z raportu wynika, że ruch w mieście zmalał.',462,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-glowna-mysl','główna myśl','основная мысль','Najpierw znajdź główną myśl tekstu.',463,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-strescic','streścić','кратко пересказать','Potrafisz streścić artykuł w trzech zdaniach?',464,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-porownac','porównać źródła','сравнить источники','Warto porównać źródła przed wyciągnięciem wniosku.',465,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}'),
('b1media-wprowadzac-blad','wprowadzać w błąd','вводить в заблуждение','Zdjęcie bez daty może wprowadzać w błąd.',466,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('b1media-words','b1media-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('b1media-words','b1media-publikacja',0),('b1media-words','b1media-naglowek',1),('b1media-words','b1media-zrodlo',2),('b1media-words','b1media-wiarygodny',3),('b1media-words','b1media-udostepnic',4),('b1media-words','b1media-komentarz',5),('b1media-words','b1media-relacjonowac',6),('b1media-words','b1media-twierdzic',7),('b1media-review','b1media-podkreslac',0),('b1media-review','b1media-zaprzeczyc',1),('b1media-review','b1media-wynikac',2),('b1media-review','b1media-glowna-mysl',3),('b1media-review','b1media-strescic',4),('b1media-review','b1media-porownac',5),('b1media-review','b1media-wprowadzac-blad',6);

delete from public.questions where lesson_id in ('b1media-grammar','b1media-quiz','b1media-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('b1media-grammar','Autor ___, że nowa aplikacja poprawi bezpieczeństwo.','["twierdzi","wynika","streszcza się"]',0,'Twierdzić вводит утверждение автора и сочетается с że.',0),
('b1media-grammar','Z raportu ___, że większość czytelników sprawdza datę.','["wynika","zaprzecza","relacjonuje"]',0,'Безличная конструкция z raportu wynika, że передаёт вывод из источника.',1),
('b1media-grammar','Reporter powiedział: «Mieszkańcy protestują». Reporter relacjonował, ___.','["że mieszkańcy protestują","czy mieszkańcy protestują","żeby mieszkańcy protestują"]',0,'В пересказе сообщения содержание вводится союзом że.',2),
('b1media-grammar','Najpierw podaj temat, ___ przedstaw główną myśl i szczegóły.','["następnie","ponieważ","mimo że"]',0,'Następnie связывает последовательные части пересказа.',3),
('b1media-grammar','Составьте: Автор подчёркивает, что заголовок не передаёт главную мысль.','["Autor podkreśla, że nagłówek nie oddaje głównej myśli.","Autor wynika, czy nagłówek nie oddaje główną myśl.","Autor podkreślać, żeby nagłówek nie oddaje."]',0,'После podkreśla содержание вводится że; oddawać требует родительного падежа.',4),
('b1media-grammar','Составьте: Сначала я проверил источник, а затем кратко пересказал публикацию.','["Najpierw sprawdziłem źródło, a następnie krótko streściłem publikację.","Ponieważ sprawdziłem źródło, następnie streszczam publikacją.","Najpierw źródło sprawdzałem, mimo że streścił publikację."]',0,'Najpierw… a następnie задаёт ясную структуру; streścić принимает винительный падеж.',5),
('b1media-quiz','Что означает wiarygodne źródło?','["источник, которому можно доверять","популярный комментарий","короткий заголовок"]',0,'Wiarygodne źródło содержит проверяемые сведения и прозрачное авторство.',0),
('b1media-quiz','Nie znam autora ani daty, więc nie będę ___ tej wiadomości.','["udostępniać","wynikać","nagłówkować"]',0,'Udostępniać wiadomość — делиться сообщением.',1),
('b1media-quiz','Który czasownik wprowadza zdecydowaną opinię autora?','["twierdzić","wynikać z","porównać"]',0,'Twierdzić показывает, что именно утверждает автор.',2),
('b1media-quiz','Z danych ___, że zainteresowanie wzrosło.','["wynika","podkreśla","udostępnia"]',0,'Форма wynika используется для вывода, основанного на данных.',3),
('b1media-quiz','Jak zacząć uporządkowane streszczenie?','["Tekst dotyczy…, a jego główna myśl to…","Wszystko w tekście jest ważne.","Nie pamiętam źródła, ale…"]',0,'Хороший пересказ называет тему и основную мысль.',4),
('b1media-quiz','Autor zaprzeczył, ___ opublikował nieprawdziwe dane.','["że","czy","więc"]',0,'После zaprzeczył содержание сообщения вводится że.',5),
('b1media-quiz','Co najlepiej pomaga sprawdzić wiadomość?','["Porównanie daty, autora i kilku źródeł","Przeczytanie tylko komentarzy","Udostępnienie samego nagłówka"]',0,'Сопоставление реквизитов и независимых источников снижает риск ошибки.',6),
('b1media-quiz','Выберите естественное сочетание.','["streścić publikację","wynikać komentarz","zaprzeczyć źródłem"]',0,'Streścić publikację — кратко передать содержание публикации.',7),
('b1media-quiz','Reporter ___ przebieg debaty, a ekspert wyjaśniał dane.','["relacjonował","wynikał","udostępniał się"]',0,'Relacjonować означает последовательно освещать событие.',8),
('b1media-quiz','Które zdanie oddziela fakt od opinii?','["Raport podaje liczbę, natomiast autor ocenia jej znaczenie.","Każdy popularny wpis jest prawdziwy.","Nagłówek zawsze wystarcza."]',0,'Первый вариант явно различает данные и авторскую оценку.',9),
('b1media-reading-check','Co zobaczyła Marta rano?','["Wpis o rzekomym zamknięciu biblioteki","Relację z koncertu","Reklamę nowej książki"]',0,'В ленте появился пост о якобы закрывающейся библиотеке.',0),
('b1media-reading-check','Dlaczego nagłówek wzbudził jej wątpliwości?','["Nie podawał autora ani daty decyzji","Był napisany po polsku","Zawierał nazwę dzielnicy"]',0,'В заголовке не было проверяемых реквизитов.',1),
('b1media-reading-check','Jak Marta sprawdziła informację?','["Porównała wpis z oficjalną stroną i lokalnym portalem","Zapytała tylko autora komentarza","Natychmiast udostępniła wpis"]',0,'Она обратилась к двум более прозрачным источникам.',2),
('b1media-reading-check','Co naprawdę planowała biblioteka?','["Krótki remont jednego piętra","Całkowite zamknięcie","Przeprowadzkę do innego miasta"]',0,'Речь шла лишь о ремонте одного этажа.',3),
('b1media-reading-check','Jak Marta streściła sytuację znajomym?','["Podała główną myśl, źródła i ważne szczegóły","Powtórzyła sam alarmujący nagłówek","Usunęła wszystkie informacje"]',0,'Её пересказ отделял подтверждённую суть от преувеличения.',4),
('b1media-reading-check','Jaki jest główny wniosek tekstu?','["Przed udostępnieniem trzeba sprawdzić kontekst i źródła","Najpopularniejszy wpis jest zawsze dokładny","Komentarze zastępują oficjalne informacje"]',0,'Главная мысль — осознанная проверка до распространения сообщения.',5);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('b1media-wiadomosc-ktora-wymagala-sprawdzenia','b1-media-internet','Wiadomość, która wymagała sprawdzenia','Как проверить публикацию и передать её главную мысль','B1',8,'📰','["Rano Marta zobaczyła w mediach społecznościowych alarmujący wpis: biblioteka w jej dzielnicy miała zostać zamknięta. Nagłówek brzmiał poważnie, ale publikacja nie zawierała nazwiska autora ani daty decyzji. W komentarzach jedni mieszkańcy wyrażali złość, a inni od razu udostępniali wiadomość znajomym.","Marta postanowiła sprawdzić źródło informacji. Na oficjalnej stronie biblioteki znalazła komunikat o remoncie jednego piętra. Następnie porównała go z artykułem lokalnego portalu, który relacjonował posiedzenie rady dzielnicy i podawał dokładny termin prac.","Z obu źródeł wynikało, że biblioteka pozostanie otwarta, chociaż przez dwa tygodnie część sal będzie niedostępna. Dyrektorka podkreślała, że wszystkie zajęcia dla dzieci odbędą się zgodnie z planem. Zaprzeczyła też, że instytucji grozi całkowite zamknięcie.","Marta napisała znajomym krótkie streszczenie. Najpierw podała główną myśl, następnie wymieniła sprawdzone źródła, a na końcu wyjaśniła, skąd wzięło się nieporozumienie. Zrozumiała, że alarmujący nagłówek może wprowadzać w błąd, jeśli czytelnik nie sprawdzi daty, autora i szerszego kontekstu."]','{"alarmujący":{"lemma":"alarmujący","translation":"тревожный","part_of_speech":"прилагательное"},"miała zostać":{"lemma":"mieć zostać","translation":"должна была быть","part_of_speech":"глагольная конструкция"},"zawierała":{"lemma":"zawierać","translation":"содержать","part_of_speech":"глагол"},"wyrażali":{"lemma":"wyrażać","translation":"выражать","part_of_speech":"глагол"},"postanowiła":{"lemma":"postanowić","translation":"решить","part_of_speech":"глагол"},"komunikat":{"lemma":"komunikat","translation":"сообщение; объявление","part_of_speech":"существительное"},"remoncie":{"lemma":"remont","translation":"ремонт","part_of_speech":"существительное"},"posiedzenie":{"lemma":"posiedzenie","translation":"заседание","part_of_speech":"существительное"},"pozostanie":{"lemma":"pozostać","translation":"остаться","part_of_speech":"глагол"},"niedostępna":{"lemma":"niedostępny","translation":"недоступный","part_of_speech":"прилагательное"},"odbędą się":{"lemma":"odbyć się","translation":"состояться","part_of_speech":"глагол"},"grozi":{"lemma":"grozić","translation":"угрожать","part_of_speech":"глагол"},"streszczenie":{"lemma":"streszczenie","translation":"краткий пересказ","part_of_speech":"существительное"},"wymieniła":{"lemma":"wymienić","translation":"перечислить","part_of_speech":"глагол"},"nieporozumienie":{"lemma":"nieporozumienie","translation":"недоразумение","part_of_speech":"существительное"},"szerszego":{"lemma":"szeroki","translation":"более широкий","part_of_speech":"прилагательное"}}','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-30","comprehension_lesson_id":"b1media-reading-check"}',30,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
