insert into public.topics(id,course_id,title,description,emoji,position,is_active) values
('b1-work-development','b1-independent','Работа и развитие','Обсуждаем опыт, планы и профессиональное развитие в формальном регистре','💼',2,true)
on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('b1work-words','b1-work-development','words','Nowy krok w pracy','Работа и обязанности','8 карточек · B1','Опиши опыт и условия вакансии',9,'💼',118,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-grammar','b1-work-development','grammar','Gdybym dostał tę pracę...','Условия и вежливость','6 заданий · B1','Используй условное наклонение в формальной речи',12,'✏️',119,true,'Условное наклонение и формальный регистр','[["Условие","Gdyby + прошедшая форма с частицей by описывает воображаемую ситуацию: Gdybym dostał..., zrobiłbym..."],["Вежливая просьба","Chciałbym, mógłby Pan и czy moglibyśmy смягчают просьбу в профессиональной беседе."],["Официальное письмо","Uprzejmie proszę o... и Zwracam się z prośbą o... — нейтральные формулы обращения."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-review','b1-work-development','review','Plan rozwoju','Развитие и результаты','7 карточек · B1','Обсуди цели, обучение и инициативу',8,'🔄',120,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-quiz','b1-work-development','quiz','Quiz: praca i rozwój','Проверка темы','10 вопросов · B1','Проверь лексику и профессиональный регистр',9,'🎯',121,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-reading-check','b1-work-development','quiz','Czy rozumiesz historię Leny?','Понимание текста','6 вопросов · B1','Найди мотивацию, действия и вывод',7,'📖',122,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('b1work-stanowisko','stanowisko','должность','Aplikuję na stanowisko specjalisty do spraw sprzedaży.',392,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-obowiazki','obowiązki','обязанности','Do moich obowiązków należy kontakt z klientami.',393,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-doswiadczenie','doświadczenie zawodowe','профессиональный опыт','Mam trzyletnie doświadczenie zawodowe.',394,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-kwalifikacje','kwalifikacje','квалификация','Kandydat powinien mieć odpowiednie kwalifikacje.',395,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-rekrutacja','rekrutacja','подбор персонала','Rekrutacja składa się z dwóch etapów.',396,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-rozmowa','rozmowa kwalifikacyjna','собеседование','Jutro mam rozmowę kwalifikacyjną online.',397,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-zespol','zespół','команда','Nasz zespół pracuje nad nowym projektem.',398,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-termin','termin','срок','Musimy dotrzymać terminu projektu.',399,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-awans','awans','повышение','Po dwóch latach otrzymała awans.',400,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-podwyzka','podwyżka','повышение зарплаты','Chciałbym porozmawiać o podwyżce.',401,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-szkolenie','szkolenie','обучение; тренинг','Firma organizuje szkolenie z negocjacji.',402,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-rozwoj','rozwój zawodowy','профессиональное развитие','Zależy mi na rozwoju zawodowym.',403,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-wdrozyc','wdrożyć','внедрить; ввести в курс дела','Mentorka pomogła wdrożyć nową pracownicę.',404,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-osiagnac','osiągnąć cel','достичь цели','W tym kwartale osiągnęliśmy cel sprzedażowy.',405,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('b1work-inicjatywa','wykazać inicjatywę','проявить инициативу','Warto wykazać inicjatywę podczas projektu.',406,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('b1work-words','b1work-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('b1work-words','b1work-stanowisko',0),('b1work-words','b1work-obowiazki',1),('b1work-words','b1work-doswiadczenie',2),('b1work-words','b1work-kwalifikacje',3),('b1work-words','b1work-rekrutacja',4),('b1work-words','b1work-rozmowa',5),('b1work-words','b1work-zespol',6),('b1work-words','b1work-termin',7),('b1work-review','b1work-awans',0),('b1work-review','b1work-podwyzka',1),('b1work-review','b1work-szkolenie',2),('b1work-review','b1work-rozwoj',3),('b1work-review','b1work-wdrozyc',4),('b1work-review','b1work-osiagnac',5),('b1work-review','b1work-inicjatywa',6);

delete from public.questions where lesson_id in ('b1work-grammar','b1work-quiz','b1work-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('b1work-grammar','Gdybym miał więcej czasu, ___ kurs zarządzania.','["ukończyłbym","ukończę by","ukończyłem"]',0,'Условное наклонение образуется формой прошедшего времени с частицей by: ukończyłbym.',0),
('b1work-grammar','Na pani miejscu ___ swoje osiągnięcia w CV.','["opisałabym","opisuję by","opisałam"]',0,'Na pani miejscu + tryb warunkowy служит вежливым советом.',1),
('b1work-grammar','Составьте: Я хотел бы узнать больше об обязанностях.','["Chciałbym dowiedzieć się więcej o obowiązkach.","Chcę się obowiązki więcej dowiedział.","Dowiedziałbym obowiązkom więcej."]',0,'Chciałbym — вежливая условная форма; dowiedzieć się o требует местного падежа.',2),
('b1work-grammar','Как официально попросить о встрече?','["Czy moglibyśmy umówić się na spotkanie?","Spotkamy się, dobra?","Musisz dać mi spotkanie."]',0,'Czy moglibyśmy... — нейтральная формальная просьба в условном наклонении.',3),
('b1work-grammar','Составьте: Если бы компания предложила обучение, я бы принял участие.','["Gdyby firma zaproponowała szkolenie, wziąłbym w nim udział.","Jeśli firma proponuje szkolenie, brałem go.","Gdyby szkolenie firma, wezmę udziałem."]',0,'Gdyby вводит условие, а wziąłbym — его возможный результат; wziąć udział w + miejscownik.',4),
('b1work-grammar','Uprzejmie ___ o informację na temat wyniku rekrutacji.','["proszę","żądam sobie","pytam tobie"]',0,'Uprzejmie proszę o... — стандартная формула официальной переписки.',5),
('b1work-quiz','Что означает stanowisko?','["должность","совещание","зарплата"]',0,'Stanowisko — место или должность в организации.',0),
('b1work-quiz','Do moich ___ należy przygotowanie raportów.','["obowiązków","awansów","zespołów do"]',0,'Należeć do + dopełniacz: do obowiązków.',1),
('b1work-quiz','Rekrutacja zwykle zaczyna się od ___.','["wysłania CV","wdrożenia terminu","osiągnięcia zespołu"]',0,'Кандидат начинает процесс с отправки резюме.',2),
('b1work-quiz','Gdybym dostała tę pracę, ___ się nowych narzędzi.','["nauczyłabym","nauczę by","uczyłam do"]',0,'Gdybym... nauczyłabym — согласованные формы условного наклонения.',3),
('b1work-quiz','Как вежливо начать просьбу о повышении зарплаты?','["Chciałbym porozmawiać o możliwości podwyżki.","Dajcie mi natychmiast podwyżkę.","Podwyżka należy mnie."]',0,'Chciałbym porozmawiać... звучит профессионально и не категорично.',4),
('b1work-quiz','Pracownik, który proponuje rozwiązanie bez polecenia, ___.','["wykazuje inicjatywę","dotrzymuje stanowiska","wdraża awans"]',0,'Wykazać inicjatywę — самостоятельно предложить или начать полезное действие.',5),
('b1work-quiz','Musimy ___ terminu do piątku.','["dotrzymać","osiągnąć się","awansować do"]',0,'Dotrzymać terminu — выполнить работу в установленный срок.',6),
('b1work-quiz','Szkolenie wspiera nasz ___.','["rozwój zawodowy","wynik rekrutacji do","obowiązek zespołem"]',0,'Обучение развивает профессиональные компетенции.',7),
('b1work-quiz','Czy ___ przesłać mi szczegóły oferty?','["mógłby Pan","Pan może by","musisz pan"]',0,'Mógłby Pan... — формальная вежливая просьба.',8),
('b1work-quiz','Po dobrych wynikach Marta otrzymała ___.','["awans","rekrutację","termin"]',0,'Otrzymać awans — получить повышение.',9),
('b1work-reading-check','Dlaczego Lena chciała zmienić pracę?','["Chciała się rozwijać i mieć większą odpowiedzialność","Nie lubiła swojego zawodu","Planowała przestać pracować"]',0,'Ей не хватало возможностей развития и ответственности.',0),
('b1work-reading-check','Co zrobiła przed wysłaniem CV?','["Opisała wyniki i ukończyła kurs","Poprosiła o natychmiastowy awans","Zrezygnowała ze szkolenia"]',0,'Она подготовила конкретные достижения и прошла курс.',1),
('b1work-reading-check','O co zapytał kierownik podczas rozmowy?','["O reakcję na opóźnienie projektu","O ulubiony środek transportu","O cenę mieszkania"]',0,'Руководитель попросил привести пример решения рабочей проблемы.',2),
('b1work-reading-check','Jak Lena odpowiedziała?','["Opisała plan i rozmowę z klientem","Obwiniła cały zespół","Powiedziała, że nie zna rozwiązania"]',0,'Она показала инициативу и спокойную коммуникацию.',3),
('b1work-reading-check','Jakie wsparcie rozwoju oferowała firma?','["Mentora i budżet szkoleniowy","Tylko wyższą pensję","Bezpłatne podróże"]',0,'В предложении были наставник и бюджет на обучение.',4),
('b1work-reading-check','Jaki jest główny wniosek tekstu?','["Rozwój wymaga przygotowania i świadomych pytań","Każda zmiana pracy gwarantuje awans","Na rozmowie nie warto pytać o warunki"]',0,'Лена добилась результата благодаря подготовке и оценке возможностей развития.',5);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('b1work-nowy-krok-leny','b1-work-development','Nowy krok Leny','Собеседование и осознанный выбор профессионального развития','B1',8,'💼','["Lena od czterech lat pracowała jako specjalistka do spraw obsługi klienta. Lubiła swój zespół i dobrze wykonywała obowiązki, jednak coraz częściej czuła, że stoi w miejscu. Chciała zdobyć nowe kwalifikacje, prowadzić projekty i mieć większy wpływ na decyzje.","Zanim wysłała CV, dokładnie opisała swoje wyniki i ukończyła internetowy kurs zarządzania projektem. Podczas rozmowy kwalifikacyjnej kierownik zapytał, co zrobiłaby, gdyby ważny projekt był opóźniony. Lena odpowiedziała, że najpierw ustaliłaby przyczynę, następnie przygotowałaby plan i spokojnie porozmawiałaby z klientem.","Podała też przykład z poprzedniej pracy. Gdy jej zespół nie mógł dotrzymać terminu, wykazała inicjatywę i podzieliła zadania inaczej. Dzięki temu projekt zakończył się tylko dzień później, a klient wcześniej otrzymał jasną informację. Kierownik docenił jej konkretne odpowiedzi.","Firma zaproponowała Lenie stanowisko koordynatorki, wsparcie mentora i budżet na szkolenia. Zanim przyjęła ofertę, uprzejmie zapytała o zakres obowiązków oraz możliwości awansu. Uznała, że rozwój zawodowy nie polega wyłącznie na zmianie stanowiska: wymaga przygotowania, odwagi i świadomego wyboru miejsca, w którym można się uczyć."]','{"specjalistka":{"lemma":"specjalistka","translation":"специалистка","part_of_speech":"существительное"},"wykonywała":{"lemma":"wykonywać","translation":"выполнять","part_of_speech":"глагол"},"wpływ":{"lemma":"wpływ","translation":"влияние","part_of_speech":"существительное"},"kwalifikacje":{"lemma":"kwalifikacja","translation":"квалификация","part_of_speech":"существительное"},"wyniki":{"lemma":"wynik","translation":"результат","part_of_speech":"существительное"},"opóźniony":{"lemma":"opóźniony","translation":"задержанный","part_of_speech":"прилагательное"},"ustaliłaby":{"lemma":"ustalić","translation":"установить; определить","part_of_speech":"глагол"},"przyczynę":{"lemma":"przyczyna","translation":"причина","part_of_speech":"существительное"},"dotrzymać":{"lemma":"dotrzymać","translation":"соблюсти","part_of_speech":"глагол"},"wykazała":{"lemma":"wykazać","translation":"проявить","part_of_speech":"глагол"},"docenił":{"lemma":"docenić","translation":"оценить по достоинству","part_of_speech":"глагол"},"zakres":{"lemma":"zakres","translation":"объём; круг","part_of_speech":"существительное"},"wyłącznie":{"lemma":"wyłącznie","translation":"исключительно","part_of_speech":"наречие"},"świadomego":{"lemma":"świadomy","translation":"осознанный","part_of_speech":"прилагательное"}}','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29","comprehension_lesson_id":"b1work-reading-check"}',26,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
