insert into public.topics(id,course_id,title,description,emoji,position,is_active) values
('a2final-review','a2-independence','Итоговое повторение A2','Интеграционная практика и диагностика навыков уровня A2','🏁',11,true)
on conflict(id) do update set course_id=excluded.course_id,title=excluded.title,description=excluded.description,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active;

insert into public.lessons(id,topic_id,kind,title,plan_title,subtitle,description,minutes,emoji,position,is_active,theory_title,theory_sections,source_metadata) values
('a2final-words','a2final-review','words','Potrafię to powiedzieć','Активные умения A2','8 карточек · A2','Повтори действия для типичных повседневных ситуаций',8,'🧩',103,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-diagnosis','a2final-review','grammar','Diagnoza gramatyczna A2','Грамматика A2','8 заданий · A2','Проверь времена, падежи, союзы и порядок слов',12,'✏️',104,true,'Как связать знания A2 в самостоятельную речь','[["Время и результат","Выбирай прошедшее или будущее по ситуации, а вид глагола — по процессу или завершённому результату."],["Форма зависит от связи","Предлоги и глаголы управляют падежом; niż вводит сравнение, а местоимение заменяет уже названный объект."],["Связный ответ","Że передаёт содержание, bo — причину, następnie — последовательность. В просьбе используй czy może… или chciałbym/chciałabym…."]]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-review','a2final-review','review','Rozwiązuję problemy','Стратегии общения','8 карточек · A2','Повтори фразы для объяснения, совета и итога',8,'🔄',105,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-quiz','a2final-review','quiz','Finałowy quiz A2','Итоговая диагностика','12 вопросов · A2','Проверь ключевые навыки всех тем A2',12,'🎯',106,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-reading-check','a2final-review','quiz','Czy rozumiesz historię Leny?','Понимание текста','6 вопросов · A2','Найди детали и главный вывод связного рассказа',7,'📖',107,true,'','[]','{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set topic_id=excluded.topic_id,kind=excluded.kind,title=excluded.title,plan_title=excluded.plan_title,subtitle=excluded.subtitle,description=excluded.description,minutes=excluded.minutes,emoji=excluded.emoji,position=excluded.position,is_active=excluded.is_active,theory_title=excluded.theory_title,theory_sections=excluded.theory_sections,source_metadata=excluded.source_metadata;

insert into public.flashcards(id,polish,translation,example,position,is_active,source_metadata) values
('a2final-opowiedziec','opowiedzieć o wydarzeniu','рассказать о событии','Potrafię opowiedzieć o tym, co wydarzyło się wczoraj.',346,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zaplanowac','zaplanować podróż','спланировать поездку','Najpierw zaplanujemy podróż, a potem kupimy bilety.',347,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zglosic','zgłosić problem','сообщить о проблеме','Lokator zgłosił właścicielowi problem z ogrzewaniem.',348,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-porownac','porównać możliwości','сравнить варианты','Przed zakupem warto porównać kilka możliwości.',349,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-wyjasnic','wyjaśnić sytuację','объяснить ситуацию','Spokojnie wyjaśniła sprzedawcy całą sytuację.',350,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-poprosic','poprosić o pomoc','попросить о помощи','Czy mogę poprosić panią o pomoc?',351,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-doradzic','doradzić','посоветовать','Farmaceutka doradziła mi łagodny syrop.',352,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-uzasadnic','uzasadnić opinię','обосновать мнение','Uzasadnij swoją opinię jednym przykładem.',353,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-porozumiec','porozumieć się','договориться; понять друг друга','Po szczerej rozmowie łatwiej było nam się porozumieć.',354,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zareagowac','zareagować','отреагировать','Nie wiedziałem, jak zareagować na tę wiadomość.',355,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zalatwic','załatwić sprawę','уладить дело','Udało mi się załatwić sprawę w urzędzie.',356,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zachowac','zachować potwierdzenie','сохранить подтверждение','Trzeba zachować potwierdzenie płatności.',357,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-zmienic','zmienić zdanie','изменить мнение','Po filmie zmieniłam zdanie o tym reżyserze.',358,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-uwzglednic','uwzględnić pogodę','учесть погоду','Planując wycieczkę, trzeba uwzględnić pogodę.',359,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-polecic','polecić miejsce','порекомендовать место','Czy możesz polecić ciekawe miejsce w Polsce?',360,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}'),
('a2final-podsumowac','podsumować','подвести итог','Na końcu krótko podsumowała swoje doświadczenia.',361,true,'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29"}')
on conflict(id) do update set polish=excluded.polish,translation=excluded.translation,example=excluded.example,position=excluded.position,is_active=excluded.is_active,source_metadata=excluded.source_metadata;

delete from public.lesson_flashcards where lesson_id in ('a2final-words','a2final-review');
insert into public.lesson_flashcards(lesson_id,flashcard_id,position) values
('a2final-words','a2final-opowiedziec',0),('a2final-words','a2final-zaplanowac',1),('a2final-words','a2final-zglosic',2),('a2final-words','a2final-porownac',3),('a2final-words','a2final-wyjasnic',4),('a2final-words','a2final-poprosic',5),('a2final-words','a2final-doradzic',6),('a2final-words','a2final-uzasadnic',7),
('a2final-review','a2final-porozumiec',0),('a2final-review','a2final-zareagowac',1),('a2final-review','a2final-zalatwic',2),('a2final-review','a2final-zachowac',3),('a2final-review','a2final-zmienic',4),('a2final-review','a2final-uwzglednic',5),('a2final-review','a2final-polecic',6),('a2final-review','a2final-podsumowac',7);

delete from public.questions where lesson_id in ('a2final-diagnosis','a2final-quiz','a2final-reading-check');
insert into public.questions(lesson_id,prompt,options,correct,explanation,position) values
('a2final-diagnosis','W sobotę Marta ___ do Krakowa i zwiedziła muzeum.','["pojechała","pojedzie","jechać"]',0,'Завершённое событие в прошлом требует формы pojechała.',0),
('a2final-diagnosis','Jutro rano ___ bilety na pociąg.','["kupimy","kupiliśmy","kupować"]',0,'Jutro указывает на будущее: kupimy.',1),
('a2final-diagnosis','W mieszkaniu nie ma ___.','["ciepłej wody","ciepła woda","ciepłą wodą"]',0,'После nie ma используется родительный падеж: ciepłej wody.',2),
('a2final-diagnosis','Ten plecak jest ___ niż tamten.','["lżejszy","najlżejszy","lekki od"]',0,'При сравнении двух предметов используется сравнительная степень + niż.',3),
('a2final-diagnosis','Составьте: Перед поездкой стоит проверить прогноз.','["Przed podróżą warto sprawdzić prognozę.","Przed podróż warto sprawdza prognoza.","Podróżą warto prognozę sprawdził."]',0,'После przed нужен творительный, после warto — инфинитив.',4),
('a2final-diagnosis','Ania powiedziała, ___ nie może przyjść, ___ jest chora.','["że; bo","bo; że","dlatego; czy"]',0,'Że вводит содержание сообщения, а bo — его причину.',5),
('a2final-diagnosis','Czytałem tę książkę. Polecam ___.','["ją","go","ich"]',0,'Książka — существительное женского рода, поэтому объект заменяется местоимением ją.',6),
('a2final-diagnosis','Составьте: Я хотел бы подать заявление завтра.','["Chciałbym złożyć wniosek jutro.","Chcę jutro wniosek daj.","Chciałbym złożyłem wniosek jutro."]',0,'Вежливая просьба строится как chciałbym + инфинитив złożyć.',7),
('a2final-quiz','Co powiesz o zakończonym weekendzie?','["W sobotę spotkałem się z przyjaciółmi.","W sobotę spotkam się wczoraj.","W sobotę spotykać przyjaciele."]',0,'Для законченного события используем прошедшее время.',0),
('a2final-quiz','Pociąg odjeżdża ___ Warszawy o siódmej.','["do","w","na"]',0,'Направление к городу передаётся конструкцией do + родительный падеж.',1),
('a2final-quiz','Hydraulik zajmuje się ___.','["naprawą kranu","naprawę kranu","naprawa kran"]',0,'Zajmować się требует творительного падежа: naprawą.',2),
('a2final-quiz','Najpierw ___ raport, a potem wysłałem go kierownikowi.','["napisałem","pisałem do końca","będę pisał"]',0,'Napisałem подчёркивает завершённый результат действия.',3),
('a2final-quiz','Który produkt kosztuje najmniej?','["najtańszy","tańszy niż","bardziej drogi"]',0,'Najtańszy — превосходная степень от tani.',4),
('a2final-quiz','Mam gorączkę. Co powinienem zrobić?','["Powinieneś odpocząć i skontaktować się z lekarzem.","Nie wolno zawsze lekarz.","Odpoczywałeś jutro."]',0,'Powinieneś + инфинитив выражает рекомендацию.',5),
('a2final-quiz','Ola była smutna, ___ nie dostała tej pracy.','["bo","że","dlatego"]',0,'Bo вводит причину эмоционального состояния.',6),
('a2final-quiz','Film był ciekawy, więc poleciłem ___ znajomym.','["go","ją","je"]',0,'Film — мужской род, объект заменяется местоимением go.',7),
('a2final-quiz','Jak grzecznie poprosić o informację w urzędzie?','["Czy może mi pani powiedzieć, gdzie mam podpisać?","Powiedz mi teraz, gdzie podpis!","Gdzie ja podpisuje pani?"]',0,'Czy może mi pani powiedzieć…? — нейтральная официальная просьба.',8),
('a2final-quiz','Jeśli jutro będzie burza, ___.','["zostaniemy w domu","zostaliśmy w domu wczoraj","zostać dom"]',0,'Реальное условие относится к будущему: jeśli będzie…, zostaniemy….',9),
('a2final-quiz','Najpierw zwiedziliśmy zamek, ___ poszliśmy na rynek.','["następnie","ponieważ","chociaż że"]',0,'Następnie связывает последовательные события рассказа.',10),
('a2final-quiz','Что лучше всего завершает связный рассказ?','["Na koniec podsumowałem, czego się nauczyłem.","Bo na koniec i dlatego.","Podsumować ja nauczył."]',0,'Финальный маркер na koniec и правильное прошедшее время создают ясное завершение.',11),
('a2final-reading-check','Dlaczego Lena pojechała do Torunia?','["Na weekend i spotkanie z kuzynką","Żeby złożyć reklamację","Na wizytę u lekarza"]',0,'Лена планировала выходные и встречу с двоюродной сестрой.',0),
('a2final-reading-check','Jaki problem pojawił się po przyjeździe?','["W pokoju nie działało ogrzewanie","Lena zgubiła paszport","Muzeum było zamknięte"]',0,'В комнате было холодно, потому что не работало отопление.',1),
('a2final-reading-check','Jak rozwiązano problem w hostelu?','["Recepcjonistka dała Lenie inny pokój","Lena kupiła nowy grzejnik","Kuzynka naprawiła okno"]',0,'После спокойного объяснения Лена получила другую комнату.',2),
('a2final-reading-check','Dlaczego Lena i Zosia zmieniły plan spaceru?','["Zaczął padać deszcz","Nie miały biletów","Pokłóciły się"]',0,'Из-за дождя они выбрали музей вместо долгой прогулки.',3),
('a2final-reading-check','Co Lena zrobiła przed powrotem?','["Kupiła syrop i zachowała paragon","Złożyła wniosek o paszport","Oddała bilet kolejowy"]',0,'В аптеке она купила сироп и сохранила чек.',4),
('a2final-reading-check','Jaki jest główny wniosek Leny?','["Spokój i jasne wyjaśnienie pomagają rozwiązać problem","Każdą podróż trzeba odwołać","W mieście nie warto pytać o pomoc"]',0,'В конце Лена подводит итог: спокойствие и ясная просьба помогают.',5);

insert into public.reading_texts(id,topic_id,title,description,level,minutes,emoji,paragraphs,glossary,source_metadata,position,is_active) values
('a2final-weekend-leny','a2final-review','Weekend, który sprawdził plan Leny','Поездка, неожиданности и спокойное решение проблем','A2',8,'🧭',
'["Lena zaplanowała weekend w Toruniu, gdzie miała spotkać się z kuzynką Zosią. W piątek kupiła bilet, sprawdziła prognozę pogody i zarezerwowała niedrogi pokój. Pociąg przyjechał zgodnie z planem, więc wieczorem obie zdążyły jeszcze zjeść kolację na Starym Mieście.","Po powrocie do hostelu Lena zauważyła, że w jej pokoju nie działa ogrzewanie. Najpierw zadzwoniła do recepcji, a potem spokojnie wyjaśniła sytuację. Recepcjonistka przeprosiła i zaproponowała cieplejszy pokój. Lena przyjęła propozycję, ponieważ nie chciała zaczynać weekendu od kłótni.","Następnego dnia zaczął padać deszcz, dlatego Lena i Zosia zmieniły plan. Zamiast długiego spaceru wybrały muzeum, które poleciła im recepcjonistka. Wystawa bardzo im się spodobała. Po południu Lena poczuła ból gardła, więc w aptece poprosiła o poradę, kupiła syrop i zachowała paragon.","W niedzielę pogoda się poprawiła i kuzynki krótko spacerowały nad Wisłą. Przed odjazdem Lena podsumowała weekend: nie wszystko wydarzyło się zgodnie z planem, ale każdy problem udało się rozwiązać. Zrozumiała, że warto zachować spokój, jasno prosić o pomoc i umieć zmienić plan."]',
'{"zarezerwowała":{"lemma":"zarezerwować","translation":"забронировать","part_of_speech":"глагол"},"zgodnie":{"lemma":"zgodnie","translation":"согласно; как было запланировано","part_of_speech":"наречие"},"zauważyła":{"lemma":"zauważyć","translation":"заметить","part_of_speech":"глагол"},"ogrzewanie":{"lemma":"ogrzewanie","translation":"отопление","part_of_speech":"существительное"},"wyjaśniła":{"lemma":"wyjaśnić","translation":"объяснить","part_of_speech":"глагол"},"zaproponowała":{"lemma":"zaproponować","translation":"предложить","part_of_speech":"глагол"},"kłótni":{"lemma":"kłótnia","translation":"ссора","part_of_speech":"существительное"},"wystawa":{"lemma":"wystawa","translation":"выставка","part_of_speech":"существительное"},"poradę":{"lemma":"porada","translation":"совет","part_of_speech":"существительное"},"zachowała":{"lemma":"zachować","translation":"сохранить","part_of_speech":"глагол"},"odjazdem":{"lemma":"odjazd","translation":"отъезд","part_of_speech":"существительное"},"podsumowała":{"lemma":"podsumować","translation":"подвести итог","part_of_speech":"глагол"}}',
'{"origin":"original","created_for":"PolskiFlow","verified_at":"2026-08-29","comprehension_lesson_id":"a2final-reading-check"}',23,true)
on conflict(id) do update set topic_id=excluded.topic_id,title=excluded.title,description=excluded.description,level=excluded.level,minutes=excluded.minutes,emoji=excluded.emoji,paragraphs=excluded.paragraphs,glossary=excluded.glossary,source_metadata=excluded.source_metadata,position=excluded.position,is_active=excluded.is_active;
